import test from 'node:test';
import assert from 'node:assert/strict';
import { createDefaultState, SAVE_VERSION, TECH_NODES } from '../src/data/defaultState.js';
import { featureUnlocked, SYSTEM_TECH_NODES, viewUnlocked } from '../src/config/balance.js';
import { buyHardware, buyTechNode, computePerSecond, economySnapshot, improveModel, marketMetrics, startDevelopmentCycle, tickGame, trainModel, trainingEtaSeconds, trainingRatePerSecond, trainingRequired, trainingRequiredForState, patentResearchRequired } from '../src/systems/GameSystem.js';
import { buyHardwareUpgrade, hardwareTrackBonus } from '../src/systems/HardwareUpgradeSystem.js';
import { techNodeState } from '../src/systems/TechSystem.js';
import { SaveSystem } from '../src/systems/PersistentSaveSystem.js';

function funded(){const state=createDefaultState();return{...state,resources:{...state.resources,credits:1e12},hardware:{...state.hardware,calculator:1}}}

test('Hardware produces Compute and continuously funds real Training work',()=>{let state=funded();assert(computePerSecond(state)>0);state=trainModel(state);const required=trainingRequiredForState(state),stored=state.resources.compute;state=tickGame(state,1000);assert(state.model.trainingProgress>0&&state.model.trainingProgress<required);assert(state.resources.compute<=stored);assert(state.statistics.totalComputeConsumed>0)});

test('more Hardware and more Training allocation reduce canonical Training ETA',()=>{let state=trainModel(funded());const initial=trainingEtaSeconds(state);state=buyHardware(state,'calculator');assert(trainingEtaSeconds(state)<initial);const hardwareEta=trainingEtaSeconds(state);state={...state,allocation:{training:80,inference:20,research:0,data:0,agents:0}};assert(trainingRatePerSecond(state)>0);assert(trainingEtaSeconds(state)<hardwareEta)});

test('Training grants unspent Model Points and specialization changes the real market',()=>{let state=funded();state={...state,hardware:{...state.hardware,calculator:100},model:{...state.model,xp:79,progress:{...state.model.progress,tinyChat:{...state.model.progress.tinyChat,xp:79}}}};state=trainModel(state);for(let i=0;i<120&&state.model.trainingActive;i++)state=tickGame(state,1000);assert(state.model.upgradePoints>0);const points=state.model.upgradePoints;state={...state,meta:{...state.meta,techNodes:['system-model-engineering']}};const before=marketMetrics(state).demand;state=improveModel(state,'tinyChat','popularity');assert.equal(state.model.upgradePoints,points-1);assert(marketMetrics(state).demand>before)});

test('removed Hardware sub-upgrades cannot change gameplay',()=>{const state=funded(),before=computePerSecond(state),next=buyHardwareUpgrade(state,'calculator','processor');assert.equal(next,state);assert.equal(hardwareTrackBonus(state,'hardwareOutput','calculator'),0);assert.equal(computePerSecond(next),before)});

test('canonical market can become either Demand or Capacity Limited',()=>{const capacityLimited={...funded(),hardware:{...funded().hardware,calculator:1},allocation:{training:0,inference:100,research:0,data:0,agents:0}};assert.equal(marketMetrics(capacityLimited).bottleneck,'CAPACITY LIMITED');const demandLimited={...funded(),hardware:{...funded().hardware,calculator:10000},allocation:{training:0,inference:100,research:0,data:0,agents:0},market:{...funded().market,priceMultiplier:3}};assert.equal(marketMetrics(demandLimited).bottleneck,'DEMAND LIMITED');for(const key of ['credits','creditsPerSecond','users','demand','capacity','utilization','bottleneck'])assert.notEqual(economySnapshot(demandLimited)[key],undefined)});

test('Energy is removed from active simulation and navigation',()=>{const state={...funded(),hardware:{...funded().hardware,workstation:1000}};assert.equal(featureUnlocked(state,'energy'),false);assert.equal(viewUnlocked(state,'energy'),false);assert.equal(economySnapshot(state).energyEfficiency,1);assert.equal(economySnapshot(state).energyDemand,0)});

test('Lifetime INT exposes but never auto-purchases system Tech',()=>{let state=createDefaultState();state={...state,meta:{...state.meta,intelligence:100,totalIntelligence:100}};assert(SYSTEM_TECH_NODES.every(node=>!state.meta.techNodes.includes(node.id)));assert.equal(featureUnlocked(state,'research'),false);assert.equal(techNodeState(state,SYSTEM_TECH_NODES[0]),'available');const before=state.meta.intelligence;state=buyTechNode(state,'system-model-engineering');assert.equal(state.meta.intelligence,before-1);assert(featureUnlocked(state,'modelSkills'))});

test('Development Cycles preserve purchased Tech while resetting run economy',()=>{let state={...funded(),meta:{...funded().meta,intelligence:3,totalIntelligence:3,techNodes:['system-model-engineering']},run:{...funded().run,computeProduced:1e9},hardware:{...funded().hardware,gpuServer:1},model:{...funded().model,level:9}};state=startDevelopmentCycle(state);assert(state.meta.techNodes.includes('system-model-engineering'));assert.equal(state.run.computeProduced,0)});

test('legacy Hardware sub-upgrades migrate into a deterministic Credit refund',()=>{const old=createDefaultState();old.version=12;old.upgrades=['calculator-cooling','calculator-tensor','calculator-compiler','company-brand'];const credits=old.resources.credits,storage=memoryStorage();storage.setItem('ai-singularity-save',JSON.stringify(old));const previous=globalThis.localStorage;globalThis.localStorage=storage;try{const loaded=new SaveSystem({}).load();assert.equal(loaded.version,SAVE_VERSION);assert.deepEqual(loaded.hardwareUpgradeLevels.calculator,{processor:0,memory:0,optimization:0});assert(loaded.resources.credits>credits);assert(!loaded.upgrades.includes('calculator-cooling'));assert(loaded.upgrades.includes('company-brand'))}finally{if(previous===undefined)delete globalThis.localStorage;else globalThis.localStorage=previous}});

test('future Tech nodes remain visible as authored data without granting features',()=>{const state=createDefaultState();assert(SYSTEM_TECH_NODES.length>=10);assert(SYSTEM_TECH_NODES.some(node=>node.feature==='research'));assert(!SYSTEM_TECH_NODES.some(node=>node.feature==='energy'));assert(SYSTEM_TECH_NODES.every(node=>['available','locked-int','locked-prerequisite','purchased'].includes(techNodeState(state,node))))});

function memoryStorage(){const map=new Map();return{getItem:key=>map.get(key)??null,setItem:(key,value)=>map.set(key,value),removeItem:key=>map.delete(key)}}

test('Hardware purchases remain the canonical way to accelerate Training',()=>{let state=trainModel(funded());const before=trainingEtaSeconds(state);state=buyHardware(state,'calculator');assert(trainingEtaSeconds(state)<before)});

test('Lifetime Intelligence provides canonical permanent income and spending does not reduce it',()=>{const base={...funded(),hardware:{...funded().hardware,calculator:20},meta:{...funded().meta,intelligence:10,totalIntelligence:10}};const income=economySnapshot(base).creditsPerSecond;const spent=buyTechNode(base,'compute-1');assert.equal(spent.meta.totalIntelligence,10);assert.equal(economySnapshot(spent).creditsPerSecond,income)});
test('Technology roadmap spans fifty nodes, astronomical costs, positions, and an acyclic graph',()=>{assert(TECH_NODES.length>=50);assert(Math.max(...TECH_NODES.map(node=>node.cost))>=1e36);assert(TECH_NODES.every(node=>Number.isFinite(node.position.x)&&Number.isFinite(node.position.y)));for(const node of TECH_NODES){const seen=new Set();let cursor=node;while(cursor?.requires){assert(!seen.has(cursor.id));seen.add(cursor.id);cursor=TECH_NODES.find(candidate=>candidate.id===cursor.requires)}}});
test('controlled Training and Patent curves increase without adjacent catastrophic jumps',()=>{const requirements=[1,5,10,25,50,61,100].map(trainingRequired);for(let index=1;index<requirements.length;index++)assert(requirements[index]/requirements[index-1]<1e8);const patents=Array.from({length:20},(_,index)=>patentResearchRequired(index));assert(patents.every((value,index)=>!index||value>patents[index-1]))});

test('one completed Training grants exactly one level and one model-specific point without XP',()=>{let state=funded();state={...state,hardware:{...state.hardware,calculator:100}};const before=state.model.progress.tinyChat;state=trainModel(state);state=tickGame(state,1000);const after=state.model.progress.tinyChat;assert.equal(after.level,before.level+1);assert.equal(after.upgradePoints,before.upgradePoints+1);assert.equal(after.xp,0);assert.equal(state.model.xp,0);assert.equal(state.model.trainingActive,false)});
test('first Model Point immediately purchases each basic specialization while advanced skills stay gated',()=>{for(const skill of ['quality','efficiency','popularity']){let state=funded();state.model.upgradePoints=1;state.model.progress.tinyChat.upgradePoints=1;const next=improveModel(state,'tinyChat',skill);assert.equal(next.model.progress.tinyChat.skills[skill],1);assert.equal(next.model.progress.tinyChat.upgradePoints,0)}let locked=funded();locked.model.upgradePoints=1;locked.model.progress.tinyChat.upgradePoints=1;assert.equal(improveModel(locked,'tinyChat','reasoning'),locked)});
test('Quality, Efficiency, and Popularity change distinct canonical economy outcomes',()=>{const base=funded();const upgrade=skill=>{const state=structuredClone(base);state.model.upgradePoints=1;state.model.progress.tinyChat.upgradePoints=1;return improveModel(state,'tinyChat',skill)};const original=economySnapshot(base),quality=economySnapshot(upgrade('quality')),efficiency=economySnapshot(upgrade('efficiency')),popularity=economySnapshot(upgrade('popularity'));assert(quality.demand>original.demand&&quality.revenuePerUser>original.revenuePerUser);assert(efficiency.capacity>original.capacity);assert(popularity.demand>original.demand)});
test('Model Point costs rise by rank and cannot overspend another Model pool',()=>{let state=funded();state.model.progress.tinyChat={...state.model.progress.tinyChat,upgradePoints:4,skills:{quality:3}};const next=improveModel(state,'tinyChat','quality');assert.equal(next.model.progress.tinyChat.upgradePoints,2);state.model.owned.push('smartChat');state.model.progress.smartChat={level:1,xp:0,upgradePoints:0,trainings:0,skills:{}};assert.equal(improveModel(state,'smartChat','quality'),state)});
test('Training requirements are finite and monotonic through level 500',()=>{const levels=[1,2,3,5,10,20,50,100,250,500],values=levels.map(trainingRequired);assert(values.every(Number.isFinite));assert(values.every((value,index)=>!index||value>values[index-1]))});
