import test from 'node:test';import assert from 'node:assert/strict';
import { createDefaultState,HARDWARE_CATALOG,MODEL_CATALOG } from '../src/data/defaultState.js';
import { acquireModel,buyHardware,buyMarketing,buyTechNode,canBreakthrough,canDevelop,buyPatentSlot,computePerSecond,cycleIntelligence,economySnapshot,improveModel,marketMetrics,patentCurrentBonus,patentResearchPerSecond,patentResearchRequired,revenuePerUser,startBreakthrough,startDevelopmentCycle,tickGame,trainModel,trainingRequiredForState,togglePatentEquipped,upgradePatent } from '../src/systems/GameSystem.js';
import { BALANCE, featureUnlocked, viewUnlocked } from '../src/config/balance.js';
import { formatNumber } from '../src/ui/number-format.js';
import { BottleneckAnalyzer } from '../src/dev/bottleneck-analyzer.js';
import { DowntimeAnalyzer } from '../src/dev/downtime-analyzer.js';
import { MeaningfulActionService } from '../src/dev/meaningful-action-service.js';
import { OverloadAnalyzer } from '../src/dev/overload-analyzer.js';
import { createCompleteSessionExport,exportCSV,exportJSON,exportMarkdown,importJSON } from '../src/dev/report-exporter.js';
import { analyzeSession,calculateFunDensity } from '../src/dev/session-analyzer.js';
import { TelemetrySampler } from '../src/dev/telemetry-sampler.js';
import { createTelemetryEvent,validateTelemetryEvent,MAX_EVENTS } from '../src/dev/telemetry-events.js';
import { isDeveloperMode,TelemetryService } from '../src/dev/telemetry-service.js';
import { MAX_SESSIONS,TelemetryStorage } from '../src/dev/telemetry-storage.js';
import { runSimulation } from '../src/dev/deterministic-simulator.js';
import { SaveSystem } from '../src/systems/PersistentSaveSystem.js';
import { DeveloperResetService,FRESH_RESET_MARKER } from '../src/dev/developer-reset-service.js';

const state=()=>({...createDefaultState(),tutorial:{step:10,completed:true}});const event=(type,seconds,extra={})=>createTelemetryEvent({type,category:'progression',sessionSeconds:seconds,...extra},{sequence:seconds+1,sessionSeconds:seconds});
test('event schema is valid, monotonic, and immutable',()=>{const before={credits:10,nested:{value:1}};const one=createTelemetryEvent({type:'x',category:'purchase',timestamp:100,sessionSeconds:5,before},{sequence:1,sessionSeconds:5});before.nested.value=9;const two=createTelemetryEvent({type:'y',category:'purchase',timestamp:90,sessionSeconds:3},{sequence:2,lastTimestamp:100,lastSessionSeconds:5});assert(validateTelemetryEvent(one));assert.equal(two.timestamp,100);assert.equal(two.sessionSeconds,5);assert.equal(one.before.nested.value,1);assert(Object.isFrozen(one.before))});
test('click bursts aggregate rapid clicks',()=>{let now=1000;const t=new TelemetryService({clock:()=>now,storage:null});t.start(state());for(let i=0;i<5;i++){t.optimizeClick();now+=100}now+=2000;t.flushClickBurst(state());const burst=t.events.find(e=>e.type==='click-burst-ended');assert.equal(burst.amount,5);assert(burst.metadata.clicksPerSecond>0)});
test('sampling intervals are configurable and records are bounded with aggregation',()=>{const sampler=new TelemetrySampler(5);assert(sampler.sample(state(),0));assert.equal(sampler.sample(state(),4),null);sampler.setInterval(1);assert(sampler.sample(state(),4));for(let i=5;i<10030;i++)sampler.sample(state(),i);assert(sampler.samples.length<=10000);assert(sampler.samples.some(s=>s.aggregated))});
test('event limits aggregate old records while preserving beginning',()=>{let now=0;const t=new TelemetryService({clock:()=>now,storage:null});t.start(state());const first=t.events[0].id;for(let i=0;i<MAX_EVENTS+30;i++){now++;t.record({type:'noise',category:'session'},state())}assert.equal(t.events[0].id,first);assert(t.events.some(e=>e.type==='aggregated-events'));assert(t.events.length<=MAX_EVENTS+1)});
test('downtime starts, ends, and ignores background time',()=>{const d=new DowntimeAnalyzer();const snapshot={usefulPurchases:0,claimableRewards:0,strategicChoice:false,bottleneck:'Credits Limited',credits:0,research:0,energyEfficiency:1,researchRate:1,cheapestUsefulEta:90,cheapestUsefulLabel:'Calculator',trainingActive:false};d.update({seconds:31,lastActionSeconds:0,backgrounded:false,snapshot,lastAction:null});assert(d.active);d.update({seconds:50,lastActionSeconds:0,backgrounded:true,snapshot,lastAction:null});assert.equal(d.periods.length,1);const fresh=new DowntimeAnalyzer();fresh.update({seconds:100,lastActionSeconds:0,backgrounded:true,snapshot,lastAction:null});assert.equal(fresh.active,null)});
test('overload detection retains contributing events',()=>{const analyzer=new OverloadAnalyzer(),events=Array.from({length:5},(_,i)=>event('achievement-unlocked',i,{reward:true}));assert(analyzer.analyze(events));assert.equal(analyzer.periods[0].eventIds.length,5)});
test('bottleneck transitions are recorded',()=>{const b=new BottleneckAnalyzer(),base={energyEfficiency:1,trainingActive:false,trainingRate:1,patentEta:0,researchRate:1,usefulPurchases:1,cheapestUsefulEta:0,capacity:20,demand:10,marketing:2,reputation:2,modelQuality:3,users:5,adoption:20};b.update(base,0);const transition=b.update({...base,capacity:5,demand:20},10);assert.equal(transition.previous,'Demand Limited');assert.equal(b.current.name,'Capacity Limited');assert.equal(b.periods[0].duration,10)});
test('meaningful action statistics include median and p90',()=>{const m=new MeaningfulActionService();m.record(event('hardware-purchased',10,{meaningful:true}));m.record(event('run-upgrade-purchased',30,{meaningful:true}));m.record(event('patent-discovered',70,{meaningful:true}));const s=m.summary();assert.equal(s.average,30);assert.equal(s.median,20);assert.equal(s.longest,40);assert(s.p90>=20)});
test('Fun Density always remains within zero and one hundred',()=>{assert.equal(calculateFunDensity([],[],[],0).score,45);const many=Array.from({length:30},(_,i)=>event('reward',i,{meaningful:true,reward:true}));assert.equal(calculateFunDensity(many,[],[],30).score,100);assert(calculateFunDensity([], [{severity:'severe',end:0}], [{end:0}], 0).score>=0)});
test('reports contain required fields and export round trips',()=>{const sample={sessionSeconds:0,runSeconds:0,developmentCycle:0,credits:10,lifetimeCredits:0,creditsPerSecond:1,computePerSecond:1,users:1,demand:1,capacity:1,utilization:1,energyEfficiency:1,funDensity:50};const raw={startTimestamp:1,endTimestamp:2,durationSeconds:1,events:[],samples:[sample],downtime:[],overloads:[],meaningfulSummary:{average:0,median:0,p90:0,longest:0},bottleneckSummary:{percentages:{},longest:null,transitions:0}};const summary=analyzeSession(raw);assert(summary.session&&summary.economy&&summary.progression&&summary.activity&&summary.pacing&&summary.bottlenecks&&summary.balanceFlags);const payload={summary,events:[],samples:[sample],downtimePeriods:[],overloadPeriods:[],bottleneckPeriods:[],balanceFlags:[]};const imported=importJSON(exportJSON(payload));assert.deepEqual(imported.samples,payload.samples);assert(exportCSV([sample]).includes('sessionSeconds'));assert(exportMarkdown(summary).includes('Automatic Analysis'))});
test('session storage retains ten recent plus pinned sessions',()=>{const memory=mockStorage(),storage=new TelemetryStorage(memory);for(let i=0;i<12;i++)storage.save({id:`s${i}`,date:i});assert.equal(storage.list().length,MAX_SESSIONS);storage.pin('s11');for(let i=12;i<15;i++)storage.save({id:`s${i}`,date:i});assert(storage.list().find(s=>s.id==='s11')?.pinned);storage.delete('s11');assert(!storage.list().some(s=>s.id==='s11'))});
test('cheats mark sessions non-natural',()=>{const t=new TelemetryService({storage:null});t.start(state());t.markCheat('credits',state());assert.equal(t.natural,false);assert(t.events.some(e=>e.type==='developer-cheat'))});
test('imported telemetry does not alter game state',()=>{const game=state(),copy=structuredClone(game);const report={summary:{},events:[],samples:[],downtimePeriods:[],overloadPeriods:[],bottleneckPeriods:[],balanceFlags:[]};importJSON(exportJSON(report));assert.deepEqual(game,copy)});
test('developer mode is hidden by default and query-gated',()=>{const storage=mockStorage();assert.equal(isDeveloperMode({search:''},storage),false);assert.equal(isDeveloperMode({search:'?dev=1'},storage),true);storage.setItem('ai-singularity-dev-mode','1');assert.equal(isDeveloperMode({search:''},storage),true)});
test('telemetry observation does not alter economy',()=>{let a=state(),b=structuredClone(a);const telemetry=new TelemetryService({storage:null});telemetry.start(a);for(let i=0;i<20;i++){const prior=a;a=tickGame(a,1000);telemetry.observe(prior,a,'game-loop');b=tickGame(b,1000)}assert.deepEqual(a,b)});
test('deterministic simulation emits telemetry without touching human state',()=>{const human=state(),copy=structuredClone(human),simulation=runSimulation('Balanced',.1);assert(simulation.report.samples.length>0);assert(simulation.report.events.some(item=>item.type==='hardware-purchased'));assert.equal(simulation.report.summary.progression.hardwarePurchases,Object.values(simulation.state.hardware).reduce((sum,value)=>sum+value,0));assert(simulation.report.summary.economy.creditsEarned>0);assert(simulation.report.samples.some(sample=>sample.computePerSecond>0&&sample.users>0));assert.deepEqual(human,copy)});
test('events carry identity, version, lifetime context, and meaningful snapshots',()=>{let now=1000;const storage=mockStorage(),telemetry=new TelemetryService({clock:()=>now,storage}),before=state();telemetry.start(before);now+=5000;const after=buyHardware(before,'calculator');telemetry.observe(before,after,'hardware');const purchase=telemetry.events.find(item=>item.type==='hardware-purchased');assert(purchase.sessionId&&purchase.runId&&purchase.playerId);assert.equal(purchase.saveVersion,18);assert.equal(purchase.gameVersion,'0.17.0');assert.equal(purchase.playerSnapshot.credits,after.resources.credits);assert.equal(purchase.metadata.hardwareId,'calculator');assert.equal(purchase.metadata.previousAmount,0);assert(telemetry.events.some(item=>item.type==='first-hardware-purchase'))});
test('Patents equip, upgrade with INT, and buy permanent Gem slots',()=>{let game=state();game={...game,patents:{...game.patents,discovered:['cold-kernels']},meta:{...game.meta,intelligence:100,totalIntelligence:100,techNodes:['system-model-engineering','system-allocation','system-research','system-patents']},resources:{...game.resources,gems:1000}};game=togglePatentEquipped(game,'cold-kernels');assert.deepEqual(game.patents.equipped,['cold-kernels']);const bonus=patentCurrentBonus(game,'cold-kernels');game=upgradePatent(game,'cold-kernels');assert(patentCurrentBonus(game,'cold-kernels')>bonus);assert.equal(game.patents.intInvested['cold-kernels'],2);game=buyPatentSlot(game);assert.equal(game.patents.slots,4);assert.equal(game.resources.gems,750)});
test('developer reset removes game persistence and recreates a first-launch state',async()=>{const local=mockStorage(),session=mockStorage();local.setItem('ai-singularity-save','progressed');local.setItem('ai-singularity-dev-sessions','history');local.setItem('ai-singularity-simulation-cache','simulation');local.setItem('unrelated-app','keep');session.setItem('ai-singularity-session-cache','stale');const deleted=[];const database={databases:async()=>[{name:'ai-singularity-telemetry'},{name:'unrelated-db'}],deleteDatabase:name=>{deleted.push(name);const request={};Promise.resolve().then(()=>request.onsuccess?.());return request}};let telemetryCleared=false,reloaded=false,fresh;const service=new DeveloperResetService({local,session,database});await service.reset({telemetry:{clearAll:()=>{telemetryCleared=true}},replaceState:()=>{fresh=createDefaultState()},reload:()=>{reloaded=true}});assert.equal(local.getItem('ai-singularity-save'),null);assert.equal(local.getItem('ai-singularity-dev-sessions'),null);assert.equal(local.getItem('ai-singularity-simulation-cache'),null);assert.equal(local.getItem('unrelated-app'),'keep');assert.equal(session.getItem('ai-singularity-session-cache'),null);assert.deepEqual(deleted,['ai-singularity-telemetry']);assert(telemetryCleared&&reloaded);assert.equal(fresh.tutorial.step,0);assert(Object.values(fresh.hardware).every(value=>value===0));assert.deepEqual(fresh.model.owned,createDefaultState().model.owned);assert.equal(fresh.upgrades.length,0);assert.equal(fresh.patents.discovered.length,0);assert.equal(fresh.meta.intelligence,0);assert.equal(fresh.resources.gems,0);assert.equal(session.getItem(FRESH_RESET_MARKER),'1');assert.equal(service.consumeFreshResetMarker(),true);assert.equal(service.consumeFreshResetMarker(),false)});
test('cleared telemetry stays empty until the reloaded session starts',()=>{const storage=mockStorage(),telemetry=new TelemetryService({storage});telemetry.start(state());telemetry.storage.save({id:'old'});telemetry.clearAll();telemetry.observe(state(),tickGame(state(),1000),'game-loop');assert.equal(telemetry.events.length,0);assert.equal(telemetry.sampler.samples.length,0);assert.deepEqual(telemetry.storage.list(),[]);const fresh=new TelemetryService({storage});fresh.start(createDefaultState(),{silent:true});assert.equal(fresh.events.filter(event=>event.type==='run-started').length,1);assert(fresh.sessionId&&fresh.runId)});
test('Milestone 11 patent and prestige curves enforce long-term pacing',()=>{const game=createDefaultState(),unlocked={...game,meta:{...game.meta,totalIntelligence:20,techNodes:['system-model-engineering','system-allocation','system-research','system-patents']},allocation:{...game.allocation,research:15},hardware:{...game.hardware,calculator:1}},rate=patentResearchPerSecond(unlocked);assert(rate>0);const firstMinutes=patentResearchRequired(0)/rate/60;assert(firstMinutes>=20&&firstMinutes<=30);const requirements=Array.from({length:50},(_,index)=>patentResearchRequired(index));assert(requirements.reduce((sum,value)=>sum+value,0)>requirements[0]*5000);assert(cycleIntelligence({...game,run:{...game.run,computeProduced:BALANCE.intelligence.computeScale*100},hardware:{...game.hardware,miniDatacenter:1},model:{...game.model,level:9}})>0)});
test('one-second telemetry exports economy, hardware, patent, and actionable purchase context',()=>{let now=0,game=createDefaultState();game={...game,hardware:{...game.hardware,calculator:1}};const telemetry=new TelemetryService({clock:()=>now,storage:null});telemetry.start(game);const before={...game,resources:{...game.resources,credits:100}};const after=buyHardware(before,'calculator');now=1000;telemetry.observe(before,after,'hardware');const sample=telemetry.sampler.samples.at(-1),purchase=telemetry.events.find(e=>e.type==='hardware-purchased'),report=telemetry.getReport();for(const key of ['credits','creditsPerSecond','compute','computePerSecond','trainingCompute','research','users','demand','capacity','reputation','adoption','marketing','priceMultiplier','revenuePerUser','revenuePerSecond','effectiveMultipliers','bottleneck','computeConsumed','computeWasted','trainingTarget','currentPatent','currentTechBranch','currentIntelligence'])assert.notEqual(sample[key],undefined,key);assert.equal(telemetry.sampler.interval,1);assert.equal(purchase.metadata.itemCategory,'hardware');assert(Number.isFinite(purchase.metadata.expectedProductionIncrease));assert('roi'in purchase.metadata&&'paybackTime'in purchase.metadata&&'availableAlternatives'in purchase.metadata);assert(report.summary.hardware&&report.summary.models&&report.summary.patents&&report.summary.prestige);assert(exportMarkdown(report.summary).includes('## Suggestions'))});
test('models unlock permanently with INT instead of Credits',()=>{let game=createDefaultState();const credits=game.resources.credits;game={...game,meta:{...game.meta,intelligence:2,totalIntelligence:2,techNodes:['system-model-engineering']}};game=acquireModel(game,'smartChat');assert(game.model.owned.includes('smartChat'));assert(game.meta.unlockedModels.includes('smartChat'));assert.equal(game.meta.intelligence,2);assert.equal(game.resources.credits,credits);game={...game,run:{...game.run,computeProduced:BALANCE.intelligence.computeScale*100},hardware:{...game.hardware,miniDatacenter:1},model:{...game.model,level:9}};game=startDevelopmentCycle(game);assert(game.model.owned.includes('smartChat'));assert(game.meta.unlockedModels.includes('smartChat'))});
test('training grants exactly one immediately usable Model Point',()=>{let game=createDefaultState();game.hardware.calculator=100;game=trainModel(game);const before=game.model.level;game=tickGame(game,1000);assert.equal(game.model.level,before+1);assert.equal(game.model.xp,0);assert.equal(game.model.upgradePoints,1);game=improveModel(game,'tinyChat','quality');assert.equal(game.model.upgradePoints,0)});
test('decision analytics records real page visits and durations',()=>{let now=0,game=createDefaultState();const telemetry=new TelemetryService({clock:()=>now,storage:null});telemetry.start(game);now=5000;const market={...game,ui:{...game.ui,activeView:'market'}};telemetry.observe(game,market,'navigation');now=12000;const model={...market,ui:{...market.ui,activeView:'model'}};telemetry.observe(market,model,'navigation');const pages=telemetry.getReport().summary.decisions.pages;assert.equal(pages.dashboard.totalDuration,5);assert.equal(pages.market.totalDuration,7);assert.equal(pages.model.visits,1);assert(telemetry.getReport().summary.timeline.some(item=>item.type==='navigation-view-opened'))});
test('waiting analytics identifies inactivity despite affordable choices',()=>{const analyzer=new DowntimeAnalyzer(),snapshot={affordablePurchases:2,usefulPurchases:1,claimableRewards:0,strategicChoice:false,developmentCycleEligible:false,cheapestUsefulLabel:'Calculator',cheapestUsefulEta:0,credits:100,compute:0,research:0,energyEfficiency:1,trainingProgress:0,patentProgress:0,trainingActive:false,patentEta:Infinity,researchRate:0,computePerSecond:0,bottleneck:'Credits Limited'};analyzer.update({seconds:10,lastActionSeconds:0,backgrounded:false,snapshot,lastAction:null});assert.equal(analyzer.active.cause,'waiting-although-affordable-purchase-exists');assert(analyzer.active.recommendedFix.includes('Calculator'));analyzer.update({seconds:120,lastActionSeconds:0,backgrounded:false,snapshot,lastAction:null});assert.deepEqual(analyzer.active.thresholdsReached,[10,20,40,60,120])});
test('model identities and unlocked skill builds change different economy outputs',()=>{const base={...createDefaultState(),meta:{...createDefaultState().meta,totalIntelligence:55,techNodes:['system-model-engineering','system-allocation','system-research','system-patents']},allocation:{...createDefaultState().allocation,research:15},hardware:{...createDefaultState().hardware,calculator:10}};const vision={...base,model:{...base.model,activeId:'omni',owned:['tinyChat','omni'],deployed:['omni'],progress:{...base.model.progress,omni:{level:1,xp:0,upgradePoints:0,skills:{}}}}};const enterprise={...base,model:{...base.model,activeId:'enterprise',owned:['tinyChat','enterprise'],deployed:['enterprise'],progress:{...base.model.progress,enterprise:{level:1,xp:0,upgradePoints:0,skills:{}}}}};assert(marketMetrics(vision).demand>marketMetrics(base).demand);assert(revenuePerUser(enterprise)>revenuePerUser(base));let skilled={...base,model:{...base.model,upgradePoints:1,progress:{tinyChat:{...base.model.progress.tinyChat,upgradePoints:1}}}};const researchBefore=patentResearchPerSecond(skilled);skilled=improveModel(skilled,'tinyChat','research');assert(patentResearchPerSecond(skilled)>researchBefore)});
test('save version 8 models migrate into authored Milestone 11 progression',()=>{const storage=mockStorage(),previous=globalThis.localStorage,legacy=createDefaultState();legacy.version=8;legacy.model={...legacy.model,activeId:'scientificAi',owned:['tinyChat','scientificAi'],deployed:['scientificAi'],progress:undefined};delete legacy.meta.unlockedModels;storage.setItem('ai-singularity-save',JSON.stringify(legacy));globalThis.localStorage=storage;try{const loaded=new SaveSystem({}).load();assert.equal(loaded.version,18);assert.equal(loaded.model.activeId,'research');assert(loaded.model.owned.includes('research'));assert(loaded.meta.unlockedModels.includes('research'));assert(loaded.model.progress.research)}finally{if(previous===undefined)delete globalThis.localStorage;else globalThis.localStorage=previous}});
test('Calculator fleet keeps increasing Compute and Credits beyond the old Energy cap',()=>{let game=createDefaultState();game={...game,resources:{...game.resources,credits:10000}};const rates=[];for(let index=0;index<20;index++){game=buyHardware(game,'calculator');rates.push(computePerSecond(game))}assert(rates.every((rate,index)=>index===0||rate>rates[index-1]));for(let second=0;second<120;second++)game=tickGame(game,1000);const before=game.resources.credits;for(let second=0;second<60;second++)game=tickGame(game,1000);assert(game.resources.credits>before);assert(economySnapshot(game).creditsPerSecond>0);assert.equal(economySnapshot(game).energyEfficiency,1)});
test('Milestone 10 Hardware and Model progression uses the authored order',()=>{assert.deepEqual(HARDWARE_CATALOG.map(item=>item.name),['Calculator','Pocket Computer','Laptop','Gaming PC','Workstation','Server Rack','GPU Cluster','Datacenter','Hyperscale Center','Orbital Datacenter','Moon Compute Facility','Mars Compute Grid','Fusion Compute Network','Dyson Compute Array','Matrioshka Brain','Singularity Core']);assert(HARDWARE_CATALOG.every((item,index)=>index===0||item.baseCost>HARDWARE_CATALOG[index-1].baseCost));const locked={...createDefaultState(),resources:{...createDefaultState().resources,credits:1e9}};assert.equal(buyHardware(locked,'workstation'),locked);assert.deepEqual(MODEL_CATALOG.map(model=>model.name),['TinyChat','SmartChat','GPT-Class','Omni','Research','Agent','Enterprise','AGI','ASI Seed']);assert.deepEqual(createDefaultState().model.owned,['tinyChat'])});
test('Patent curve reaches six months before Research build acceleration',()=>{const requirements=Array.from({length:50},(_,index)=>patentResearchRequired(index));assert(requirements.every((value,index)=>!index||value>requirements[index-1]));assert(requirements.at(-1)>requirements[0]*1e8)});
test('stored Optimize Compute is consumed by active Training',()=>{let game=createDefaultState();game={...game,hardware:{...game.hardware,calculator:1},resources:{...game.resources,compute:100}};game=trainModel(game);const before=game.resources.compute;game=tickGame(game,1000);assert(game.resources.compute<before);assert(game.statistics.totalComputeConsumed>0)});
test('telemetry samples match the canonical effective economy snapshot',()=>{let game=createDefaultState();game={...game,hardware:{...game.hardware,calculator:7}};game=tickGame(game,1000);const sample=new TelemetrySampler(1).sample(game,1),economy=economySnapshot(game);for(const key of ['credits','creditsPerSecond','compute','computePerSecond','computeConsumed','computeWasted','users','demand','capacity','utilization','energyProduction','energyDemand','energyEfficiency','currentHardwareTier','currentModel','modelLevel','modelXp','currentObjective'])assert.equal(sample[key],economy[key],key)});
test('Development Cycles derive INT from run Compute and cannot repeat for free',()=>{let game=createDefaultState();game={...game,run:{...game.run,computeProduced:BALANCE.intelligence.computeScale*100},hardware:{...game.hardware,miniDatacenter:1},model:{...game.model,level:9}};assert(canDevelop(game));game=startDevelopmentCycle(game);assert.equal(game.run.computeProduced,0);assert(game.meta.totalIntelligence>=1);assert.equal(canDevelop(game),false)});
test('fresh saves reveal only core views and unlock systems with lifetime INT',()=>{const fresh=createDefaultState();for(const view of ['dashboard','hardware','model','objectives'])assert(viewUnlocked(fresh,view));for(const view of ['market','allocation','patents','strategy'])assert.equal(viewUnlocked(fresh,view),false);const progressed={...fresh,meta:{...fresh.meta,totalIntelligence:55}};assert(featureUnlocked(progressed,'modelSkills'));assert.equal(featureUnlocked(progressed,'marketing'),true);for(const feature of ['research','patents'])assert.equal(featureUnlocked(progressed,feature),false);const purchased={...progressed,meta:{...progressed.meta,techNodes:['system-model-engineering','system-marketing','system-allocation','system-research','system-patents','system-automation']}};for(const feature of ['marketing','research','patents','modelSkills'])assert(featureUnlocked(purchased,feature))});
test('custom notation advances beyond trillions without scientific notation',()=>{assert.equal(formatNumber(999),'999');assert.equal(formatNumber(1_500),'1.5K');assert.equal(formatNumber(2e6),'2M');assert.equal(formatNumber(1e15),'1aa');assert.equal(formatNumber(1e18),'1ab');assert(!formatNumber(1e120).includes('e+'))});
test('Breakthrough is a real late-game reset that preserves account valuables',()=>{let game=createDefaultState();game={...game,resources:{...game.resources,gems:17},statistics:{...game.statistics,totalComputeProduced:BALANCE.breakthrough.requiredCompute},meta:{...game.meta,totalIntelligence:BALANCE.breakthrough.requiredLifetimeIntelligence,intelligence:500,techNodes:['compute-1'],achievements:{'compute-1':1}},patents:{...game.patents,levels:{'cold-kernels':4}}};assert(canBreakthrough(game));game=startBreakthrough(game);assert.equal(game.resources.gems,17);assert.equal(game.meta.intelligence,0);assert.equal(game.meta.techNodes.length,0);assert.equal(Object.keys(game.patents.levels).length,0);assert(game.meta.breakthroughCurrency>0)});
function mockStorage(){const data=new Map();return{get length(){return data.size},key:index=>[...data.keys()][index]??null,getItem:k=>data.get(k)??null,setItem:(k,v)=>data.set(k,v),removeItem:k=>data.delete(k),clear:()=>data.clear()}}

test('training telemetry records real elapsed time, compute investment, levels, and modifiers',()=>{let now=1_000,game=createDefaultState();game={...game,hardware:{...game.hardware,calculator:10}};const telemetry=new TelemetryService({clock:()=>now,storage:null});telemetry.start(game);let next=trainModel(game);telemetry.observe(game,next,'training');game=next;for(let seconds=0;seconds<600&&game.model.trainingActive;seconds++){now+=1_000;next=tickGame(game,1_000);telemetry.observe(game,next,'game-loop');game=next}const completion=telemetry.events.find(event=>event.type==='model-training-completed');assert(completion);assert(completion.metadata.actualDuration>0);assert(completion.metadata.effectiveDuration>0);assert(completion.metadata.computeInvested>0);assert(completion.metadata.trainingCompletionTimestamp>=completion.metadata.trainingStartTimestamp);assert.equal(completion.metadata.modelId,'tinyChat');assert(completion.metadata.resultingModelLevel>=completion.metadata.startingModelLevel);assert(Number.isFinite(completion.metadata.baseExpectedDuration));assert(completion.metadata.relevantTrainingModifiers.trainingMultiplier>0)});

test('active session duration is not reduced twice by background time',()=>{let now=1_000;const telemetry=new TelemetryService({clock:()=>now,storage:null});const game=createDefaultState();telemetry.start(game);now=11_000;telemetry.pause(game);now=31_000;telemetry.resume(game);now=41_000;const report=telemetry.getReport();assert.equal(report.summary.session.activePlaytime,20);assert.equal(report.summary.session.backgroundTime,20);assert.equal(report.summary.session.averageSessionLength,20)});
test('Development Cycles end and start Runs without ending the Human Session',()=>{let now=1_000,before=state();before={...before,run:{...before.run,computeProduced:1e12,creditsEarned:1e9},hardware:{...before.hardware,miniDatacenter:1},model:{...before.model,level:9}};const telemetry=new TelemetryService({clock:()=>now,storage:null});telemetry.start(before);const sessionId=telemetry.sessionId;now+=2_000;const after=startDevelopmentCycle(before);telemetry.observe(before,after,'development-cycle');assert.equal(telemetry.sessionId,sessionId);assert(telemetry.events.some(event=>event.type==='run-ended'));assert(telemetry.events.some(event=>event.type==='run-started'));const report=telemetry.getReport().summary;assert(report.runs.length>=2);assert.equal(after.session.elapsedMs,before.session.elapsedMs)});
test('Model build telemetry records spent points and canonical before-after economy',()=>{let now=1_000,before=state();before.hardware.calculator=10;before.model.upgradePoints=1;before.model.progress.tinyChat.upgradePoints=1;const telemetry=new TelemetryService({clock:()=>now,storage:null});telemetry.start(before);now+=500;const after=improveModel(before,'tinyChat','popularity');telemetry.observe(before,after,'model');const event=telemetry.events.find(entry=>entry.type==='model-improvement-purchased');assert.equal(event.metadata.skill,'popularity');assert.equal(event.metadata.pointsSpent,1);assert(event.metadata.economyImpact.demandAfter>event.metadata.economyImpact.demandBefore)});

test('every completed Training grants exactly one accounted Model Point',()=>{let game=state();game.hardware.calculator=100;for(let run=0;run<3;run++){game=trainModel(game);game={...game,model:{...game.model,trainingProgress:trainingRequiredForState(game)-0.001}};game=tickGame(game,1000);const progress=game.model.progress.tinyChat;assert.equal(progress.level,run+2);assert.equal(progress.trainings,run+1);assert.equal(progress.upgradePoints,run+1);assert.equal(progress.totalPointsEarned,run+1);assert.equal(progress.totalPointsSpent,0)}game=improveModel(game,'tinyChat','quality');const progress=game.model.progress.tinyChat;assert.equal(progress.totalPointsEarned,progress.upgradePoints+progress.totalPointsSpent)});
test('Training and spending emit canonical Model Point telemetry',()=>{let now=1_000,game=state();game.hardware.calculator=1;const telemetry=new TelemetryService({clock:()=>now,storage:null});telemetry.start(game);let next=trainModel(game);telemetry.observe(game,next,'training');game=next;next=tickGame({...game,model:{...game.model,trainingProgress:trainingRequiredForState(game)-.001}},1000);now+=1_000;telemetry.observe(game,next,'game-loop');game=next;next=improveModel(game,'tinyChat','quality');now+=1_000;telemetry.observe(game,next,'model-skill');const earned=telemetry.events.find(event=>event.type==='model-point-earned'),spent=telemetry.events.find(event=>event.type==='model-skill-upgraded');assert.equal(earned.metadata.pointsBefore,0);assert.equal(earned.metadata.pointsAfter,1);assert.equal(earned.metadata.levelAfter,2);assert.equal(spent.metadata.skill,'quality');assert.equal(spent.metadata.pointCost,1);assert.equal(spent.metadata.pointsBefore,1);assert.equal(spent.metadata.pointsAfter,0);assert(spent.sessionId&&spent.runId);assert(spent.metadata.economyImpact.demandAfter>spent.metadata.economyImpact.demandBefore)});
test('complete export marks empty progressed sessions BROKEN and missing samples INCOMPLETE',()=>{const ending={sessionSeconds:223,activeModel:'tinyChat',models:{tinyChat:{level:2}},highestHardwareTier:1};const broken=createCompleteSessionExport({events:[],samples:[],startingState:{activeModel:'tinyChat',models:{tinyChat:{level:1}},highestHardwareTier:0},endingState:ending,summary:{session:{totalDuration:223,activePlaytime:223},runs:[],economy:{},models:{trainingCompletions:[]},progression:{},decisions:{}}});assert.equal(broken.telemetryHealth,'BROKEN');assert(broken.validation.issues.some(issue=>issue.includes('no gameplay events')));const incomplete=createCompleteSessionExport({events:[{type:'session-start',timestamp:1,sessionSeconds:0}],samples:[],startingState:ending,endingState:ending,summary:{session:{totalDuration:223,activePlaytime:223},runs:[],economy:{},models:{trainingCompletions:[]},progression:{},decisions:{}}});assert.equal(incomplete.telemetryHealth,'INCOMPLETE')});
test('live export preparation uses the active recorder and always captures current state',()=>{let now=1_000,game={...state(),resources:{...state().resources,credits:1e6}};const telemetry=new TelemetryService({clock:()=>now,storage:null});telemetry.start(game);game=buyHardware(game,'calculator');now=2_000;telemetry.observe(telemetry.lastState,game,'hardware');const report=telemetry.prepareExport(game),complete=createCompleteSessionExport(report);assert(report===telemetry.getReport()||report.events===telemetry.events);assert(complete.events.some(event=>event.type==='hardware-purchased'));assert(complete.samples.length>0);assert.equal(complete.identity.sessionId,telemetry.sessionId);assert.equal(complete.telemetryHealth,'HEALTHY')});
test('complete export captures Marketing, Model skill, and Technology purchase loop',()=>{let now=1_000,game={...state(),resources:{...state().resources,credits:1e9},hardware:{...state().hardware,calculator:1},meta:{...state().meta,intelligence:20,totalIntelligence:20,cycles:1}};const telemetry=new TelemetryService({clock:()=>now,storage:null});telemetry.start(game);const observe=(next,source)=>{now+=1_000;telemetry.observe(game,next,source);game=next};observe(buyMarketing(game),'market');for(let i=0;i<2;i++){observe(trainModel(game),'training');observe(tickGame({...game,model:{...game.model,trainingProgress:trainingRequiredForState(game)-.001}},1000),'game-loop')}observe(improveModel(game,'tinyChat','quality'),'model-skill');telemetry.record({category:'technology',type:'technology-node-selected',source:'tech-tree',label:'compute-1',metadata:{nodeId:'compute-1',interaction:'tap'}},game);observe(buyTechNode(game,'compute-1'),'tech');const complete=createCompleteSessionExport(telemetry.prepareExport(game));for(const type of ['marketing-purchased','model-skill-upgraded','technology-node-selected','technology-node-purchased'])assert(complete.events.some(event=>event.type===type),type);assert(complete.events.length>0);assert(complete.samples.length>0);assert.equal(complete.telemetryHealth,'HEALTHY')});

test('complete session export preserves two Runs, raw events, samples, and Model builds',()=>{let now=1_000,game=state();game.hardware.calculator=100;const telemetry=new TelemetryService({clock:()=>now,storage:null});telemetry.start(game);const observe=(next,source)=>{now+=1_000;telemetry.observe(game,next,source);game=next};observe(trainModel(game),'training');observe(tickGame({...game,model:{...game.model,trainingProgress:trainingRequiredForState(game)-0.001}},1000),'game-loop');observe(improveModel(game,'tinyChat','quality'),'model');observe(buyHardware({...game,resources:{...game.resources,credits:1e9}},'calculator'),'hardware');game={...game,run:{...game.run,computeProduced:1e14,creditsEarned:1e10},hardware:{...game.hardware,miniDatacenter:1},model:{...game.model,level:9,progress:{...game.model.progress,tinyChat:{...game.model.progress.tinyChat,level:9}}}};observe(startDevelopmentCycle(game),'development-cycle');game={...game,meta:{...game.meta,intelligence:Math.max(10,game.meta.intelligence)}};observe(buyTechNode(game,'system-model-engineering'),'tech');game={...game,hardware:{...game.hardware,calculator:100}};observe(trainModel(game),'training');observe(tickGame({...game,model:{...game.model,trainingProgress:trainingRequiredForState(game)-0.001}},1000),'game-loop');observe(improveModel(game,'tinyChat','popularity'),'model');const report=telemetry.getReport(),complete=createCompleteSessionExport(report);assert.equal(complete.identity.sessionId,telemetry.sessionId);assert(complete.runs.length>=2);assert(complete.events.filter(event=>event.type==='model-training-completed').length>=2);assert(complete.events.filter(event=>event.type==='model-improvement-purchased').length>=2);assert(complete.events.some(event=>event.type==='hardware-purchased'));assert(complete.events.some(event=>event.type==='development-cycle-performed'));assert(complete.events.some(event=>event.type==='intelligence-node-purchased'));assert(complete.samples.length>0);assert(complete.builds.tinyChat.modelPointsEarned>=2);assert(complete.navigation.pages);assert(complete.analysis.summary);assert(report.summary.economy.computeProduced>0);assert(report.summary.economy.creditsEarned>0);assert(report.summary.progression.hardwarePurchases>=1);assert(report.summary.models.improvementPointsEarned>=1);assert(report.summary.models.improvementPointsSpent>=1);assert.equal(complete.telemetryHealth,'HEALTHY')});

test('one Training action emits one canonical start event',()=>{let now=1_000,game=state();game.hardware.calculator=1;const telemetry=new TelemetryService({clock:()=>now,storage:null});telemetry.start(game);const next=trainModel(game);now+=1_000;telemetry.observe(game,next,'training');assert.equal(telemetry.events.filter(event=>event.type==='model-training-started').length,1)});

test('market bottleneck durations reconcile to analyzed active time',()=>{const game=state(),telemetry=new TelemetryService({clock:()=>1_000,storage:null});telemetry.start(game);const report={...telemetry.getReport(),samples:[{sessionSeconds:0,bottleneck:'DEMAND LIMITED',utilization:.5},{sessionSeconds:10,bottleneck:'CAPACITY LIMITED',utilization:.8},{sessionSeconds:30,bottleneck:'CAPACITY LIMITED',utilization:.9},{sessionSeconds:40,bottleneck:'DEMAND LIMITED',utilization:.6}]};const market=analyzeSession(report).market,total=Object.values(analyzeSession(report).market.bottleneckSeconds).reduce((sum,value)=>sum+value,0);assert.equal(total,market.validActiveAnalyzedSeconds);assert(Math.abs(market.demandLimitedPercent+market.capacityLimitedPercent+market.balancedPercent-1)<1e-9)});
