import test from 'node:test';
import assert from 'node:assert/strict';
import { createDefaultState, GEM_SHOP_ITEMS, OBJECTIVES } from '../src/data/defaultState.js';
import { marketMetrics, revenuePerUser, startDevelopmentCycle } from '../src/systems/GameSystem.js';
import { activateGemBoost, activeBoosts } from '../src/systems/RewardedBoostService.js';
import { earnGems, gemLedgerReconciles } from '../src/systems/GemSystem.js';
import { GEM_BOOSTS, GEM_CONVENIENCE } from '../src/data/metaCatalog.js';
import { TelemetryService } from '../src/dev/telemetry-service.js';
import { createCompleteSessionExport } from '../src/dev/report-exporter.js';

function serverRackState(){const state=createDefaultState();state.hardware.miniDatacenter=10;state.allocation={training:91,inference:9,research:0,data:0,agents:0};state.market={priceMultiplier:1,marketing:10,reputation:.85,adoption:100};state.resources.users=218_000;state.model.level=11;state.model.progress.tinyChat={...state.model.progress.tinyChat,level:11,skills:{quality:3,popularity:4,efficiency:3}};return state}
function cycleReady(state){state.objectives=Object.fromEntries(OBJECTIVES.slice(0,6).map(item=>[item.id,true]));state.run={...state.run,computeProduced:1e14,creditsEarned:1e10};state.hardware.miniDatacenter=10;state.model.level=11;return state}

test('Server Rack market remains finite and price-responsive without Capacity-created Demand',()=>{const state=serverRackState(),market=marketMetrics(state);assert(Number.isFinite(market.capacity)&&market.capacity>0);assert(market.demand>0);assert.equal(market.capacityDemand,0);const highPrice=structuredClone(state);highPrice.market.priceMultiplier=1.5;assert(marketMetrics(highPrice).demand<market.demand);assert(revenuePerUser(highPrice)>revenuePerUser(state))});
test('Popularity, Quality, and Marketing affect Demand while Inference allocation does not',()=>{const base=serverRackState(),baseMarket=marketMetrics(base);const popular=structuredClone(base);popular.model.progress.tinyChat.skills.popularity+=3;assert(marketMetrics(popular).demand>baseMarket.demand);const quality=structuredClone(base);quality.model.progress.tinyChat.skills.quality+=3;assert(revenuePerUser(quality)>revenuePerUser(base));assert(marketMetrics(quality).demand>baseMarket.demand);const marketed=structuredClone(base);marketed.market.marketing=16;assert(marketMetrics(marketed).demand>baseMarket.demand);const inference=structuredClone(base);inference.allocation={...inference.allocation,inference:30,training:70};assert.equal(marketMetrics(inference).potentialDemand,baseMarket.potentialDemand)});
test('Revenue is earned only from users actually served by Demand and Capacity',()=>{const state=serverRackState();state.resources.users=10_000_000;const market=marketMetrics(state);assert(market.servedUsers<=market.capacity);assert.equal(market.revenue,market.servedUsers*revenuePerUser(state));assert(market.revenue<state.resources.users*revenuePerUser(state))});

test('Gem boosts extend duration, never multiplier, coexist, persist, and use the ledger',()=>{const now=1_000_000;let state=earnGems(createDefaultState(),20,'developer');state=activateGemBoost(state,'revenue-boost',now);state=activateGemBoost(state,'revenue-boost',now+1_000);state=activateGemBoost(state,'compute-boost',now+1_000);const boosts=activeBoosts(state,now+1_000);assert.equal(boosts.length,2);assert.equal(boosts.find(item=>item.source==='gem:revenue-boost').value,1);assert.equal(boosts.find(item=>item.source==='gem:revenue-boost').remainingMs,1_799_000);assert.equal(structuredClone(state).world.modifiers.length,2);assert.equal(state.gemEconomy.spent,12);assert(gemLedgerReconciles(state));const poor=createDefaultState();assert.equal(activateGemBoost(poor,'training-boost',now),poor);const expired=activateGemBoost(state,'training-boost',now+10_000_000);assert(activeBoosts(expired,now+10_000_001).some(item=>item.source==='gem:training-boost'))});
test('every visible Gem Shop offer has safe copy',()=>{for(const item of [...GEM_BOOSTS,...GEM_CONVENIENCE,...GEM_SHOP_ITEMS]){assert.equal(typeof item.description,'string');assert(item.description.length>0);assert(!/undefined|null|NaN/.test(`${item.name} ${item.description}`))}});

test('one playthrough spans runtime sessions and Development Cycles until destructive reset',()=>{let now=1_000;const map=new Map(),storage={getItem:key=>map.get(key)??null,setItem:(key,value)=>map.set(key,value),removeItem:key=>map.delete(key)};const before=cycleReady(createDefaultState()),id=before.profile.playthroughId;const first=new TelemetryService({clock:()=>now,storage});first.start(before);now+=2_000;first.observe(before,before,'checkpoint');const second=new TelemetryService({clock:()=>now,storage});second.start(before);assert.equal(second.playthroughId,id);assert.notEqual(second.sessionId,first.sessionId);assert.equal(second.runtimeSessions.length,2);const after=startDevelopmentCycle(before);now+=2_000;second.observe(before,after,'development-cycle');assert.equal(after.profile.playthroughId,id);assert.equal(second.playthroughId,id);const complete=createCompleteSessionExport(second.prepareExport(after));assert.equal(complete.identity.playthroughId,id);assert.equal(complete.identity.runtimeSessions.length,2);assert(complete.runs.length>=2);assert.notEqual(createDefaultState().profile.playthroughId,id)});
