import test from 'node:test';
import assert from 'node:assert/strict';
import { createDefaultState, MODEL_CATALOG, SAVE_VERSION } from '../src/data/defaultState.js';
import { ITEM_CATALOG, ITEM_RARITIES, ITEM_SLOT_TYPES, ITEM_TAGS } from '../src/data/itemCatalog.js';
import { CONSUMABLES } from '../src/data/metaCatalog.js';
import { acquireItem, buyGemConvenience, earnGems, equipItem, grantConsumable, toggleItemFavorite, unequipItem, useConsumable } from '../src/systems/InventorySystem.js';
import { computePerSecond, marketMetrics, startBreakthrough, startDevelopmentCycle } from '../src/systems/GameSystem.js';
import { ensureMissions, missionPeriodIds, missionsWithProgress } from '../src/systems/MissionSystem.js';
import { RewardedBoostService } from '../src/systems/RewardedBoostService.js';
import { modelBuildSummary } from '../src/systems/ModifierSystem.js';
import { TelemetryService } from '../src/dev/telemetry-service.js';

function unlocked(){const state=createDefaultState();state.meta.totalIntelligence=200;state.meta.intelligence=200;state.meta.techNodes=['system-model-engineering','system-allocation','system-marketing','system-missions','system-research','system-items','system-patents','system-account','system-automation','system-enterprise','system-energy','system-agents'];state.hardware.calculator=10;return state}

test('Item catalog is authored, unique, and schema-valid',()=>{assert.equal(ITEM_CATALOG.length,30);assert.equal(new Set(ITEM_CATALOG.map(item=>item.id)).size,ITEM_CATALOG.length);for(const item of ITEM_CATALOG){assert(ITEM_RARITIES.includes(item.rarity));assert(ITEM_SLOT_TYPES.includes(item.slotType));assert(item.tags.length);assert(item.tags.every(tag=>ITEM_TAGS.includes(tag)));assert(Object.keys(item.effects).length)}});
test('Inventory acquires, favorites, equips, replaces, and unequips immutable instances',()=>{let state=unlocked();state=acquireItem(state,'sparse-transformer');state=acquireItem(state,'open-weights');const [first,second]=state.inventory.instances;state=toggleItemFavorite(state,first.instanceId);assert(state.inventory.instances[0].favorite);state=equipItem(state,first.instanceId,'tinyChat');assert.equal(state.inventory.equipped.tinyChat.architecture,first.instanceId);state=equipItem(state,second.instanceId,'tinyChat');assert.equal(state.inventory.equipped.tinyChat.architecture,second.instanceId);assert.equal(state.inventory.instances[0].equippedModelId,null);state=unequipItem(state,'tinyChat','architecture');assert.equal(state.inventory.instances[1].equippedModelId,null)});
test('incompatible and locked Item slots cannot be equipped',()=>{let state=unlocked();state=acquireItem(state,'scientific-corpus');const id=state.inventory.instances[0].instanceId;assert.equal(equipItem(state,id,'tinyChat'),state)});
test('equipped Items change actual model and economy outputs',()=>{let state=unlocked();state.hardware.calculator=20;const base=marketMetrics(state).demand;state=acquireItem(state,'open-weights');state=equipItem(state,state.inventory.instances[0].instanceId,'tinyChat');assert(modelBuildSummary(state,MODEL_CATALOG[0]).effects.adoption>0);assert(marketMetrics(state).demand>base)});
test('different equipped builds create distinct outcomes',()=>{const outcomes=[];for(const id of ['open-weights','scientific-corpus','enterprise-dataset','prototype-gpu']){let state=unlocked();state=acquireItem(state,id);const instance=state.inventory.instances[0];state={...state,premium:{...state.premium,purchases:['item-slot-3']},meta:{...state.meta,techNodes:['model-1']}};state=equipItem(state,instance.instanceId,'tinyChat');outcomes.push([computePerSecond(state),marketMetrics(state).demand,marketMetrics(state).revenue,modelBuildSummary(state,MODEL_CATALOG[0]).identity])}assert(new Set(outcomes.map(JSON.stringify)).size>=3)});
test('missions reset by robust periods and respect feature gates',()=>{const fresh=ensureMissions(createDefaultState(),new Date('2026-01-01T12:00:00Z'));assert(!missionsWithProgress(fresh).some(mission=>mission.metric==='research'));const later=ensureMissions(unlocked(),new Date('2026-01-01T12:00:00Z'));assert(missionsWithProgress(later).every(mission=>Number.isFinite(mission.target)&&mission.target>0));assert.notDeepEqual(missionPeriodIds(new Date('2026-01-01')),missionPeriodIds(new Date('2026-02-08')))});
test('Gems have gameplay accounting and a legitimate convenience sink',()=>{let state=earnGems(unlocked(),50,'test');assert.equal(state.gemEconomy.earned,50);state=buyGemConvenience(state,'item-slot-3');assert.equal(state.resources.gems,10);assert.equal(state.gemEconomy.spent,40)});
test('Consumables are held and explicitly used',()=>{let state=grantConsumable(unlocked(),'compute-core');state=useConsumable(state,'compute-core');assert.equal(state.consumables['compute-core'],0);assert.equal(state.resources.compute,CONSUMABLES.find(item=>item.id==='compute-core').value)});
test('Rewarded web mock never invokes automatically and enforces cooldown',()=>{const service=new RewardedBoostService();const initial=unlocked();assert.equal(initial.rewardedBoosts.completed,0);const once=service.activate(initial,'credits',1_000_000);assert.equal(once.rewardedBoosts.completed,1);assert.equal(service.activate(once,'credits',1_000_001),once)});
test('Items persist through both prestige layers and save schema is safe',()=>{let state=unlocked();state=acquireItem(state,'sparse-transformer');state.run.computeProduced=1e6;const cycle=startDevelopmentCycle(state);assert.equal(cycle.inventory.instances.length,1);state.meta.totalIntelligence=20_000;state.statistics.totalComputeProduced=1e30;const breakthrough=startBreakthrough(state);assert.equal(breakthrough.inventory.instances.length,1);assert.equal(breakthrough.marketplace.enabled,false);assert.equal(SAVE_VERSION,16)});
test('new systems emit local developer telemetry from real diffs',()=>{let now=1000;const telemetry=new TelemetryService({clock:()=>now,storage:null});let state=unlocked();telemetry.start(state);const after=acquireItem(state,'sparse-transformer');now+=10;telemetry.observe(state,after,'item-acquired');assert(telemetry.events.some(event=>event.type==='item-acquired'));assert(telemetry.sampler.samples.at(-1).inventorySize===1)});
