import test from 'node:test';
import assert from 'node:assert/strict';
import { createDefaultState } from '../src/data/defaultState.js';
import { computePerSecond, marketMetrics, potentialDemand, revenuePerUser, tickGame } from '../src/systems/GameSystem.js';
import { adoptionFactor, advanceUsers, inferenceCapacity, marketSnapshot, priceDemandFactor, reputationFactor, servedUsers, wordOfMouthFactor } from '../src/systems/MarketSystem.js';
import { simulateDuration } from '../src/systems/OfflineProgressSystem.js';
import { createGameplaySnapshot } from '../src/dev/telemetry-sampler.js';

const close=(a,b,tolerance=1e-9)=>assert(Math.abs(a-b)<=tolerance*Math.max(1,Math.abs(a),Math.abs(b)),`${a} != ${b}`);
function state(){const s=createDefaultState();s.hardware.miniDatacenter=8;s.market={priceMultiplier:1,marketing:12,reputation:.9,adoption:70,demand:0};s.resources.users=40_000;s.model.level=11;s.model.progress.tinyChat={...s.model.progress.tinyChat,level:11,skills:{quality:3,popularity:4,efficiency:3}};return s}

test('Market V3 Potential Demand is independent of Inference allocation and Capacity',()=>{const low=state(),high=structuredClone(low);low.allocation={training:90,inference:10,research:0,data:0,agents:0};high.allocation={training:10,inference:90,research:0,data:0,agents:0};close(potentialDemand(low),potentialDemand(high));close(marketMetrics(low).potentialDemand,marketMetrics(high).potentialDemand);assert(marketMetrics(high).inferenceCapacity>marketMetrics(low).inferenceCapacity)});
test('V2 explosion regression: tenfold Capacity cannot manufacture Potential Demand',()=>{const s=state(),fundamentals=marketMetrics(s).factors,demand=marketMetrics(s).potentialDemand,one=inferenceCapacity(s,1e6,5,1),ten=inferenceCapacity(s,1e7,5,1);assert(ten.inferenceCapacity>one.inferenceCapacity*9.9);const a=marketSnapshot(s,{factors:fundamentals,totalComputePerSecond:1e6,modelEfficiency:5,inferenceModifiers:1,revenuePerUser:1}),b=marketSnapshot(s,{factors:fundamentals,totalComputePerSecond:1e7,modelEfficiency:5,inferenceModifiers:1,revenuePerUser:1});close(a.potentialDemand,demand);close(b.potentialDemand,demand)});
test('Served Users and Revenue obey canonical bounds and identities',()=>{const s=state(),m=marketMetrics(s);assert(m.servedUsers<=m.currentUsers);assert(m.servedUsers<=m.potentialDemand);assert(m.servedUsers<=m.inferenceCapacity);close(m.revenuePerSecond,m.servedUsers*m.revenuePerUser);assert.equal(servedUsers(100,200,50),50);assert.equal(servedUsers(100,40,500),40)});
test('tick credits equal the post-user-flow canonical Revenue rate',()=>{const s=state(),seconds=2,before=marketMetrics(s),users=advanceUsers(s.resources.users,before.potentialDemand,seconds,before.factors.popularity,before.factors.marketing),post=marketMetrics(s,users),next=tickGame(s,seconds*1000);close(next.resources.users,users);close(next.resources.credits-s.resources.credits,post.revenuePerSecond*seconds)});
test('exact fixed-fundamental user convergence is timestep invariant',()=>{const s=state(),m=marketMetrics(s),step=(users,seconds)=>advanceUsers(users,m.potentialDemand,seconds,m.factors.popularity,m.factors.marketing);let sixty=s.resources.users;for(let i=0;i<60;i++)sixty=step(sixty,1);close(sixty,step(s.resources.users,60));let sixHundred=s.resources.users;for(let i=0;i<600;i++)sixHundred=step(sixHundred,1);close(sixHundred,step(s.resources.users,600))});
test('bounded factors, continuous price, and finite representative snapshots',()=>{for(const users of [0,1,1e3,1e9,Number.MAX_VALUE]){const value=wordOfMouthFactor(users);assert(value>=1&&value<2.5)}for(const r of [-1e6,0,1,10,1e6]){const value=reputationFactor(r);assert(value>=.75&&value<=1.25)}for(const a of [0,1,50,1e9]){const value=adoptionFactor(a);assert(value>=1&&value<1.5)}close(priceDemandFactor(1-1e-9,5),1,1e-8);close(priceDemandFactor(1+1e-9,5),1,1e-8);const m=marketMetrics(state());for(const key of ['potentialDemand','currentUsers','servedUsers','inferenceComputePerSecond','inferenceCapacity','utilization','revenuePerUser','revenuePerSecond','acquisitionHalfLife','churnHalfLife','userGrowthPerSecond'])assert(Number.isFinite(m[key]),key);for(const key of ['potentialDemand','currentUsers','servedUsers','inferenceComputePerSecond','inferenceCapacity','utilization','revenuePerUser','revenuePerSecond'])assert(m[key]>=0,key)});
test('capacity- and demand-constrained snapshots monetize only the binding quantity',()=>{const s=state(),f=marketMetrics(s).factors,rpu=revenuePerUser(s);const capacity=marketSnapshot(s,{factors:f,totalComputePerSecond:100,modelEfficiency:1,inferenceModifiers:1,revenuePerUser:rpu},1e9);close(capacity.servedUsers,capacity.inferenceCapacity);const demand=marketSnapshot(s,{factors:f,totalComputePerSecond:1e15,modelEfficiency:1,inferenceModifiers:1,revenuePerUser:rpu},1e15);close(demand.servedUsers,demand.potentialDemand)});
test('offline chunk simulation preserves the exact user-flow trajectory',()=>{const s=state(),single=tickGame(s,60_000),chunked=simulateDuration(s,60_000);close(chunked.resources.users,single.resources.users,.02);assert(Number.isFinite(chunked.resources.credits));assert(computePerSecond(chunked)>0)});
test('periodic telemetry contains reconstructable Market V3 diagnostics',()=>{const sample=createGameplaySnapshot(state(),10,{timestamp:10_000});for(const key of ['potentialDemand','currentUsers','servedUsers','inferenceComputePerSecond','capacity','utilization','revenuePerUser','revenuePerSecond','usersPerSecond','marketing','reputation','adoption','currentModel','modelLevel','currentHardwareTier'])assert.notEqual(sample[key],undefined,key);assert.equal(sample.capacityDemand,0);assert.equal(typeof sample.marketFactors,'object')});
