import test from 'node:test';
import assert from 'node:assert/strict';
import { BALANCE } from '../src/config/balance.js';
import { createDefaultState } from '../src/data/defaultState.js';
import { tickGame, trainModel } from '../src/systems/GameSystem.js';
import { reconcileOffline, simulateDuration } from '../src/systems/OfflineProgressSystem.js';
import { activeReward, dismissReward, enqueueReward } from '../src/systems/RewardQueue.js';
import { ensureMissions, missionPeriodIds } from '../src/systems/MissionSystem.js';
import { TelemetryService } from '../src/dev/telemetry-service.js';
import { BALANCE_STRATEGIES, intelligenceMilestoneTable, runBalanceLab } from '../src/dev/balance-lab.js';

function productive(){const state=createDefaultState();state.hardware.calculator=10;state.tutorial={step:10,completed:true};return state}
function close(a,b,key,tolerance=.001){const x=a[key],y=b[key],scale=Math.max(1,Math.abs(x),Math.abs(y));assert(Math.abs(x-y)/scale<=tolerance,`${key}: ${x} vs ${y}`)}
test('offline duration clamps negative time, caps eight hours, and cannot reconcile twice',()=>{let state=productive();state.offline.lastActiveTimestamp=10_000;assert.equal(reconcileOffline(state,5_000).offline.durationMs,0);state.offline.lastActiveTimestamp=1_000;const once=reconcileOffline(state,1_000+10*60*60*1000);assert.equal(once.offline.effectiveDurationMs,BALANCE.offline.capMs);const twice=reconcileOffline(once,1_000+10*60*60*1000);assert.equal(twice.resources.credits,once.resources.credits)});
test('offline advances Credits, Compute, Users and active Training',()=>{let state=productive();state=trainModel(state);const next=reconcileOffline({...state,offline:{...state.offline,lastActiveTimestamp:1_000}},61_000);assert(next.resources.credits>state.resources.credits);assert(next.statistics.totalComputeProduced>state.statistics.totalComputeProduced);assert(next.resources.users>=state.resources.users);assert(next.model.xp>state.model.xp||next.model.level>state.model.level||next.model.trainingProgress>state.model.trainingProgress)});
test('locked Research and Patents do not progress offline',()=>{const state=productive(),next=reconcileOffline({...state,allocation:{training:20,inference:20,research:60,data:0,agents:0},offline:{...state.offline,lastActiveTimestamp:1_000}},301_000);assert.equal(next.resources.research,0);assert.equal(next.patents.progress,0)});
test('offline respects Energy limitation and expires temporary boosts',()=>{let state=productive();state.meta.totalIntelligence=55;state.hardware.gpuServer=50;state.world.modifiers=[{effect:'hardwareOutput',value:1,expiresAt:10_000}];state.statistics.playTimeMs=9_000;const limited=simulateDuration(state,60_000);assert(limited.statistics.totalComputeProduced<60_000*50*72);assert.equal(limited.world.modifiers.length,0)});
for(const seconds of [60,300,1800])test(`${seconds}s offline matches online deterministic simulation`,()=>{const state=productive();let online=state;for(let i=0;i<seconds;i++)online=tickGame(online,1000);const offline=simulateDuration(state,seconds*1000);for(const key of ['credits','compute','users','research'])close(online.resources,offline.resources,key);assert.equal(online.model.level,offline.model.level);close(online.patents,offline.patents,'progress')});
test('offline creates one aggregated Welcome Back reward with milestones',()=>{let state=productive();state=trainModel(state);state=reconcileOffline({...state,offline:{...state.offline,lastActiveTimestamp:1_000}},601_000);const reward=activeReward(state);assert.equal(reward.category,'offline');assert(reward.lines.length>0);assert.equal(state.offline.rewardPending,true);state=dismissReward(state,reward.id);assert.equal(state.rewards.queue.length,0);assert.equal(state.offline.rewardPending,false)});
test('reward queue orders major rewards and aggregates low rewards',()=>{let state=createDefaultState();state=enqueueReward(state,{priority:'low',category:'mission',title:'Mission',lines:[{key:'gems',value:1}]});state=enqueueReward(state,{priority:'low',category:'mission',title:'Mission',lines:[{key:'credits',value:10}]});state=enqueueReward(state,{priority:'critical',category:'feature',title:'Research unlocked'});assert.equal(state.rewards.queue.length,2);assert.equal(activeReward(state).priority,'critical')});
test('mission seeds persist across reload, rotate by period, and scale from baselines',()=>{const state=productive();state.profile.localOwnerId='stable-player';const day=ensureMissions(state,new Date('2026-01-01T00:00:00Z')),reload=ensureMissions(structuredClone(day),new Date('2026-01-01T12:00:00Z')),tomorrow=ensureMissions(day,new Date('2026-01-02T00:00:00Z'));assert.deepEqual(day.missions.daily,reload.missions.daily);assert.notDeepEqual(day.missions.daily.map(m=>m.id),tomorrow.missions.daily.map(m=>m.id));assert(day.missions.daily.every(m=>Number.isFinite(m.target)&&m.target>0&&Number.isFinite(m.baseline)));assert.notDeepEqual(missionPeriodIds(new Date('2026-01-01')),missionPeriodIds(new Date('2026-02-01')))});
test('all Balance Lab strategies complete one hour with finite nonnegative state',()=>{for(const strategy of BALANCE_STRATEGIES){const result=runBalanceLab({strategy,durationSeconds:3600});assert(Number.isFinite(result.state.resources.credits)&&result.state.resources.credits>=0);assert(Number.isFinite(result.state.statistics.totalComputeProduced));assert(result.summary.flags.every(flag=>typeof flag==='string'))}});
test('Balance Lab runs 24h, 7d and 30d quickly with actual INT formula table',()=>{for(const durationSeconds of [86400,604800,2592000]){const result=runBalanceLab({strategy:'Balanced',durationSeconds});assert.equal(result.config.durationSeconds,durationSeconds);assert(Number.isFinite(result.summary.intPerHour))}const table=intelligenceMilestoneTable(10);assert.equal(table.length,10);assert(table.every((row,index)=>!index||row.requiredRunCompute>table[index-1].requiredRunCompute))});
test('representative Build policies specialize different canonical outputs',()=>{const base=createDefaultState();Object.assign(base.meta,{intelligence:100,totalIntelligence:100,techNodes:['system-model-engineering','system-allocation','system-marketing','system-research','system-patents','system-automation','system-enterprise','system-agents']});base.hardware.laptop=10;base.resources.credits=1e7;base.model.upgradePoints=20;Object.assign(base.model.progress.tinyChat,{upgradePoints:20,totalPointsEarned:20,totalPointsSpent:0});base.tutorial={step:10,completed:true};const results=Object.fromEntries(['Compute','Consumer','Enterprise','Research','Efficiency','Agent','Balanced'].map(strategy=>[strategy,runBalanceLab({strategy,durationSeconds:600,initialState:base}).summary]));assert.equal(results.Compute.build,'Compute');assert.equal(results.Enterprise.build,'Enterprise');assert.equal(results.Research.build,'Research');assert.equal(results.Agent.build,'Agent');assert(results.Enterprise.revenuePerUser>results.Balanced.revenuePerUser);assert(results.Research.researchPerHour>results.Balanced.researchPerHour);assert(results.Efficiency.capacity>results.Compute.capacity);assert(new Set(Object.values(results).map(result=>`${result.demand}:${result.capacity}:${result.revenuePerUser}:${result.researchPerHour}`)).size>=5)});

test('clean balance run identity reaches events, samples, and reports without marking cheats',()=>{let now=1000,state=productive();state.balanceRun={id:'balance-test',startedAt:now,natural:true};const telemetry=new TelemetryService({clock:()=>now,storage:null});telemetry.start(state);now+=1000;const next=tickGame(state,1000);telemetry.observe(state,next,'game-loop');const report=telemetry.getReport();assert.equal(report.balanceRunId,'balance-test');assert.equal(report.events[0].balanceRunId,'balance-test');assert.equal(report.samples[0].balanceRunId,'balance-test');assert.equal(report.summary.session.natural,true)});
