import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { BALANCE } from '../src/config/balance.js';
import { createDefaultState, HARDWARE_CATALOG, OBJECTIVES, SAVE_VERSION } from '../src/data/defaultState.js';
import { canDevelop, cycleIntelligence, developmentCycleRequirements, trainingFinishGemCost } from '../src/systems/GameSystem.js';
import { earnGems, gemLedgerReconciles, spendGems } from '../src/systems/GemSystem.js';
import { claimMission, ensureMissions, missionsWithProgress } from '../src/systems/MissionSystem.js';

test('realistic eighteen-minute human state is not prematurely eligible for Prestige',()=>{const state=createDefaultState();state.model.level=7;state.model.progress.tinyChat.level=7;state.hardware.workstation=1;state.run.computeProduced=18_000_000;state.run.creditsEarned=5_000_000;state.objectives=Object.fromEntries(OBJECTIVES.slice(0,4).map(item=>[item.id,true]));const requirements=developmentCycleRequirements(state);assert.equal(requirements.ready,false);assert.equal(canDevelop(state),false);assert.equal(cycleIntelligence(state),0)});

test('first complete Prestige bundle awards one scarce INT and remains sublinear',()=>{const state=createDefaultState();state.model.level=BALANCE.intelligence.minimumModelLevel;state.model.progress.tinyChat.level=BALANCE.intelligence.minimumModelLevel;state.hardware[HARDWARE_CATALOG[BALANCE.intelligence.minimumHardwareTier].id]=1;state.run.computeProduced=BALANCE.intelligence.computeScale;state.run.creditsEarned=BALANCE.intelligence.creditScale;state.objectives=Object.fromEntries(OBJECTIVES.slice(0,BALANCE.intelligence.minimumObjectives).map(item=>[item.id,true]));assert(developmentCycleRequirements(state).ready);assert.equal(cycleIntelligence(state),1);state.run.computeProduced*=1_000_000;state.run.creditsEarned*=1_000_000;assert(cycleIntelligence(state)<15)});

test('canonical Gem ledger accepts authored sources and sinks without negative balances',()=>{let state=createDefaultState();state=earnGems(state,12,'daily-mission',{missionId:'daily-test'});assert(gemLedgerReconciles(state));const rejected=spendGems(state,99,'training-finish');assert.equal(rejected,state);state=spendGems(state,5,'training-finish',{modelId:'tinyChat'});assert.equal(state.resources.gems,7);assert(gemLedgerReconciles(state));assert.deepEqual(state.gemEconomy.history.map(entry=>entry.source),['daily-mission','training-finish'])});

test('mission groups always preview scaled Credits and controlled Gems',()=>{const generated=ensureMissions(createDefaultState(),new Date('2026-08-29T12:00:00Z'));for(const period of ['daily','weekly','monthly']){const missions=missionsWithProgress(generated,period);assert(missions.length>=2);assert(missions.every(mission=>mission.reward.credits>=BALANCE.missions.creditRewardFloor[period]));assert(missions.every(mission=>mission.reward.gems>=BALANCE.missions.gems[period]));assert(missions.every(mission=>mission.category!=='Energy'))}});

test('claiming a Daily mission records its Gem source and cannot double claim',()=>{let state=createDefaultState();state.statistics.totalCreditsEarned=100;state.missions={...state.missions,dailyPeriodId:'2026-08-29',daily:[{id:'daily-ledger',period:'daily',category:'Economy',text:'Earn Credits',target:10,metric:'creditsEarned',baseline:90,reward:{credits:300,gems:2}}]};state=claimMission(state,'daily-ledger');assert.equal(state.resources.gems,2);assert(state.gemEconomy.history.some(entry=>entry.source==='daily-mission'));assert.equal(claimMission(state,'daily-ledger'),state)});

test('Gem finish curve grows meaningfully across longer projects',()=>{const costs=[1,3,5,10,20].map(level=>{const state=createDefaultState();state.model.trainingActive=true;state.hardware.calculator=1;state.model.progress.tinyChat.level=level;state.model.level=level;state.model.trainingSession={};return trainingFinishGemCost(state)});assert(costs.every((cost,index)=>!index||cost>=costs[index-1]));assert(costs.at(-1)>costs[0])});

test('Milestone 19 visuals are vector, reduced-motion safe, and Energy-free in active analytics',()=>{const icons=readFileSync(new URL('../src/ui/icons.js',import.meta.url),'utf8'),css=readFileSync(new URL('../src/styles/main.css',import.meta.url),'utf8'),dashboard=readFileSync(new URL('../src/dev/developer-dashboard.js',import.meta.url),'utf8');assert.match(icons,/gem:'M/);assert.match(css,/prefers-reduced-motion:reduce/);assert.match(css,/min-height:44px/);assert.doesNotMatch(dashboard,/energyProduction|energyDemand|energyEfficiency|\['ENERGY'/);assert.equal(SAVE_VERSION,20)});
