import test from 'node:test';
import assert from 'node:assert/strict';
import { createDefaultState, HARDWARE_CATALOG, MODEL_CATALOG, OBJECTIVES } from '../src/data/defaultState.js';
import { BALANCE, isResearchUnlocked } from '../src/config/balance.js';
import { activateGemBoost, activeBoosts } from '../src/systems/RewardedBoostService.js';
import { canDevelop, developmentCycleRequirements, economySnapshot, buyHardware, buyMarketing, trainModel, tickGame, upgradeModelSkill } from '../src/systems/GameSystem.js';
import { earnGems } from '../src/systems/GemSystem.js';
import { ensureMissions, missionCreditReward, missionPeriodIds } from '../src/systems/MissionSystem.js';
import { TelemetryService } from '../src/dev/telemetry-service.js';
import { createCompleteSessionExport } from '../src/dev/report-exporter.js';
import { hasUniqueIcon } from '../src/ui/icons.js';

function rich(){const state=createDefaultState();state.resources.credits=1e9;state.hardware.calculator=10;return state}
test('real-session telemetry exports navigation, hardware, training, model, marketing, gems, and boosts',()=>{let now=1_000,state=rich();const telemetry=new TelemetryService({clock:()=>now,storage:null});telemetry.start(state);const act=(next,source)=>{now+=1_000;telemetry.observe(state,next,source);state=next};act({...state,ui:{...state.ui,activeView:'hardware'}},'navigation');act(buyHardware(state,'calculator'),'hardware');act(trainModel(state),'training');act(tickGame({...state,model:{...state.model,trainingProgress:1e99}},1_000),'game-loop');act(upgradeModelSkill(state,'tinyChat','quality'),'model-skill');act(buyMarketing(state),'market');act(earnGems(state,10,'developer'),'mission');act(activateGemBoost(state,'compute-boost'),'gem-boost');const complete=createCompleteSessionExport(telemetry.prepareExport(state));for(const type of ['navigation-view-opened','hardware-purchased','model-training-started','model-training-completed','model-skill-upgraded','marketing-purchased','gems-earned','gems-spent','boost-activated'])assert(complete.events.some(event=>event.type===type),type);assert.notEqual(complete.telemetryHealth,'BROKEN')});
test('first Development Cycle uses supplied human-run progression and still rejects an early rush',()=>{let human=rich();human.hardware.gpuServer=1;human.model.level=12;human.model.progress.tinyChat.level=12;human.run={...human.run,creditsEarned:61_000_000,computeProduced:400_000_000};human.objectives=Object.fromEntries(OBJECTIVES.slice(0,6).map(item=>[item.id,true]));assert(developmentCycleRequirements(human).ready);assert(canDevelop(human));const early={...human,run:{...human.run,creditsEarned:5_000_000,computeProduced:24_000_000}};assert(!canDevelop(early));assert.equal(BALANCE.intelligence.creditScale,60_000_000);assert.equal(BALANCE.intelligence.computeScale,400_000_000)});
test('Gem boosts spend through the ledger, last 15 minutes, stack by extending duration, and affect canonical economy',()=>{let state=rich();state=earnGems(state,20,'developer');const before=economySnapshot(state),first=activateGemBoost(state,'compute-boost'),after=economySnapshot(first);assert.equal(first.gemEconomy.spent,4);assert.equal(first.resources.gems,16);assert(after.computePerSecond>before.computePerSecond);assert(Math.abs(activeBoosts(first)[0].remainingMs-900_000)<10);const second=activateGemBoost(first,'compute-boost');assert(Math.abs(activeBoosts(second)[0].remainingMs-1_800_000)<10)});
test('mission periods use unique UTC calendar days and rewards stay supplemental under spikes',()=>{const state=ensureMissions(rich(),new Date('2026-08-31T10:00:00Z'));assert.notEqual(missionPeriodIds(new Date('2026-08-31')).dailyPeriodId,missionPeriodIds(new Date('2026-09-01')).dailyPeriodId);for(const period of ['daily','weekly','monthly'])assert(state.missions[period].length>0);const boosted={...state,world:{...state.world,modifiers:[{effect:'revenue',value:100,expiresAt:1e9}]}};assert.equal(missionCreditReward(boosted,'daily'),missionCreditReward(state,'daily'))});
test('Research unlocks after the first Cycle and all Hardware and Models have unique icons',()=>{const state=createDefaultState();assert(!isResearchUnlocked(state));state.hardware.gpuServer=1;assert(!isResearchUnlocked(state));state.meta.cycles=1;assert.equal(isResearchUnlocked(state),false);state.meta.techNodes=['research-1'];assert(isResearchUnlocked(state));for(const item of HARDWARE_CATALOG)assert(hasUniqueIcon(item.id),item.id);for(const model of MODEL_CATALOG)assert(hasUniqueIcon(model.id),model.id)});
