import test from 'node:test';
import assert from 'node:assert/strict';
import { createDefaultState, OBJECTIVES, objectiveTitle } from '../src/data/defaultState.js';
import { objectiveProgress, startDevelopmentCycle } from '../src/systems/GameSystem.js';
import { claimAllMissions, claimMission, claimMissionTrack, ensureMissions, MISSION_CATALOG, missionDiagnostics, missionsWithProgress, missionTitle } from '../src/systems/MissionSystem.js';
import { tickResearchLabs } from '../src/systems/ResearchSystem.js';

function completable(period='daily'){
  const state=createDefaultState(),periodId='2026-09-02';
  state.missions={...state.missions,[`${period}PeriodId`]:periodId,[period]:[1,2].map(index=>({id:`${period}-${index}`,type:'manual-taps',period,periodId,category:'ACTIVE PLAY',target:index,titleTemplate:'Perform {target} manual taps',difficulty:'STANDARD',progressSource:'totalClicks',baseline:0,reward:{gems:1,credits:10}})),tracks:{weekly:{periodId:'2026-W36',points:0,claimed:{}},monthly:{periodId:'2026-09',points:0,claimed:{}}}};
  state.statistics.totalClicks=2;
  return state;
}
function cycleReady(state){state.resources.credits=1e20;state.run.creditsEarned=1e20;state.run.computeProduced=1e20;state.model.level=30;state.model.progress.tinyChat.level=30;state.hardware.enterpriseDatacenter=1;state.objectives=Object.fromEntries(OBJECTIVES.slice(0,8).map(o=>[o.id,true]));return state}

test('canonical permanent Training goal uses one target for title, counter, and completion',()=>{const goal=OBJECTIVES.find(item=>item.id==='training-6'),state=createDefaultState();assert.equal(goal.target,6);assert.equal(goal.text,'Complete 6 Trainings');assert.equal(goal.text,objectiveTitle(goal.titleTemplate,goal.target));state.statistics.totalTrainings=1;assert.equal(objectiveProgress(state,goal),1);state.statistics.totalTrainings=5;assert.equal(objectiveProgress(state,goal),5);state.statistics.totalTrainings=6;assert.equal(objectiveProgress(state,goal),6);assert.equal(missionTitle('Complete {target} Trainings',40),'Complete 40 Trainings')});

test('period generation is persistent, rotates independently, diverse, and unlock-aware',()=>{const fresh=createDefaultState(),today=ensureMissions(fresh,new Date('2026-09-02T12:00:00Z')),reload=ensureMissions(structuredClone(today),new Date('2026-09-02T18:00:00Z'));assert.deepEqual(today.missions,reload.missions);assert.equal(today.missions.daily.length,5);assert.equal(today.missions.weekly.length,7);assert.equal(today.missions.monthly.length,10);for(const period of ['daily','weekly','monthly'])assert.equal(new Set(today.missions[period].map(m=>m.category)).size,today.missions[period].length);const tomorrow=ensureMissions(today,new Date('2026-09-03T12:00:00Z'));assert.notDeepEqual(today.missions.daily.map(m=>m.id),tomorrow.missions.daily.map(m=>m.id));assert.deepEqual(today.missions.weekly.map(m=>m.id),tomorrow.missions.weekly.map(m=>m.id));assert(!missionsWithProgress(today).some(m=>['research-projects','technology-purchases','patent-discoveries','parallel-labs','development-cycles'].includes(m.type)));const diagnostics=missionDiagnostics(today);assert(diagnostics.excluded.daily.some(m=>m.type==='research-projects'&&m.reason==='Research locked'))});

test('Development Cycle preserves Mission periods and tracks while resetting run Goals',()=>{let state=cycleReady(ensureMissions(createDefaultState(),new Date('2026-09-02T12:00:00Z')));state.objectives['training-6']=true;state.missions.claims[state.missions.daily[0].id]=123;state.missions.tracks.weekly.points=9;const before=structuredClone(state.missions),next=startDevelopmentCycle(state);assert.deepEqual(next.missions,before);assert.equal(next.objectives['training-6'],undefined)});

test('Claim All claims only completed Missions and advances weekly and monthly tracks',()=>{let state=completable();state=claimAllMissions(state,'daily');assert.equal(Object.keys(state.missions.claims).length,2);assert.equal(state.missions.tracks.weekly.points,2);assert.equal(state.missions.tracks.monthly.points,2);assert.equal(claimAllMissions(state,'daily'),state);state.missions.tracks.weekly.points=4;const gems=state.resources.gems;state=claimMissionTrack(state,'weekly',4);assert(state.resources.gems>gems);assert(state.missions.tracks.weekly.claimed[4])});

test('distinct calendar days and Lab-hours use canonical period and parallel-Lab accounting',()=>{let state=ensureMissions(createDefaultState(),new Date('2026-09-01T12:00:00Z'));state=ensureMissions(state,new Date('2026-09-01T18:00:00Z'));state=ensureMissions(state,new Date('2026-09-02T12:00:00Z'));assert.deepEqual(state.retention.loginDays,['2026-09-01','2026-09-02']);state.researchLabs.labs[0]={...state.researchLabs.labs[0],projectId:'research-algorithms',remainingSeconds:100,totalSeconds:100};state.researchLabs.labs[1]={...state.researchLabs.labs[1],projectId:'research-silicon',remainingSeconds:100,totalSeconds:100};state=tickResearchLabs(state,3_600_000);assert.equal(state.statistics.researchLabSeconds,7200);const entry={period:'weekly',periodId:state.missions.weeklyPeriodId,progressSource:'researchLabSeconds',target:2,titleTemplate:'Accumulate {target} Lab-Hours',baseline:0,reward:{}};state.missions.weekly=[entry];assert.equal(missionsWithProgress(state,'weekly')[0].progress,2)});

test('catalog is substantial, data-driven, tier-capable, and contains no paywall requirements',()=>{for(const period of ['daily','weekly','monthly'])assert(MISSION_CATALOG.filter(entry=>entry.eligiblePeriods.includes(period)).length>=15);assert(MISSION_CATALOG.some(entry=>entry.tiers?.length>=3));for(const entry of MISSION_CATALOG)assert(!/ad|gem|lab-[345]/iu.test(entry.progressSource));let state=completable('weekly');state.missions.weekly[0].difficulty='HARD';state=claimMission(state,'weekly-1');assert.equal(state.missions.tracks.weekly.points,2)});
