import test from 'node:test';
import assert from 'node:assert/strict';
import { BALANCE } from '../src/config/balance.js';
import { createDefaultState, TECH_NODES } from '../src/data/defaultState.js';
import { optimizeGain, startDevelopmentCycle, tickGame, trainingRequiredForState } from '../src/systems/GameSystem.js';
import { doubleOfflineRewardWithGems, offlineCapacityMs, offlineEfficiency, reconcileOffline } from '../src/systems/OfflineProgressSystem.js';
import { earnGems } from '../src/systems/GemSystem.js';
import { canQueueResearch, claimDailyFreeGems, purchaseResearchLab, RESEARCH_PROJECTS, researchSpeed, startResearchProject, tickResearchLabs, unlockedResearchLabs } from '../src/systems/ResearchSystem.js';

function cycleReady(state){return{...state,hardware:{...state.hardware,gpuServer:1},model:{...state.model,level:9,progress:{...state.model.progress,tinyChat:{...state.model.progress.tinyChat,level:9}}},run:{...state.run,creditsEarned:60_000_000,computeProduced:400_000_000},objectives:Object.fromEntries(Array.from({length:6},(_,index)=>[`goal-${index}`,true]))}}
function researchState(){const state=createDefaultState();return{...state,meta:{...state.meta,cycles:1,techNodes:['research-1']},resources:{...state.resources,research:1e9},researchLabs:{...state.researchLabs,unlocked:1}}}

test('Development Cycle preserves Goals, Missions, Research Points, and Research Labs',()=>{const state=cycleReady(researchState()),withProgress={...state,objectives:{...state.objectives,permanent:true},missions:{...state.missions,dailyPeriodId:'day',claims:{daily:true}},researchLabs:{...state.researchLabs,completedProjects:['research-algorithms:1']}};const next=startDevelopmentCycle(withProgress);assert.equal(next.objectives.permanent,true);assert.equal(next.missions.dailyPeriodId,'day');assert.equal(next.missions.claims.daily,true);assert.equal(next.resources.research,withProgress.resources.research);assert.deepEqual(next.researchLabs.completedProjects,withProgress.researchLabs.completedProjects)});
test('offline rewards cap at two hours and apply separate sixty percent efficiency',()=>{let state=createDefaultState();state={...state,hardware:{...state.hardware,calculator:1},offline:{...state.offline,lastActiveTimestamp:1}};const next=reconcileOffline(state,1+7*60*60*1000);assert.equal(offlineCapacityMs(state),2*60*60*1000);assert.equal(offlineEfficiency(state),.6);assert.equal(next.offline.effectiveDurationMs,2*60*60*1000);assert.equal(next.offline.rewardedDurationMs,2*60*60*1000*.6)});
test('Gem double duplicates only the capped offline resource reward',()=>{let state=earnGems(createDefaultState(),20,'developer');state={...state,offline:{...state.offline,rewardPending:true,results:{gains:{credits:50,compute:25,users:4,research:3}}}};const next=doubleOfflineRewardWithGems(state);assert.equal(next.resources.credits,state.resources.credits+50);assert.equal(next.resources.compute,25);assert.equal(next.resources.gems,state.resources.gems-BALANCE.offline.doubleGemCost);assert.equal(next.offline.doubled,true)});
test('free Shop Gems have a persistent 24-hour cooldown',()=>{const first=claimDailyFreeGems(createDefaultState(),1000),blocked=claimDailyFreeGems(first,1001),later=claimDailyFreeGems(first,1000+BALANCE.freeGems.cooldownMs);assert.equal(first.resources.gems,5);assert.strictEqual(blocked,first);assert.equal(later.resources.gems,10)});
test('Research requires time and Lab 2 is a deep Tech unlock',()=>{const state=researchState(),project=RESEARCH_PROJECTS[0],started=startResearchProject(state,project.id,1);assert.equal(started.researchUpgradeLevels[project.id]??0,0);const partial=tickResearchLabs(started,started.researchLabs.labs[0].totalSeconds*500);assert(partial.researchLabs.labs[0].projectId);const complete=tickResearchLabs(partial,partial.researchLabs.labs[0].remainingSeconds*1000+1);assert.equal(complete.researchUpgradeLevels[project.id],1);assert.equal(unlockedResearchLabs(state),1);assert.equal(unlockedResearchLabs({...state,meta:{...state.meta,techNodes:['research-1','research-4']}}),2)});
test('Labs 3–5 are Gem-only, parallel Labs work, and Queue remains gated',()=>{let state=earnGems(researchState(),2_000,'developer');state={...state,meta:{...state.meta,techNodes:['research-1','research-4']}};for(const lab of [3,4,5])state=purchaseResearchLab(state,lab);assert.equal(unlockedResearchLabs(state),5);let parallel=startResearchProject(state,RESEARCH_PROJECTS[0].id,1);parallel=startResearchProject(parallel,RESEARCH_PROJECTS[1].id,2);assert.equal(parallel.researchLabs.labs.filter(lab=>lab.projectId).length,2);assert.equal(canQueueResearch(parallel),false)});
test('manual Compute scales with Model, old Hardware, and permanent Compute Tech',()=>{const base=createDefaultState(),scaled={...base,hardware:{...base.hardware,calculator:50,homeComputer:20},model:{...base.model,level:10},meta:{...base.meta,techNodes:['compute-1']}};assert(optimizeGain(scaled)>optimizeGain(base))});
test('Training completion produces a compact presentation trigger',()=>{let state=createDefaultState();state={...state,hardware:{...state.hardware,calculator:1},model:{...state.model,trainingActive:true,trainingProgress:trainingRequiredForState(state),trainingSession:{startingLevel:1,activeElapsedMs:1,computeInvested:1}}};const next=tickGame(state,0);assert.match(next.ui.toast.message,/Training complete/)});
test('Technology graph exposes topology and an acyclic prerequisite path',()=>{const ids=new Set(TECH_NODES.map(node=>node.id));for(const node of TECH_NODES){assert(Array.isArray(node.parents));assert(Number.isFinite(node.depth));assert(node.parents.every(parent=>ids.has(parent)));for(const parent of node.parents)assert(TECH_NODES.find(item=>item.id===parent).depth<node.depth)}});
test('Research Speed is canonical and improves with Datacenters and Model levels',()=>{const base=researchState(),scaled={...base,hardware:{...base.hardware,hyperscaleDatacenter:10},model:{...base.model,level:20}};assert(researchSpeed(scaled)>researchSpeed(base))});
