import test from 'node:test';
import assert from 'node:assert/strict';
import { createDefaultState, MODEL_SKILLS } from '../src/data/defaultState.js';
import { economySnapshot, modelImprovementCost, modelSkillEconomyPreview, upgradeModelSkill } from '../src/systems/GameSystem.js';
import { TelemetryService } from '../src/dev/telemetry-service.js';

function modelState(modelId,skill,level){const state=createDefaultState(),base=state.model.progress.tinyChat;state.hardware.gpuServer=1000;state.resources.users=50_000;state.model.activeId=modelId;state.model.trainingTarget=modelId;state.model.owned=[...new Set(['tinyChat',modelId])];state.model.deployed=[modelId];state.model.progress[modelId]={...base,level:9,skills:{[skill]:level},upgradePoints:100,availablePoints:100,totalPointsEarned:100,totalPointsSpent:0};state.model.improvements[modelId]={[skill]:level};state.model.level=9;state.model.upgradePoints=100;return state}

for(const modelId of ['tinyChat','smartChat','gptClass'])for(const skill of MODEL_SKILLS)for(const level of [0,3,5,10])test(`${modelId} ${skill} ${level}→${level+1} preview equals canonical purchase`,()=>{const state=modelState(modelId,skill,level),preview=modelSkillEconomyPreview(state,modelId,skill),before=economySnapshot(state),next=upgradeModelSkill(state,modelId,skill),after=economySnapshot(next);assert.equal(next.model.progress[modelId].skills[skill],level+1);assert.equal(preview.before,before[preview.metric]);assert.equal(preview.after,after[preview.metric]);assert(preview.percentChange>0);if(skill==='quality'){assert(after.demand>before.demand);assert(after.revenuePerUser>before.revenuePerUser)}if(skill==='popularity')assert(after.demand>before.demand);if(skill==='efficiency'){assert(after.capacity>before.capacity);assert(after.trainingCompute>before.trainingCompute)}assert.equal(state.model.progress[modelId].skills[skill],level);assert(modelImprovementCost(state,modelId,skill)>=1)});

test('active Model contributes even when deployment list is stale',()=>{const state=modelState('smartChat','quality',5);state.model.deployed=['tinyChat'];const preview=modelSkillEconomyPreview(state,'smartChat','quality');assert(preview.after>preview.before)});

test('Model skill telemetry records complete economy impact without a false no-effect warning',()=>{let now=1_000;const telemetry=new TelemetryService({clock:()=>now,storage:{getItem(){return null},setItem(){},removeItem(){}}}),state=modelState('tinyChat','quality',5);telemetry.start(state);now+=1_000;const next=upgradeModelSkill(state,'tinyChat','quality');telemetry.observe(state,next,'model-skill');const event=telemetry.events.find(item=>item.type==='model-skill-upgraded');assert.equal(event.metadata.modelId,'tinyChat');assert.equal(event.metadata.skill,'quality');assert.equal(event.metadata.previousLevel,5);assert.equal(event.metadata.newLevel,6);assert.equal(event.metadata.pointCost,modelImprovementCost(state,'tinyChat','quality'));assert(event.metadata.economyImpact.demandAfter>event.metadata.economyImpact.demandBefore);assert(event.metadata.economyImpact.revenuePerUserAfter>event.metadata.economyImpact.revenuePerUserBefore);assert(!telemetry.events.some(item=>item.type==='model-upgrade-no-effect'))});
