import test from 'node:test';
import assert from 'node:assert/strict';
import { createDefaultState, HARDWARE_CATALOG, MODEL_SKILLS } from '../src/data/defaultState.js';
import { computePerSecond, economySnapshot, tickGame, trainingRatePerSecond, trainingRequiredForState } from '../src/systems/GameSystem.js';
import { simulateDuration } from '../src/systems/OfflineProgressSystem.js';
import { allocatedCompute, derivedHardwareGrowth, hardwareBulkBaseCost, hardwareUnitCost, modelTierScale, withinModelLevelFactor } from '../src/systems/ProgressionSystem.js';
import { simulatePolicy } from '../scripts/phase-2b-simulator.mjs';

const close=(a,b,tolerance=1e-10)=>assert.ok(Math.abs(a-b)<=Math.max(1,Math.abs(a),Math.abs(b))*tolerance,`${a} != ${b}`);
function state(){const s=createDefaultState();s.hardware.calculator=10;s.hardware.homeComputer=5;s.resources.credits=1e6;return s}

test('per-tier Hardware growth is derived and bulk cost equals its geometric sum',()=>{for(const item of HARDWARE_CATALOG){close(item.costGrowth,derivedHardwareGrowth(item.targetPurchaseCount,item.targetFinalCostRatio),1e-7);for(const n of [0,10,25]){const sum=Array.from({length:10},(_,i)=>item.baseCost*item.costGrowth**(n+i)).reduce((a,b)=>a+b,0);close(hardwareBulkBaseCost(item,n,10),sum);assert.ok(hardwareUnitCost(item,n+1)>hardwareUnitCost(item,n))}}});
test('canonical Compute and allocation conserve the generated flow',()=>{const s=state(),total=computePerSecond(s);close(total,economySnapshot(s).computePerSecond);close(allocatedCompute(total,40)+allocatedCompute(total,60),total)});
test('Training requirement is static while Hardware and Training Research reduce ETA',()=>{const base=state(),requirement=trainingRequiredForState(base),hardware=structuredClone(base);hardware.hardware.calculator+=10;assert.equal(trainingRequiredForState(hardware),requirement);assert(trainingRatePerSecond(hardware)>trainingRatePerSecond(base))});
test('Efficiency affects only Capacity and Compute/User',()=>{const low=state(),high=structuredClone(low);high.model.progress.tinyChat.skills.efficiency=16;const a=economySnapshot(low),b=economySnapshot(high);assert.equal(trainingRatePerSecond(high),trainingRatePerSecond(low));assert(b.capacity>a.capacity);const allocation=structuredClone(low);allocation.allocation.inference=1;assert.equal(economySnapshot(allocation).capacity,a.capacity)});
test('Quality affects Revenue/User and Popularity is not a skill',()=>{const base=state(),quality=structuredClone(base);quality.model.progress.tinyChat.skills.quality=8;const b=economySnapshot(base),q=economySnapshot(quality);assert(q.revenuePerUser>b.revenuePerUser);assert(!MODEL_SKILLS.includes('popularity'))});
test('Model level and tier curves remain finite, concave, and ordered through L500',()=>{let prior=0,priorDelta=Infinity;for(const level of [1,5,10,20,50,100,250,500]){const value=withinModelLevelFactor(level);assert.ok(Number.isFinite(value)&&value>prior);const delta=value-prior;if(prior)assert.ok(delta/(level)>0);prior=value;priorDelta=delta}assert.ok(priorDelta>0);for(let tier=1;tier<9;tier++)assert.ok(modelTierScale(tier)>modelTierScale(tier-1))});
test('offline canonical simulation is deterministic and finite',()=>{const s=state();const a=simulateDuration(s,300_000),b=simulateDuration(s,300_000);assert.deepEqual(a.resources,b.resources);for(const duration of [300_000,1_800_000,7_200_000]){const result=simulateDuration(s,duration);assert.ok(Object.values(result.resources).every(Number.isFinite))}});
test('canonical tick chunking keeps ten-minute Credit divergence below one percent',()=>{const s=state(),one=tickGame(s,600_000);let seconds=s;for(let i=0;i<600;i++)seconds=tickGame(seconds,1_000);const divergence=Math.abs(one.resources.credits-seconds.resources.credits)/seconds.resources.credits;assert.ok(divergence<.01,`Credit divergence ${divergence}`);const a=simulatePolicy('BALANCED',5),b=simulatePolicy('BALANCED',5);assert.deepEqual(a,b)});
