import test from 'node:test';
import assert from 'node:assert/strict';
import { BALANCE } from '../src/config/balance.js';
import { createDefaultState, HARDWARE_CATALOG } from '../src/data/defaultState.js';
import { computePerSecond, economySnapshot, potentialDemand, tickGame, trainingEtaSeconds, trainingRatePerSecond, trainingRequiredForState } from '../src/systems/GameSystem.js';
import { simulateDuration } from '../src/systems/OfflineProgressSystem.js';
import { allocatedCompute, derivedHardwareGrowth, hardwareBulkBaseCost, hardwareUnitCost, modelTierScale, trainingRequirement, withinModelLevelFactor } from '../src/systems/ProgressionSystem.js';
import { simulatePolicy } from '../scripts/phase-2b-simulator.mjs';

const close=(a,b,tolerance=1e-10)=>assert.ok(Math.abs(a-b)<=Math.max(1,Math.abs(a),Math.abs(b))*tolerance,`${a} != ${b}`);
function state(){const s=createDefaultState();s.hardware.calculator=10;s.hardware.homeComputer=5;s.resources.credits=1e6;return s}

test('per-tier Hardware growth is derived and bulk cost equals its geometric sum',()=>{for(const item of HARDWARE_CATALOG){close(item.costGrowth,derivedHardwareGrowth(item.targetPurchaseCount,item.targetFinalCostRatio),1e-7);for(const n of [0,10,25]){const sum=Array.from({length:10},(_,i)=>item.baseCost*item.costGrowth**(n+i)).reduce((a,b)=>a+b,0);close(hardwareBulkBaseCost(item,n,10),sum);assert.ok(hardwareUnitCost(item,n+1)>hardwareUnitCost(item,n))}}});
test('canonical Compute and allocation conserve the generated flow',()=>{const s=state(),total=computePerSecond(s);close(total,economySnapshot(s).computePerSecond);close(allocatedCompute(total,40)+allocatedCompute(total,60),total)});
test('Training requirement is static while actual modifiers genuinely reduce ETA',()=>{const base=state(),requirement=trainingRequiredForState(base),upgraded=structuredClone(base);upgraded.model.progress.tinyChat.skills.efficiency=9;upgraded.model.improvements.tinyChat={efficiency:9};assert.equal(trainingRequiredForState(upgraded),requirement);assert.ok(trainingRatePerSecond(upgraded)>trainingRatePerSecond(base));assert.ok(trainingEtaSeconds(upgraded)<trainingEtaSeconds(base));assert.equal(trainingRequirement(20,3),trainingRequirement(20,3))});
test('Efficiency affects Training and Capacity, but allocations never manufacture Demand',()=>{const low=state(),high=structuredClone(low);high.model.progress.tinyChat.skills.efficiency=16;high.model.improvements.tinyChat={efficiency:16};assert.ok(trainingRatePerSecond(high)>trainingRatePerSecond(low));assert.ok(economySnapshot(high).capacity>economySnapshot(low).capacity);const inference=structuredClone(low);inference.allocation={...inference.allocation,training:10,inference:90};assert.equal(potentialDemand(low),potentialDemand(inference));assert.ok(economySnapshot(inference).capacity>economySnapshot(low).capacity)});
test('Quality and Popularity retain their distinct Market dependency maps',()=>{const base=state(),quality=structuredClone(base),popularity=structuredClone(base);quality.model.progress.tinyChat.skills.quality=8;quality.model.improvements.tinyChat={quality:8};popularity.model.progress.tinyChat.skills.popularity=8;popularity.model.improvements.tinyChat={popularity:8};const b=economySnapshot(base),q=economySnapshot(quality),p=economySnapshot(popularity);assert.ok(q.demand>b.demand&&q.revenuePerUser>b.revenuePerUser);assert.ok(p.demand>b.demand);assert.equal(p.acquisitionHalfLife,null);close(p.revenuePerUser,b.revenuePerUser)});
test('Model level and tier curves remain finite, concave, and ordered through L500',()=>{let prior=0,priorDelta=Infinity;for(const level of [1,5,10,20,50,100,250,500]){const value=withinModelLevelFactor(level);assert.ok(Number.isFinite(value)&&value>prior);const delta=value-prior;if(prior)assert.ok(delta/(level)>0);prior=value;priorDelta=delta}assert.ok(priorDelta>0);for(let tier=1;tier<9;tier++)assert.ok(modelTierScale(tier)>modelTierScale(tier-1))});
test('offline canonical simulation is deterministic and finite',()=>{const s=state();const a=simulateDuration(s,300_000),b=simulateDuration(s,300_000);assert.deepEqual(a.resources,b.resources);for(const duration of [300_000,1_800_000,7_200_000]){const result=simulateDuration(s,duration);assert.ok(Object.values(result.resources).every(Number.isFinite))}});
test('canonical tick chunking keeps ten-minute Credit divergence below one percent',()=>{const s=state(),one=tickGame(s,600_000);let seconds=s;for(let i=0;i<600;i++)seconds=tickGame(seconds,1_000);const divergence=Math.abs(one.resources.credits-seconds.resources.credits)/seconds.resources.credits;assert.ok(divergence<.01,`Credit divergence ${divergence}`);const a=simulatePolicy('BALANCED',5),b=simulatePolicy('BALANCED',5);assert.deepEqual(a,b)});
