import test from 'node:test';
import assert from 'node:assert/strict';
import { createDefaultState, TECH_NODES } from '../src/data/defaultState.js';
import { baseIntEntitlement, claimableInt, intEntitlement, lifetimeQualifyingCompute } from '../src/systems/PrestigeSystem.js';
import { canDevelop, cycleIntelligence, developmentCycleRequirements, lifetimeIncomeMultiplier, purchaseTechnology, startDevelopmentCycle } from '../src/systems/GameSystem.js';
import { runPhase2C } from '../scripts/phase-2c-simulator.mjs';

function eligible(compute=650_000_000){const s=createDefaultState();s.statistics.totalComputeProduced=compute;s.run.computeProduced=compute;s.run.creditsEarned=0;s.hardware.gpuServer=1;s.model.level=20;s.model.progress.tinyChat.level=20;s.objectives=Object.fromEntries(Array.from({length:6},(_,i)=>[`o${i}`,true]));return s}

test('INT entitlement is monotonic and claimable INT is never negative',()=>{let prior=0;for(const compute of [0,1e6,1e8,1e10,1e14,1e40,1e100,1e300]){const value=baseIntEntitlement(compute);assert.ok(value>=prior&&Number.isFinite(value));prior=value}const s=eligible();s.meta.lifetimeIntClaimed=1e9;assert.equal(claimableInt(s),0)});
test('repeated reset cannot claim the same qualifying Compute',()=>{const first=eligible(),gain=cycleIntelligence(first),second=startDevelopmentCycle(first);assert.ok(gain>0);assert.equal(claimableInt(second),0);assert.equal(cycleIntelligence(second),0);assert.equal(second.meta.lifetimeIntClaimed,intEntitlement(first))});
test('reward ignores Credits and Inference allocation',()=>{const a=eligible(),b=structuredClone(a);b.run.creditsEarned=1e50;b.resources.credits=1e50;b.allocation.training=10;b.allocation.inference=90;assert.equal(cycleIntelligence(a),cycleIntelligence(b));assert.equal(lifetimeQualifyingCompute(a),lifetimeQualifyingCompute(b))});
test('Technology spends only Current INT and cannot reduce entitlement',()=>{const s=eligible();s.meta.intelligence=10;s.meta.totalIntelligence=10;s.meta.lifetimeIntClaimed=intEntitlement(s);const node=TECH_NODES.find(item=>item.id==='compute-1'),before=intEntitlement(s),next=purchaseTechnology(s,node.id);assert.equal(next.meta.intelligence,10-node.cost);assert.equal(next.meta.totalIntelligence,10);assert.equal(next.meta.lifetimeIntSpent,node.cost);assert.equal(intEntitlement(next),before)});
test('INT-gain Technology is applied once and raw INT has no Revenue multiplier',()=>{const s=eligible(1e10);s.meta.techNodes=['prestige-1'];const node=TECH_NODES.find(item=>item.id==='prestige-1'),base=baseIntEntitlement(1e10),expected=Math.floor(base*(1+node.value));assert.equal(cycleIntelligence(s),expected);assert.equal(lifetimeIncomeMultiplier(s),1)});
test('Development Cycle preserves permanent systems and resets run economy',()=>{const s=eligible();s.meta.intelligence=5;s.meta.totalIntelligence=5;s.meta.techNodes=['compute-1'];s.resources.research=123;s.patents.discovered=['cold-kernels'];s.patents.equipped=['cold-kernels'];s.resources.gems=7;s.inventory.instances=[{instanceId:'x',catalogId:'starter-chip'}];assert.ok(canDevelop(s));const next=startDevelopmentCycle(s);assert.equal(next.resources.credits,45);assert.equal(next.run.computeProduced,0);assert.deepEqual(next.meta.techNodes,['compute-1']);assert.equal(next.resources.research,123);assert.deepEqual(next.patents.discovered,['cold-kernels']);assert.equal(next.resources.gems,7);assert.equal(next.inventory.instances.length,1)});
test('eligibility separates anti-spam gates from informational Credits',()=>{const r=developmentCycleRequirements(eligible());assert.equal(r.ready,true);assert.ok(!('runCredits' in r.targets));assert.equal(r.informational.runCredits,0)});
test('Phase-2C cycle simulator is deterministic',()=>{const options={strategies:['COMPUTE_FIRST'],maxCycles:1,skipResetTiming:true},a=runPhase2C(options),b=runPhase2C(options);assert.deepEqual(a,b)});
