import test from 'node:test';
import assert from 'node:assert/strict';
import { BALANCE, featureUnlocked, isResearchUnlocked, viewUnlocked } from '../src/config/balance.js';
import { createDefaultState, MODEL_CATALOG, MODEL_SKILLS, OBJECTIVES, SAVE_VERSION, WORLD_EVENTS } from '../src/data/defaultState.js';
import { BillingService } from '../src/systems/BillingService.js';
import { activeTutorialStep, advanceTutorial, buyTrainingDoublePoints, cycleIntelligence, economySnapshot, finishTrainingWithGems, marketingCost, modelComparison, reconcileTutorial, researchPerSecond, setAllocation, tickGame, TUTORIAL_STEPS, trainModel, trainingDoublePointGemCost, trainingFinishGemCost, trainingRequiredForState, upgradeModelSkill, worldEventChoiceCost } from '../src/systems/GameSystem.js';
import { ensureMissions } from '../src/systems/MissionSystem.js';
import { reconcileOffline } from '../src/systems/OfflineProgressSystem.js';
import { SaveSystem } from '../src/systems/PersistentSaveSystem.js';
import { navigationItemsForState } from '../src/ui/navigation.js';

function modelState(modelId){const state=createDefaultState(),model=MODEL_CATALOG.find(entry=>entry.id===modelId),progress={level:5,xp:0,upgradePoints:20,availablePoints:20,trainings:4,trainingCount:4,totalPointsEarned:20,totalPointsSpent:0,skills:{}};return{...state,resources:{...state.resources,credits:1e9},hardware:{...state.hardware,gamingPc:10},model:{...state.model,activeId:modelId,trainingTarget:modelId,owned:[...new Set([...state.model.owned,modelId])],deployed:[modelId],level:5,upgradePoints:20,progress:{...state.model.progress,[modelId]:progress}},meta:{...state.meta,unlockedModels:[...new Set([...state.meta.unlockedModels,modelId])]},expectedModel:model}}

test('condition-driven tutorial skips completed requirements and is reload safe',()=>{let state=createDefaultState();state={...state,tutorial:{step:1,completed:false,acknowledged:['economy']},hardware:{...state.hardware,calculator:1},statistics:{...state.statistics,totalComputeProduced:1},model:{...state.model,trainingActive:true},market:{...state.market,marketing:2}};state=reconcileTutorial(state);assert.equal(state.tutorial.step,4);state.model.trainingActive=false;state.model.progress.tinyChat.trainingCount=1;state.model.progress.tinyChat.trainings=1;state.model.progress.tinyChat.totalPointsSpent=1;state.resources.users=2;state.tutorial.acknowledged.push('marketing-intro','capacity','objectives');state=reconcileTutorial(state);assert.equal(state.tutorial.step,11);assert.deepEqual(reconcileTutorial(structuredClone(state)).tutorial,state.tutorial)});

test('Research unlock propagates after first Development Cycle and survives restored state',()=>{let state=createDefaultState();assert.equal(viewUnlocked(state,'research'),false);state={...state,meta:{...state.meta,cycles:1}};assert(featureUnlocked(state,'research'));assert(viewUnlocked(state,'research'));assert(navigationItemsForState(state).some(item=>item.id==='research'));assert(featureUnlocked(structuredClone(state),'research'))});

test('Research tutorial is parked until the first Development Cycle',()=>{let state=createDefaultState();state={...state,tutorial:{...state.tutorial,step:11}};assert.equal(isResearchUnlocked(state),false);assert.equal(activeTutorialStep(state),null);state={...state,meta:{...state.meta,cycles:1}};assert.equal(isResearchUnlocked(state),true);assert.equal(activeTutorialStep(state)?.id,'research');const opened=advanceTutorial(state);assert.equal(opened.ui.activeView,'research')});

test('Research allocation and production share the post-Cycle unlock contract',()=>{let state={...createDefaultState(),hardware:{...createDefaultState().hardware,calculator:10}};const locked=setAllocation(state,'research',50);assert.equal(locked,state);assert.equal(researchPerSecond(state),0);state={...state,meta:{...state.meta,cycles:1}};state=setAllocation(state,'research',50);assert.equal(state.allocation.research,50);assert(researchPerSecond(state)>0);const before=state.resources.research;state=tickGame(state,1000);assert(state.resources.research>before)});

test('all tutorial lessons declare separate eligibility and completion semantics',()=>{assert.equal(TUTORIAL_STEPS.length,14);for(const step of TUTORIAL_STEPS){assert.equal(typeof step.eligible,'function',step.id);assert.equal(typeof step.condition,'function',step.id);assert.equal(typeof step.feature,'string',step.id);if(step.view)assert.equal(typeof step.view,'string',step.id)}});

test('returning Research saves skip a lesson already completed through real Research use',()=>{let state={...createDefaultState(),tutorial:{step:11,completed:false,acknowledged:[]},resources:{...createDefaultState().resources,research:25},meta:{...createDefaultState().meta,cycles:1,techNodes:['research-1']}};state=reconcileTutorial(state);assert.equal(state.tutorial.completed,true);assert(isResearchUnlocked(state))});

test('only the three primary Model Improvements remain in the active contract',()=>{assert.deepEqual(MODEL_SKILLS,['quality','efficiency','popularity'])});

for(const modelId of ['tinyChat','smartChat','gptClass'])test(`${modelId} Quality, Efficiency, and Popularity alter canonical economy`,()=>{const base=modelState(modelId);for(const skill of MODEL_SKILLS){const before=economySnapshot(base),next=upgradeModelSkill(structuredClone(base),modelId,skill),after=economySnapshot(next);assert.equal(next.model.progress[modelId].skills[skill],1);if(skill==='efficiency')assert(after.capacity>before.capacity);else assert(after.demand>before.demand);if(skill==='quality')assert(after.revenuePerUser>before.revenuePerUser)}});

test('model comparisons derive meaningful deltas from authored model data',()=>{const comparison=modelComparison(createDefaultState(),'gptClass');assert.equal(comparison.against,'TinyChat');assert(comparison.demand>0);assert(comparison.revenue>0);assert(comparison.training>0)});

test('Gem finish and double-point actions are atomic and recorded',()=>{let state=modelState('tinyChat');state.resources.gems=100;state=trainModel(state);const doubleCost=trainingDoublePointGemCost(state),finishCost=trainingFinishGemCost(state);assert(doubleCost>0&&finishCost>0);state=buyTrainingDoublePoints(state);assert.equal(state.resources.gems,100-doubleCost);assert.equal(state.model.trainingSession.doublePointsPurchased,true);assert.equal(buyTrainingDoublePoints(state),state);state=finishTrainingWithGems(state);assert.equal(state.model.trainingActive,false);assert.equal(state.model.progress.tinyChat.availablePoints,22);assert.equal(state.model.lastTrainingResult.upgradePointsGained,2);assert(state.gemEconomy.history.some(entry=>entry.source==='training-finish'));assert(state.gemEconomy.history.some(entry=>entry.source==='training-double-points'))});

test('offline Training completes once and reports its Model Point reward',()=>{let state=modelState('tinyChat');state.hardware.calculator=100;state=trainModel(state);state.model.trainingProgress=trainingRequiredForState(state)-1;state.offline.lastActiveTimestamp=1_000;state=reconcileOffline(state,21_000);assert.equal(state.model.trainingActive,false);assert.equal(state.model.lastTrainingResult.offline,true);assert.equal(state.model.progress.tinyChat.trainingCount,5);assert(state.offline.results.milestones.some(line=>line.includes('TRAINING COMPLETED')));const points=state.model.progress.tinyChat.availablePoints;state=reconcileOffline(state,21_000);assert.equal(state.model.progress.tinyChat.availablePoints,points)});

test('first Development Cycle is gated by mature run milestones and early INT stays scarce',()=>{let early=createDefaultState();early.run.computeProduced=1e12;early.run.creditsEarned=1e12;early.hardware.gamingPc=100;early.model.progress.tinyChat.level=20;assert.equal(cycleIntelligence(early),0);let mature=structuredClone(early);mature.hardware.miniDatacenter=1;mature.model.progress.tinyChat.level=BALANCE.intelligence.minimumModelLevel;mature.objectives=Object.fromEntries(OBJECTIVES.slice(0,BALANCE.intelligence.minimumObjectives).map(item=>[item.id,true]));mature.run.computeProduced=BALANCE.intelligence.computeScale;mature.run.creditsEarned=BALANCE.intelligence.creditScale;assert.equal(cycleIntelligence(mature),1);mature.run.computeProduced*=1e6;mature.run.creditsEarned*=1e6;assert(cycleIntelligence(mature)<20)});

test('Marketing and world-event costs remain relevant across economic orders',()=>{assert(marketingCost(30)>1e9);const low=createDefaultState(),high=modelState('gptClass'),choice=WORLD_EVENTS.find(event=>event.id==='shortage').choices[0];high.resources.users=1e6;const lowCost=worldEventChoiceCost(low,choice),highCost=worldEventChoiceCost(high,choice);assert(lowCost>=choice.cost);assert(highCost>lowCost)});

test('mission periods provide scaled Credits and controlled Gem rewards',()=>{const state=modelState('tinyChat'),missions=ensureMissions(state,new Date('2026-08-28T12:00:00Z')).missions;for(const period of ['daily','weekly','monthly']){assert(missions[period].length>0);assert(missions[period].some(entry=>entry.reward.gems||entry.reward.credits||entry.reward.item||entry.reward.cache))}const creditRewards=[...missions.daily,...missions.weekly,...missions.monthly].filter(entry=>entry.reward.credits);assert(creditRewards.every(entry=>entry.reward.credits>=BALANCE.missions.creditRewardFloor[entry.period]))});

test('version 18 saves migrate tutorial and obsolete specializations without losing core progress',()=>{const old=createDefaultState();old.version=18;old.tutorial={step:5,completed:false};old.model.progress.tinyChat.skills={quality:2,reasoning:8};const storage=new Map([['ai-singularity-save',JSON.stringify(old)]]),previous=globalThis.localStorage;globalThis.localStorage={getItem:key=>storage.get(key)??null,setItem:(key,value)=>storage.set(key,value)};try{const loaded=new SaveSystem({}).load();assert.equal(loaded.version,SAVE_VERSION);assert.equal(loaded.model.progress.tinyChat.skills.quality,2);assert.equal(loaded.model.progress.tinyChat.skills.reasoning,undefined);assert(Array.isArray(loaded.tutorial.acknowledged))}finally{if(previous===undefined)delete globalThis.localStorage;else globalThis.localStorage=previous}});

test('locked Research allocation is repaired on load and legacy Research unlocks remain valid',()=>{const previous=globalThis.localStorage,load=save=>{const storage=new Map([['ai-singularity-save',JSON.stringify(save)]]);globalThis.localStorage={getItem:key=>storage.get(key)??null,setItem:(key,value)=>storage.set(key,value)};return new SaveSystem({}).load()};try{const locked=createDefaultState();locked.allocation={training:20,inference:20,research:40,data:20,agents:0};const repaired=load(locked);assert.equal(repaired.allocation.research,0);assert.equal(repaired.allocation.inference,60);const legacy=createDefaultState();legacy.meta.techNodes=['system-research'];const restored=load(legacy);assert(isResearchUnlocked(restored));assert(viewUnlocked(restored,'research'))}finally{if(previous===undefined)delete globalThis.localStorage;else globalThis.localStorage=previous}});

test('web billing boundary cannot fabricate native purchases',async()=>{const billing=new BillingService();assert(billing.products().every(product=>!product.available));assert.deepEqual(await billing.purchase('gem_pack_1'),{ok:false,reason:'NATIVE_BILLING_UNAVAILABLE'})});
