import test from 'node:test';
import assert from 'node:assert/strict';
import { createDefaultState } from '../src/data/defaultState.js';
import { computePerSecond, economySnapshot, optimizeCode, researchPerSecond, startDevelopmentCycle, tickGame } from '../src/systems/GameSystem.js';
import { RESEARCH_PROJECTS, researchEffect, researchMechanic, researchPrerequisitesMet, researchProjectCost, startResearchProject, tickResearchLabs, unlockedResearchLabs } from '../src/systems/ResearchSystem.js';
import { BALANCE } from '../src/config/balance.js';

const powered=()=>{const state=createDefaultState();state.hardware.workstation=10;state.resources.research=1e9;return state};
const complete=(state,id)=>({...state,researchUpgradeLevels:{...state.researchUpgradeLevels,[id]:1}});

test('Research Tree has seven clean branches and twenty-seven prerequisite-safe nodes',()=>{assert.equal(RESEARCH_PROJECTS.length,27);assert.deepEqual([...new Set(RESEARCH_PROJECTS.map(node=>node.branch))],['COMPUTE','MODEL','RESEARCH','ECONOMY','ACTIVE','AUTOMATION','PATENT DISCOVERY']);const ids=new Set(RESEARCH_PROJECTS.map(node=>node.id));assert.equal(ids.size,RESEARCH_PROJECTS.length);assert(RESEARCH_PROJECTS.every(node=>node.prerequisites.every(id=>ids.has(id))));assert(!RESEARCH_PROJECTS.some(node=>/demand|marketing|adoption|popularity|allocation|agents/i.test(`${node.name} ${node.description} ${node.effect.type}`)))});

test('Hardware Compute creates RP in parallel and Research never reduces Capacity',()=>{const state=powered(),before=economySnapshot(state);assert.equal(researchPerSecond(state)>0,computePerSecond(state)>0);const project=RESEARCH_PROJECTS[0],started=startResearchProject(state,project.id,1),during=economySnapshot(started);assert.equal(during.capacity,before.capacity);assert.equal(during.users,before.users);assert.equal(during.researchPerSecond,before.researchPerSecond)});

test('Research prerequisites, costs, completion, and repeatable growth are enforced',()=>{let state=powered();const repeatable=RESEARCH_PROJECTS.find(node=>node.repeatable);assert(!researchPrerequisitesMet(state,repeatable));assert.equal(startResearchProject(state,repeatable.id,1),state);for(const id of repeatable.prerequisites)state=complete(state,id);const cost=researchProjectCost(state,repeatable),started=startResearchProject(state,repeatable.id,1);assert.equal(started.resources.research,state.resources.research-cost);const done=tickResearchLabs(started,started.researchLabs.labs[0].remainingSeconds*1000+1);assert.equal(done.researchUpgradeLevels[repeatable.id],1);assert(researchProjectCost(done,repeatable)>cost)});

test('Research effects alter Compute, Quality economy, Efficiency capacity, RP, and taps',()=>{const base=powered();base.model.progress.tinyChat.skills={quality:1,efficiency:1};const baseEconomy=economySnapshot(base),baseTap=optimizeCode(base).resources.compute;const levels={'research-compute-1':1,'research-model-2':1,'research-model-3':1,'research-science-1':1,'research-active-1':1},boosted={...base,researchUpgradeLevels:levels};assert(researchEffect(boosted,'hardwareOutput')>0);assert(computePerSecond(boosted)>computePerSecond(base));assert(economySnapshot(boosted).revenuePerUser>baseEconomy.revenuePerUser);assert(economySnapshot(boosted).capacity>baseEconomy.capacity);assert(researchPerSecond(boosted)>researchPerSecond(base));assert(optimizeCode(boosted).resources.compute>baseTap)});

test('Research milestones unlock parallel Labs and the four automation capabilities',()=>{let state=powered();state=complete(state,'research-science-2');assert.equal(unlockedResearchLabs(state),2);for(const id of ['research-automation-1','research-automation-2','research-automation-3','research-automation-4'])state=complete(state,id);for(const mechanic of ['research-auto-buy','research-auto-train','research-auto-model','research-auto-research'])assert(researchMechanic(state,mechanic));state.resources.credits=1e9;state.session.elapsedMs=2_000;const automated=tickGame(state,1_000);assert(Object.values(automated.hardware).some(value=>value>state.hardware.calculator));assert(automated.model.trainingActive)});

test('Development Cycle resets RP, Research levels, and active Labs while retaining separate patents',()=>{let state=powered();state.resources.research=12345;state.researchUpgradeLevels={'research-compute-1':1};state.researchLabs.completedProjects=['research-compute-1:1'];state.patents.discovered=['cold-kernels'];state.patents.equipped=['cold-kernels'];state.model.level=BALANCE.intelligence.minimumModelLevel;state.model.progress.tinyChat.level=BALANCE.intelligence.minimumModelLevel;state.hardware[Object.keys(state.hardware)[BALANCE.intelligence.minimumHardwareTier]]=1;state.run.computeProduced=BALANCE.intelligence.computeScale*2;state.statistics.totalComputeProduced=BALANCE.intelligence.computeScale*2;state.objectives=Object.fromEntries(Array.from({length:BALANCE.intelligence.minimumObjectives},(_,i)=>[`goal-${i}`,true]));const next=startDevelopmentCycle(state);assert.notEqual(next,state);assert.equal(next.resources.research,0);assert.deepEqual(next.researchUpgradeLevels,{});assert.deepEqual(next.researchLabs.completedProjects,[]);assert.deepEqual(next.patents.discovered,['cold-kernels'])});

test('legacy flat Research upgrades migrate into matching Tree nodes',async()=>{const {SaveSystem}=await import('../src/systems/PersistentSaveSystem.js'),legacy=createDefaultState();legacy.upgrades=['research-algorithms','research-silicon'];legacy.researchUpgradeLevels={'research-algorithms':2};const prior=globalThis.localStorage;globalThis.localStorage={getItem:key=>key==='ai-singularity-save'?JSON.stringify(legacy):null};try{const loaded=new SaveSystem(null).load();assert.equal(loaded.researchUpgradeLevels['research-model-1'],2);assert.equal(loaded.researchUpgradeLevels['research-compute-1'],1);assert.equal(loaded.researchUpgradeLevels['research-algorithms'],undefined)}finally{if(prior===undefined)delete globalThis.localStorage;else globalThis.localStorage=prior}});
