import test from 'node:test';
import assert from 'node:assert/strict';
import { AppShell } from '../src/ui/AppShell.js';
import { EventBus } from '../src/core/EventBus.js';
import { Application } from '../src/core/Application.js';
import { RenderPipeline } from '../src/core/RenderPipeline.js';
import { SaveSystem } from '../src/systems/SaveSystem.js';
import { createDefaultState } from '../src/data/defaultState.js';
import { computePerSecond, createDefaultEconomySnapshot, economySnapshot, startDevelopmentCycle } from '../src/systems/GameSystem.js';
import { reconcileOffline } from '../src/systems/OfflineProgressSystem.js';
import { ensureGameState, isCompleteGameState, validateGameState } from '../src/core/GameStateContract.js';
import { dismissReward, enqueueReward } from '../src/systems/RewardQueue.js';
import { bootstrap } from '../src/core/bootstrap.js';
import { navigationItemsForState } from '../src/ui/navigation.js';
import { isDeveloperMode, TelemetryService } from '../src/dev/telemetry-service.js';
import { cloneState } from '../src/core/clone.js';
import { animateElement } from '../src/ui/animation.js';
import { readFileSync } from 'node:fs';

class MockNode {
  constructor() { this.innerHTMLWrites = 0; this.dataset = {}; this.style = {}; this.listeners = new Map(); this.classList = { toggle() {} }; this.parentElement = { hidden: false }; this.disabled = false; this.value = ''; this.textContent = ''; this.firstElementChild = { animate() {} }; }
  set innerHTML(value) { this.innerHTMLWrites += 1; this.html = value; this.firstElementChild = { animate() {} }; }
  get innerHTML() { return this.html ?? ''; }
  addEventListener(type, listener) { this.listeners.set(type, listener); }
  removeEventListener(type) { this.listeners.delete(type); }
  dispatch(type, event) { this.listeners.get(type)?.(event); }
  animate() {}
  querySelector(selector) { return this.nodes?.get(selector) ?? new MockNode(); }
  querySelectorAll() { return []; }
  insertAdjacentHTML(_position, value) { this.html = `${this.html ?? ''}${value}`; }
  closest() { return null; }
}
class MockRoot extends MockNode {
  constructor() { super(); this.nodes = new Map(); }
  querySelector(selector) { if (!this.nodes.has(selector)) this.nodes.set(selector, new MockNode()); return this.nodes.get(selector); }
}
function memoryStorage(initial = {}) { const data = new Map(Object.entries(initial)); return { get length(){return data.size}, key:index=>[...data.keys()][index]??null, getItem:key=>data.get(key)??null, setItem:(key,value)=>data.set(key,String(value)), removeItem:key=>data.delete(key), clear:()=>data.clear() }; }
function installBrowser(search = '', suppliedStorage = memoryStorage()) { const original = { window:globalThis.window, document:globalThis.document, location:globalThis.location, localStorage:globalThis.localStorage, requestAnimationFrame:globalThis.requestAnimationFrame, cancelAnimationFrame:globalThis.cancelAnimationFrame }; const storage=suppliedStorage; globalThis.localStorage=storage; globalThis.location={search}; globalThis.requestAnimationFrame=()=>1; globalThis.cancelAnimationFrame=()=>{}; globalThis.window={setInterval:()=>1,clearInterval(){},addEventListener(){},removeEventListener(){},location:{href:`http://localhost/${search}`,replace(){}}}; globalThis.document={activeElement:null,hidden:false,addEventListener(){},removeEventListener(){},createElement:()=>new MockNode()}; return()=>{for(const [key,value] of Object.entries(original)){if(value===undefined)delete globalThis[key];else globalThis[key]=value}} }

test('fresh AppShell first render produces the dashboard and only core navigation',()=>{const root=new MockRoot(),shell=new AppShell(root,new EventBus());shell.mount(createDefaultState());assert.match(root.querySelector('[data-workspace]').innerHTML,/COMMAND CENTER/);const ids=navigationItemsForState(createDefaultState()).map(({id})=>id);assert.deepEqual(ids,['dashboard','hardware','model','objectives'])});
test('developer navigation is opt-in and does not replace the first player render',()=>{const root=new MockRoot(),shell=new AppShell(root,new EventBus(),{devMode:true,telemetry:{}});shell.mount(createDefaultState());assert.match(root.querySelector('[data-workspace]').innerHTML,/COMMAND CENTER/);assert.match(root.querySelector('[data-navigation]').innerHTML,/Developer Analytics/);assert.match(root.querySelector('[data-navigation]').innerHTML,/Runtime Inspector/)});
test('blocked developer storage cannot interfere with normal mode',()=>{const blocked={getItem(){throw new Error('storage blocked')}};assert.equal(isDeveloperMode({search:''},blocked),false);assert.equal(isDeveloperMode({search:'?dev=1'},blocked),true)});
test('Application initializes in normal and developer modes without a runtime exception',()=>{for(const search of ['', '?dev=1']){const restore=installBrowser(search);try{const root=new MockRoot(),errors=[],application=new Application(root,{onRuntimeError:error=>errors.push(error)});application.start();assert.match(root.querySelector('[data-workspace]').innerHTML,/COMMAND CENTER/);assert.deepEqual(errors,[]);application.stop()}finally{restore()}}});
test('telemetry failure is isolated from developer-mode gameplay',()=>{const restore=installBrowser('?dev=1'),originalError=globalThis.console.error,originalStart=TelemetryService.prototype.start;try{globalThis.console.error=()=>{};TelemetryService.prototype.start=function(){throw new Error('telemetry unavailable')};const root=new MockRoot(),application=new Application(root);application.start();assert.match(root.querySelector('[data-workspace]').innerHTML,/COMMAND CENTER/);application.stop()}finally{TelemetryService.prototype.start=originalStart;globalThis.console.error=originalError;restore()}});
test('bootstrap renders a visible recovery screen instead of remaining blank',()=>{const host=new MockRoot(),original=globalThis.console.error;class BrokenApplication{start(){throw new Error('render exploded')}}try{globalThis.console.error=()=>{};const instance=bootstrap(host,BrokenApplication);assert.equal(instance,null);assert.match(host.innerHTML,/Startup recovery/);assert.match(host.querySelector('pre').textContent,/Error: render exploded/);assert.match(host.querySelector('pre').textContent,/Runtime diagnostics/)}finally{globalThis.console.error=original}});
test('RenderPipeline contains asynchronous render failures',()=>{const originalRaf=globalThis.requestAnimationFrame;let callback;globalThis.requestAnimationFrame=fn=>{callback=fn;return 1};try{let captured;const pipeline=new RenderPipeline(()=>{throw new Error('frame failed')},error=>{captured=error});pipeline.request({});callback();assert.equal(captured.message,'frame failed')}finally{if(originalRaf===undefined)delete globalThis.requestAnimationFrame;else globalThis.requestAnimationFrame=originalRaf}});
test('corrupted and structurally malformed saves recover safely',()=>{const previous=globalThis.localStorage;try{globalThis.localStorage=memoryStorage({'ai-singularity-save':'{bad json'});assert.equal(new SaveSystem({}).load(),null);const malformed=createDefaultState();malformed.model={...malformed.model,activeId:'missing',owned:'invalid',deployed:'invalid',improvements:null,progress:null};malformed.hardware={calculator:-5};malformed.upgrades=null;malformed.objectives=null;malformed.world={...malformed.world,modifiers:null};malformed.meta={...malformed.meta,techNodes:null,achievements:null};globalThis.localStorage=memoryStorage({'ai-singularity-save':JSON.stringify(malformed)});const recovered=new SaveSystem({}).load();assert(recovered);assert.deepEqual(recovered.model.owned,['tinyChat']);assert.deepEqual(recovered.model.deployed,['tinyChat']);assert.equal(recovered.model.activeId,'tinyChat');assert.equal(recovered.hardware.calculator,0);assert.deepEqual(recovered.upgrades,[]);assert.deepEqual(recovered.objectives,{});assert.deepEqual(recovered.world.modifiers,[]);assert.deepEqual(recovered.meta.techNodes,[])}finally{if(previous===undefined)delete globalThis.localStorage;else globalThis.localStorage=previous}});


test('canonical state and economy contracts hydrate undefined and pre-item states',()=>{const fallback=createDefaultEconomySnapshot();const snapshot=economySnapshot(undefined);assert.deepEqual(Object.keys(snapshot),Object.keys(fallback));assert(Object.values(snapshot).every(value=>value===null||typeof value==='string'||Number.isFinite(value)));assert.equal(computePerSecond(undefined),0);const legacy=createDefaultState();delete legacy.inventory;delete legacy.artifacts;delete legacy.rewardedBoosts;const hydrated=ensureGameState(legacy);assert(isCompleteGameState(hydrated));assert.equal(economySnapshot(hydrated).computePerSecond,0)});

test('all startup transitions render with complete state and finite economy values',()=>{const scenarios=[];const fresh=createDefaultState();scenarios.push(['fresh',fresh]);const legacy={...fresh,version:8};delete legacy.inventory;delete legacy.artifacts;delete legacy.offline;delete legacy.rewards;scenarios.push(['migrated',legacy]);const reset=createDefaultState();scenarios.push(['reset',reset]);let eligible={...fresh,run:{...fresh.run,computeProduced:1_000_000}};eligible=startDevelopmentCycle(eligible);scenarios.push(['development-cycle',eligible]);const offline={...fresh,hardware:{...fresh.hardware,calculator:2},offline:{...fresh.offline,lastActiveTimestamp:1_000}};scenarios.push(['offline-return',reconcileOffline(offline,61_000)]);for(const [name,candidate] of scenarios){const state=ensureGameState(candidate),root=new MockRoot(),shell=new AppShell(root,new EventBus());assert.doesNotThrow(()=>shell.mount(state),name);assert.match(root.querySelector('[data-workspace]').innerHTML,/COMMAND CENTER/,name);const economy=economySnapshot(state);assert(Number.isFinite(economy.computePerSecond),name);assert(Number.isFinite(economy.creditsPerSecond),name)}});

test('browser reload starts twice from the persisted migrated state without an exception',()=>{const storage=memoryStorage(),firstRestore=installBrowser('',storage);try{const firstRoot=new MockRoot(),first=new Application(firstRoot);first.start();first.stop()}finally{firstRestore()}const secondRestore=installBrowser('',storage);try{const secondRoot=new MockRoot(),errors=[],second=new Application(secondRoot,{onRuntimeError:error=>errors.push(error)});second.start();assert.match(secondRoot.querySelector('[data-workspace]').innerHTML,/COMMAND CENTER/);assert.deepEqual(errors,[]);second.stop()}finally{secondRestore()}});

test('developer mode starts from a legacy save missing economy-adjacent systems',()=>{const legacy=createDefaultState();legacy.version=8;delete legacy.inventory;delete legacy.artifacts;delete legacy.rewards;delete legacy.offline;const storage=memoryStorage({'ai-singularity-save':JSON.stringify(legacy)}),restore=installBrowser('?dev=1',storage);try{const root=new MockRoot(),errors=[],application=new Application(root,{onRuntimeError:error=>errors.push(error)});application.start();assert.match(root.querySelector('[data-workspace]').innerHTML,/COMMAND CENTER/);assert.deepEqual(errors,[]);application.stop()}finally{restore()}});

test('developer validation fails fast without repairing malformed runtime state',()=>{const invalid=createDefaultState();delete invalid.inventory;assert.throws(()=>validateGameState(invalid,economySnapshot(createDefaultState())),/inventory or equipped items are missing/);const invalidEconomy={...createDefaultEconomySnapshot(),computePerSecond:NaN};assert.throws(()=>validateGameState(createDefaultState(),invalidEconomy),/economy snapshot contains NaN/)});

test('offline Continue owns input, dismisses the reward, and restores gameplay',()=>{let state=createDefaultState();state={...state,world:{...state.world,activeEvent:{id:'queued-world',title:'Queued event',description:'waits',choices:[]}}};state=enqueueReward(state,{category:'offline',title:'WELCOME BACK',lines:[{key:'Credits',value:10}],metadata:{effectiveDurationMs:60_000,durationMs:60_000}});const root=new MockRoot(),bus=new EventBus(),shell=new AppShell(root,bus);bus.on('reward:dismiss',id=>{state=dismissReward(state,id);shell.render(state)});shell.mount(state);assert.match(root.querySelector('[data-reward-queue]').innerHTML,/CONTINUE/);assert.equal(root.querySelector('[data-world-event]').innerHTML,'');assert.equal(root.querySelector('[data-patent-popup]').innerHTML,'');assert.equal(root.querySelector('[data-item-popup]').innerHTML,'');const rewardHost=root.querySelector('[data-reward-queue]'),writesBeforeStableRender=rewardHost.innerHTMLWrites;shell.render(state);shell.render(state);assert.equal(rewardHost.innerHTMLWrites,writesBeforeStableRender,'active reward DOM must remain stable between pointer down and click');assert.match(rewardHost.innerHTML,/type="button"/);const button={dataset:{rewardDismiss:'reward-1'},disabled:false,closest(selector){return selector==='[data-reward-dismiss]'?this:null}};root.dispatch('click',{target:button});assert.equal(state.rewards.queue.length,0);assert.equal(state.offline.rewardPending,false);assert.equal(root.querySelector('[data-reward-queue]').innerHTML,'');assert.match(root.querySelector('[data-world-event]').innerHTML,/Queued event/)});

test('startup remains compatible when structuredClone and Web Animations are unavailable',()=>{const original=globalThis.structuredClone;try{delete globalThis.structuredClone;const source=createDefaultState(),copy=cloneState(source);assert.deepEqual(copy,source);assert.notEqual(copy,source);assert.doesNotThrow(()=>animateElement({},[],{}));const restore=installBrowser('');try{const root=new MockRoot(),application=new Application(root);application.start();assert.match(root.querySelector('[data-workspace]').innerHTML,/COMMAND CENTER/);application.stop()}finally{restore()}}finally{if(original!==undefined)globalThis.structuredClone=original}});

test('HTML provides a visible pre-module startup fallback instead of a white page',()=>{const html=readFileSync(new URL('../index.html',import.meta.url),'utf8');assert.match(html,/INITIALIZING COMPANY SYSTEMS/);assert.match(html,/boot-error/);assert.match(html,/window\.addEventListener\('error'/)});
