import test from 'node:test';
import assert from 'node:assert/strict';
import { AppShell, findTechnologyNode, technologyNodeSelector } from '../src/ui/AppShell.js';
import { EventBus } from '../src/core/EventBus.js';
import { Application } from '../src/core/Application.js';
import { RenderPipeline } from '../src/core/RenderPipeline.js';
import { SaveSystem } from '../src/systems/PersistentSaveSystem.js';
import { createDefaultState, SAVE_VERSION, TECH_NODES } from '../src/data/defaultState.js';
const TECH_NODE_COUNT=TECH_NODES.length;
import { advanceTutorial, computePerSecond, createDefaultEconomySnapshot, economySnapshot, startDevelopmentCycle, buyMarketing, marketingCost, purchaseTechnology, tickGame, trainModel, trainingRequiredForState, upgradeModelSkill } from '../src/systems/GameSystem.js';
import { reconcileOffline } from '../src/systems/OfflineProgressSystem.js';
import { ensureGameState, isCompleteGameState, validateGameState } from '../src/core/GameStateContract.js';
import { dismissReward, enqueueReward } from '../src/systems/RewardQueue.js';
import { bootstrap } from '../src/core/bootstrap.js';
import { navigationItemsForState } from '../src/ui/navigation.js';
import { isDeveloperMode, TelemetryService } from '../src/dev/telemetry-service.js';
import { cloneState } from '../src/core/clone.js';
import { animateElement } from '../src/ui/animation.js';
import { readFileSync } from 'node:fs';

class MockNode {
  constructor() { this.innerHTMLWrites = 0; this.dataset = {}; this.style = {}; this.listeners = new Map(); this.classList = { toggle() {} }; this.parentElement = { hidden: false }; this.disabled = false; this.value = ''; this.textContent = ''; this.firstElementChild = { animate() {} }; }
  set innerHTML(value) { this.innerHTMLWrites += 1; this.html = value; this.firstElementChild = { animate() {} }; }
  get innerHTML() { return this.html ?? ''; }
  addEventListener(type, listener) { this.listeners.set(type, listener); }
  removeEventListener(type) { this.listeners.delete(type); }
  dispatch(type, event) { this.listeners.get(type)?.(event); }
  animate() {}
  querySelector(selector) { return this.nodes?.get(selector) ?? new MockNode(); }
  querySelectorAll() { return []; }
  insertAdjacentHTML(_position, value) { this.html = `${this.html ?? ''}${value}`; }
  closest() { return null; }
}
class MockRoot extends MockNode {
  constructor() { super(); this.nodes = new Map(); }
  querySelector(selector) { if (!this.nodes.has(selector)) this.nodes.set(selector, new MockNode()); return this.nodes.get(selector); }
}
function memoryStorage(initial = {}) { const data = new Map(Object.entries(initial)); return { get length(){return data.size}, key:index=>[...data.keys()][index]??null, getItem:key=>data.get(key)??null, setItem:(key,value)=>data.set(key,String(value)), removeItem:key=>data.delete(key), clear:()=>data.clear() }; }
function installBrowser(search = '', suppliedStorage = memoryStorage()) { const original = { window:globalThis.window, document:globalThis.document, location:globalThis.location, localStorage:globalThis.localStorage, requestAnimationFrame:globalThis.requestAnimationFrame, cancelAnimationFrame:globalThis.cancelAnimationFrame }; const storage=suppliedStorage; globalThis.localStorage=storage; globalThis.location={search}; globalThis.requestAnimationFrame=()=>1; globalThis.cancelAnimationFrame=()=>{}; globalThis.window={setInterval:()=>1,clearInterval(){},addEventListener(){},removeEventListener(){},location:{href:`http://localhost/${search}`,replace(){}}}; globalThis.document={activeElement:null,hidden:false,addEventListener(){},removeEventListener(){},createElement:()=>new MockNode()}; return()=>{for(const [key,value] of Object.entries(original)){if(value===undefined)delete globalThis[key];else globalThis[key]=value}} }

test('fresh AppShell first render produces the dashboard and only core navigation',()=>{const root=new MockRoot(),shell=new AppShell(root,new EventBus());shell.mount(createDefaultState());assert.match(root.querySelector('[data-workspace]').innerHTML,/COMMAND CENTER/);const ids=navigationItemsForState(createDefaultState()).map(({id})=>id);assert.deepEqual(ids,['dashboard','hardware','model','market','objectives','gemshop','missions'])});
test('developer navigation is opt-in and does not replace the first player render',()=>{const root=new MockRoot(),shell=new AppShell(root,new EventBus(),{devMode:true,telemetry:{}});shell.mount(createDefaultState());assert.match(root.querySelector('[data-workspace]').innerHTML,/COMMAND CENTER/);assert.match(root.querySelector('[data-navigation]').innerHTML,/Developer Analytics/);assert.match(root.querySelector('[data-navigation]').innerHTML,/Runtime Inspector/)});
test('blocked developer storage cannot interfere with normal mode',()=>{const blocked={getItem(){throw new Error('storage blocked')}};assert.equal(isDeveloperMode({search:''},blocked),false);assert.equal(isDeveloperMode({search:'?dev=1'},blocked),true)});
test('Application initializes in normal and developer modes without a runtime exception',()=>{for(const search of ['', '?dev=1']){const restore=installBrowser(search);try{const root=new MockRoot(),errors=[],application=new Application(root,{onRuntimeError:error=>errors.push(error)});application.start();assert.match(root.querySelector('[data-workspace]').innerHTML,/COMMAND CENTER/);assert.deepEqual(errors,[]);application.stop()}finally{restore()}}});
test('telemetry failure is isolated from developer-mode gameplay',()=>{const restore=installBrowser('?dev=1'),originalError=globalThis.console.error,originalStart=TelemetryService.prototype.start;try{globalThis.console.error=()=>{};TelemetryService.prototype.start=function(){throw new Error('telemetry unavailable')};const root=new MockRoot(),application=new Application(root);application.start();assert.match(root.querySelector('[data-workspace]').innerHTML,/COMMAND CENTER/);application.stop()}finally{TelemetryService.prototype.start=originalStart;globalThis.console.error=originalError;restore()}});
test('bootstrap renders a visible recovery screen instead of remaining blank',()=>{const host=new MockRoot(),original=globalThis.console.error;class BrokenApplication{start(){throw new Error('render exploded')}}try{globalThis.console.error=()=>{};const instance=bootstrap(host,BrokenApplication);assert.equal(instance,null);assert.match(host.innerHTML,/Startup recovery/);assert.match(host.querySelector('pre').textContent,/Error: render exploded/);assert.match(host.querySelector('pre').textContent,/Runtime diagnostics/)}finally{globalThis.console.error=original}});
test('RenderPipeline contains asynchronous render failures',()=>{const originalRaf=globalThis.requestAnimationFrame;let callback;globalThis.requestAnimationFrame=fn=>{callback=fn;return 1};try{let captured;const pipeline=new RenderPipeline(()=>{throw new Error('frame failed')},error=>{captured=error});pipeline.request({});callback();assert.equal(captured.message,'frame failed')}finally{if(originalRaf===undefined)delete globalThis.requestAnimationFrame;else globalThis.requestAnimationFrame=originalRaf}});
test('corrupted and structurally malformed saves recover safely',()=>{const previous=globalThis.localStorage;try{globalThis.localStorage=memoryStorage({'ai-singularity-save':'{bad json'});assert.equal(new SaveSystem({}).load(),null);const malformed=createDefaultState();malformed.model={...malformed.model,activeId:'missing',owned:'invalid',deployed:'invalid',improvements:null,progress:null};malformed.hardware={calculator:-5};malformed.upgrades=null;malformed.objectives=null;malformed.world={...malformed.world,modifiers:null};malformed.meta={...malformed.meta,techNodes:null,achievements:null};globalThis.localStorage=memoryStorage({'ai-singularity-save':JSON.stringify(malformed)});const recovered=new SaveSystem({}).load();assert(recovered);assert.deepEqual(recovered.model.owned,['tinyChat']);assert.deepEqual(recovered.model.deployed,['tinyChat']);assert.equal(recovered.model.activeId,'tinyChat');assert.equal(recovered.hardware.calculator,0);assert.deepEqual(recovered.upgrades,[]);assert.deepEqual(recovered.objectives,{});assert.deepEqual(recovered.world.modifiers,[]);assert.deepEqual(recovered.meta.techNodes,[])}finally{if(previous===undefined)delete globalThis.localStorage;else globalThis.localStorage=previous}});


test('canonical state and economy contracts hydrate undefined and pre-item states',()=>{const fallback=createDefaultEconomySnapshot();const snapshot=economySnapshot(undefined);assert.deepEqual(Object.keys(snapshot),Object.keys(fallback));assert(Object.values(snapshot).every(value=>value===null||typeof value==='string'||Number.isFinite(value)));assert.equal(computePerSecond(undefined),0);const legacy=createDefaultState();delete legacy.inventory;delete legacy.artifacts;delete legacy.rewardedBoosts;const hydrated=ensureGameState(legacy);assert(isCompleteGameState(hydrated));assert.equal(economySnapshot(hydrated).computePerSecond,0)});

test('all startup transitions render with complete state and finite economy values',()=>{const scenarios=[];const fresh=createDefaultState();scenarios.push(['fresh',fresh]);const legacy={...fresh,version:8};delete legacy.inventory;delete legacy.artifacts;delete legacy.offline;delete legacy.rewards;scenarios.push(['migrated',legacy]);const reset=createDefaultState();scenarios.push(['reset',reset]);let eligible={...fresh,run:{...fresh.run,computeProduced:1_000_000}};eligible=startDevelopmentCycle(eligible);scenarios.push(['development-cycle',eligible]);const offline={...fresh,hardware:{...fresh.hardware,calculator:2},offline:{...fresh.offline,lastActiveTimestamp:1_000}};scenarios.push(['offline-return',reconcileOffline(offline,61_000)]);for(const [name,candidate] of scenarios){const state=ensureGameState(candidate),root=new MockRoot(),shell=new AppShell(root,new EventBus());assert.doesNotThrow(()=>shell.mount(state),name);assert.match(root.querySelector('[data-workspace]').innerHTML,/COMMAND CENTER/,name);const economy=economySnapshot(state);assert(Number.isFinite(economy.computePerSecond),name);assert(Number.isFinite(economy.creditsPerSecond),name)}});

test('browser reload starts twice from the persisted migrated state without an exception',()=>{const storage=memoryStorage(),firstRestore=installBrowser('',storage);try{const firstRoot=new MockRoot(),first=new Application(firstRoot);first.start();first.stop()}finally{firstRestore()}const secondRestore=installBrowser('',storage);try{const secondRoot=new MockRoot(),errors=[],second=new Application(secondRoot,{onRuntimeError:error=>errors.push(error)});second.start();assert.match(secondRoot.querySelector('[data-workspace]').innerHTML,/COMMAND CENTER/);assert.deepEqual(errors,[]);second.stop()}finally{secondRestore()}});

test('developer mode starts from a legacy save missing economy-adjacent systems',()=>{const legacy=createDefaultState();legacy.version=8;delete legacy.inventory;delete legacy.artifacts;delete legacy.rewards;delete legacy.offline;const storage=memoryStorage({'ai-singularity-save':JSON.stringify(legacy)}),restore=installBrowser('?dev=1',storage);try{const root=new MockRoot(),errors=[],application=new Application(root,{onRuntimeError:error=>errors.push(error)});application.start();assert.match(root.querySelector('[data-workspace]').innerHTML,/COMMAND CENTER/);assert.deepEqual(errors,[]);application.stop()}finally{restore()}});

test('developer validation fails fast without repairing malformed runtime state',()=>{const invalid=createDefaultState();delete invalid.inventory;assert.throws(()=>validateGameState(invalid,economySnapshot(createDefaultState())),/inventory or equipped items are missing/);const invalidEconomy={...createDefaultEconomySnapshot(),computePerSecond:NaN};assert.throws(()=>validateGameState(createDefaultState(),invalidEconomy),/economy snapshot contains NaN/)});

test('offline Continue owns input, dismisses the reward, and restores gameplay',()=>{let state=createDefaultState();state={...state,world:{...state.world,activeEvent:{id:'queued-world',title:'Queued event',description:'waits',choices:[]}}};state=enqueueReward(state,{category:'offline',title:'WELCOME BACK',lines:[{key:'Credits',value:10}],metadata:{effectiveDurationMs:60_000,durationMs:60_000}});const root=new MockRoot(),bus=new EventBus(),shell=new AppShell(root,bus);bus.on('reward:dismiss',id=>{state=dismissReward(state,id);shell.render(state)});shell.mount(state);assert.match(root.querySelector('[data-reward-queue]').innerHTML,/CONTINUE/);assert.equal(root.querySelector('[data-world-event]').innerHTML,'');assert.equal(root.querySelector('[data-patent-popup]').innerHTML,'');assert.equal(root.querySelector('[data-item-popup]').innerHTML,'');const rewardHost=root.querySelector('[data-reward-queue]'),writesBeforeStableRender=rewardHost.innerHTMLWrites;shell.render(state);shell.render(state);assert.equal(rewardHost.innerHTMLWrites,writesBeforeStableRender,'active reward DOM must remain stable between pointer down and click');assert.match(rewardHost.innerHTML,/type="button"/);const button={dataset:{rewardDismiss:'reward-1'},disabled:false,closest(selector){return selector==='[data-reward-dismiss]'?this:null}};root.dispatch('click',{target:button});assert.equal(state.rewards.queue.length,0);assert.equal(state.offline.rewardPending,false);assert.equal(root.querySelector('[data-reward-queue]').innerHTML,'');assert.match(root.querySelector('[data-world-event]').innerHTML,/Queued event/)});

test('startup remains compatible when structuredClone and Web Animations are unavailable',()=>{const original=globalThis.structuredClone;try{delete globalThis.structuredClone;const source=createDefaultState(),copy=cloneState(source);assert.deepEqual(copy,source);assert.notEqual(copy,source);assert.doesNotThrow(()=>animateElement({},[],{}));const restore=installBrowser('');try{const root=new MockRoot(),application=new Application(root);application.start();assert.match(root.querySelector('[data-workspace]').innerHTML,/COMMAND CENTER/);application.stop()}finally{restore()}}finally{if(original!==undefined)globalThis.structuredClone=original}});

test('HTML provides a visible pre-module startup fallback instead of a white page',()=>{const html=readFileSync(new URL('../index.html',import.meta.url),'utf8');assert.match(html,/INITIALIZING COMPANY SYSTEMS/);assert.match(html,/boot-error/);assert.match(html,/window\.addEventListener\('error'/)});

test('Save migration module has one unambiguous system-Tech migration declaration',()=>{const source=readFileSync(new URL('../src/systems/PersistentSaveSystem.js',import.meta.url),'utf8');assert.equal((source.match(/function migrateLegacySystemTechnologyNodes\s*\(/g)??[]).length,1);assert.equal((source.match(/function migrateSystemTech\s*\(/g)??[]).length,0);assert.equal((source.match(/function asObject\s*\(/g)??[]).length,0)});

class LifecycleRoot extends MockRoot {
  querySelector(selector) {
    if (selector === '[data-missions-list]' && !this.querySelector('[data-workspace]').innerHTML.includes('data-missions-list')) return null;
    return super.querySelector(selector);
  }
}
function renderView(shell,state,view){const next={...state,ui:{...state.ui,activeView:view}};assert.doesNotThrow(()=>shell.render(next),view);return next}
test('AppShell lifecycle keeps a valid view host across Runtime Inspector navigation',()=>{const root=new LifecycleRoot(),shell=new AppShell(root,new EventBus(),{devMode:true,telemetry:{}});let state=createDefaultState();shell.mount(state);for(const view of ['runtime','dashboard','developer','runtime','dashboard','runtime'])state=renderView(shell,state,view);assert.match(root.querySelector('[data-workspace]').innerHTML,/RUNTIME INSPECTOR/)});
test('Development Cycle and offline return can navigate without a missing view host',()=>{const root=new LifecycleRoot(),shell=new AppShell(root,new EventBus(),{devMode:true,telemetry:{}});let state=createDefaultState();shell.mount(state);state={...state,meta:{...state.meta,cycles:1},ui:{...state.ui,activeView:'strategy'}};shell.render(state);state=startDevelopmentCycle({...state,run:{...state.run,computeProduced:1e12,creditsEarned:1e9},hardware:{...state.hardware,gpuServer:1},model:{...state.model,level:9}});state=renderView(shell,state,'runtime');state=reconcileOffline({...state,offline:{...state.offline,lastActiveTimestamp:1_000}},61_000);state=renderView(shell,state,'dashboard');assert.match(root.querySelector('[data-workspace]').innerHTML,/COMMAND CENTER/)});
test('Technology roadmap renders compact selectable nodes rather than giant cards',()=>{const root=new MockRoot(),shell=new AppShell(root,new EventBus());const state={...createDefaultState(),meta:{...createDefaultState().meta,cycles:1},ui:{...createDefaultState().ui,activeView:'strategy'}};shell.mount(state);const html=root.querySelector('[data-workspace]').innerHTML;assert.equal((html.match(/tech-icon-node/g)??[]).length,TECH_NODE_COUNT);assert.match(html,/tech-connections/);assert.match(html,/data-tech-detail/)});
test('Technology graph exposes search, map controls, typed nodes, tooltips, and touch-safe detail UX',()=>{const root=new MockRoot(),shell=new AppShell(root,new EventBus());const state={...createDefaultState(),meta:{...createDefaultState().meta,cycles:1},ui:{...createDefaultState().ui,activeView:'strategy'}};shell.mount(state);const html=root.querySelector('[data-workspace]').innerHTML,css=readFileSync(new URL('../src/styles/main.css',import.meta.url),'utf8');for(const action of ['current','available','fit','reset'])assert.match(html,new RegExp(`data-tech-map-action="${action}"`));assert.match(html,/data-tech-search/);assert.match(html,/node-keystone/);assert.match(html,/node-model/);assert.match(html,/node-system/);assert.match(html,/data-tooltip/);assert.match(css,/touch-action:none/);assert.match(css,/tech-detail\{position:sticky;bottom:0/)});

test('developer navigation is controlled only by Developer Mode across gameplay progression',()=>{const ids=(state,enabled)=>navigationItemsForState(state,{includeDeveloper:enabled,developmentAvailable:false}).map(item=>item.id);let game=createDefaultState();for(const candidate of [game,{...game,meta:{...game.meta,totalIntelligence:0,intelligence:0,techNodes:[]}},{...game,meta:{...game.meta,totalIntelligence:100,intelligence:50,techNodes:['system-model-engineering']}},{...game,meta:{...game.meta,cycles:4,breakthroughs:2,techNodes:[]}}]){assert(ids(candidate,true).includes('developer'));assert(ids(candidate,true).includes('runtime'));assert(!ids(candidate,false).includes('developer'));assert(!ids(candidate,false).includes('runtime'))}const reset=createDefaultState();assert(ids(reset,true).includes('developer'));assert(ids(reset,true).includes('runtime'))});

test('developer validation enforces Model Point accounting invariant',()=>{const game=createDefaultState();game.model.progress.tinyChat={...game.model.progress.tinyChat,upgradePoints:2,totalPointsEarned:1,totalPointsSpent:0};assert.throws(()=>validateGameState(game),/Model Point accounting/)});
test('save version 17 maps removed Technology branches without losing permanent INT',()=>{const legacy=createDefaultState();legacy.version=17;legacy.meta={...legacy.meta,intelligence:77,totalIntelligence:123,techNodes:['robotics-1','robotics-2','physics-1','government-1','compute-1']};const storage=memoryStorage({'ai-singularity-save':JSON.stringify(legacy)}),previous=globalThis.localStorage;globalThis.localStorage=storage;try{const loaded=new SaveSystem({}).load();assert.equal(loaded.version,SAVE_VERSION);assert.equal(loaded.meta.intelligence,77);assert.equal(loaded.meta.totalIntelligence,123);for(const id of ['hardware-1','hardware-2','research-1','enterprise-1','compute-1'])assert(loaded.meta.techNodes.includes(id));assert(!loaded.meta.techNodes.some(id=>id.startsWith('robotics-')||id.startsWith('physics-')||id.startsWith('government-')))}finally{if(previous===undefined)delete globalThis.localStorage;else globalThis.localStorage=previous}});
test('unspent Model Points and purchased skills survive save reload',()=>{const previous=globalThis.localStorage,storage=memoryStorage();globalThis.localStorage=storage;try{let state=createDefaultState();state.hardware.calculator=1;for(let i=0;i<2;i++){state=trainModel(state);state={...state,model:{...state.model,trainingProgress:trainingRequiredForState(state)-.001}};state=tickGame(state,1000)}state=upgradeModelSkill(state,'tinyChat','quality');const store={getState:()=>state,replace(next){state=next}},save=new SaveSystem(store);assert(save.save());const loaded=new SaveSystem(store).load(),progress=loaded.model.progress.tinyChat;assert.equal(progress.availablePoints,1);assert.equal(progress.upgradePoints,1);assert.equal(progress.skills.quality,1);assert.equal(progress.totalPointsEarned,2);assert.equal(progress.totalPointsSpent,1)}finally{if(previous===undefined)delete globalThis.localStorage;else globalThis.localStorage=previous}});
test('Model view enables a basic skill immediately when Training completes without navigation',()=>{const root=new MockRoot(),bus=new EventBus(),shell=new AppShell(root,bus);let state=createDefaultState();state={...state,hardware:{...state.hardware,calculator:1},ui:{...state.ui,activeView:'model'}};bus.on('model:improve',({modelId,skillId})=>{state=upgradeModelSkill(state,modelId,skillId);shell.render(state)});shell.mount(state);state=trainModel(state);state={...state,model:{...state.model,trainingProgress:trainingRequiredForState(state)-.001}};state=tickGame(state,1000);shell.render(state);const skills=root.querySelector('[data-basic-skills]');assert.match(skills.innerHTML,/data-action="upgrade-model-skill" data-model-id="tinyChat" data-skill-id="quality"/);assert.equal(root.querySelector('[data-action="upgrade-model-skill"][data-model-id="tinyChat"][data-skill-id="quality"]').disabled,false);const button={disabled:false,dataset:{action:'upgrade-model-skill',modelId:'tinyChat',skillId:'quality'},closest(selector){return selector==='[data-action="upgrade-model-skill"]'?this:null}};const demandBefore=economySnapshot(state).demand;root.dispatch('click',{target:button});assert.equal(state.model.progress.tinyChat.availablePoints,0);assert.equal(state.model.progress.tinyChat.skills.quality,1);assert(economySnapshot(state).demand>demandBefore);assert.equal(root.querySelector('[data-skill-rank="tinyChat:quality"]').textContent,'LVL 1 → 2')});
test('explicit Model UPGRADE buttons spend two Points and reactivate after live Training',()=>{const root=new MockRoot(),bus=new EventBus(),shell=new AppShell(root,bus);let state=createDefaultState();state={...state,hardware:{...state.hardware,calculator:1},ui:{...state.ui,activeView:'model'}};for(let i=0;i<2;i++){state=trainModel(state);state={...state,model:{...state.model,trainingProgress:trainingRequiredForState(state)-.001}};state=tickGame(state,1000)}bus.on('model:improve',({modelId,skillId})=>{state=upgradeModelSkill(state,modelId,skillId);shell.render(state)});shell.mount(state);const click=skillId=>root.dispatch('click',{target:{disabled:false,dataset:{action:'upgrade-model-skill',modelId:'tinyChat',skillId},closest(selector){return selector==='[data-action="upgrade-model-skill"]'?this:null}}});click('quality');assert.equal(state.model.progress.tinyChat.availablePoints,1);assert.equal(state.model.progress.tinyChat.skills.quality,1);assert.equal(root.querySelector('[data-skill-rank="tinyChat:quality"]').textContent,'LVL 1 → 2');click('efficiency');assert.equal(state.model.progress.tinyChat.availablePoints,0);assert.equal(state.model.progress.tinyChat.skills.efficiency,1);state=trainModel(state);state={...state,model:{...state.model,trainingProgress:trainingRequiredForState(state)-.001}};state=tickGame(state,1000);shell.render(state);assert.equal(state.ui.activeView,'model');assert.equal(state.model.progress.tinyChat.availablePoints,1);assert.equal(root.querySelector('[data-action="upgrade-model-skill"][data-model-id="tinyChat"][data-skill-id="popularity"]').disabled,false)});
test('Tech Tree selection and purchase use the rendered EventBus path',()=>{const previousWindow=globalThis.window;globalThis.window={};const root=new MockRoot(),bus=new EventBus(),shell=new AppShell(root,bus);let state=createDefaultState();state={...state,hardware:{...state.hardware,calculator:1},meta:{...state.meta,cycles:1,intelligence:20,totalIntelligence:20},ui:{...state.ui,activeView:'strategy'}};bus.on('tech:select',({nodeId})=>{state={...state,ui:{...state.ui,selectedTechnologyId:nodeId}};shell.render(state)});bus.on('tech:buy',nodeId=>{state=purchaseTechnology(state,nodeId);shell.render(state)});shell.mount(state);const target=(selector,dataset)=>({disabled:false,dataset,closest(query){return query===selector?this:null}});root.dispatch('click',{target:target('[data-action="select-technology-node"][data-node-id]',{action:'select-technology-node',nodeId:'model-1'})});assert.match(root.querySelector('[data-workspace]').innerHTML,/data-selected-technology="model-1"[\s\S]*Model Engineering/);root.dispatch('click',{target:target('[data-action="select-technology-node"][data-node-id]',{action:'select-technology-node',nodeId:'compute-1'})});assert.match(root.querySelector('[data-workspace]').innerHTML,/data-selected-technology="compute-1"[\s\S]*Compute Theory/);const lifetime=state.meta.totalIntelligence,before=state.meta.intelligence;root.dispatch('click',{target:target('[data-tech-purchase]',{techPurchase:'compute-1'})});assert.equal(state.meta.intelligence,before-TECH_NODES.find(node=>node.id==='compute-1').cost);assert.equal(state.meta.totalIntelligence,lifetime);assert(state.meta.techNodes.includes('compute-1'));assert.match(root.querySelector('[data-workspace]').innerHTML,/data-selected-technology="compute-1"[\s\S]*PURCHASED/);assert.match(root.querySelector('[data-workspace]').innerHTML,/branch-compute[^>]*available[^>]*data-action="select-technology-node" data-node-id="compute-2"/);root.dispatch('click',{target:target('[data-action="select-technology-node"][data-node-id]',{action:'select-technology-node',nodeId:'consumer-1'})});assert.match(root.querySelector('[data-workspace]').innerHTML,/data-selected-technology="consumer-1"[\s\S]*Growth Analytics/);if(previousWindow===undefined)delete globalThis.window;else globalThis.window=previousWindow});
test('Marketing and permanent Technology purchases survive reload without duplicate spending',()=>{const previous=globalThis.localStorage,storage=memoryStorage();globalThis.localStorage=storage;try{let state=createDefaultState();state={...state,resources:{...state.resources,credits:1e9},meta:{...state.meta,intelligence:20,totalIntelligence:20,cycles:1}};state=buyMarketing(buyMarketing(state));state=purchaseTechnology(state,'compute-1');const available=state.meta.intelligence,lifetime=state.meta.totalIntelligence,cost=marketingCost(state),store={getState:()=>state,replace(next){state=next}};assert(new SaveSystem(store).save());const loaded=new SaveSystem(store).load();assert.equal(loaded.market.marketing,2);assert.equal(marketingCost(loaded),cost);assert(loaded.meta.techNodes.includes('compute-1'));assert.equal(loaded.meta.intelligence,available);assert.equal(loaded.meta.totalIntelligence,lifetime);assert.equal(purchaseTechnology(loaded,'compute-1'),loaded)}finally{if(previous===undefined)delete globalThis.localStorage;else globalThis.localStorage=previous}});

test('ordinary simulation ticks preserve interactive view DOM structure',()=>{const previousDocument=globalThis.document;globalThis.document={activeElement:null};try{for(const view of ['model','strategy','market','dashboard','hardware','objectives','inventory','missions']){const root=new MockRoot(),shell=new AppShell(root,new EventBus());let state=createDefaultState();state={...state,meta:{...state.meta,cycles:1,intelligence:10,totalIntelligence:10},resources:{...state.resources,credits:1e6},hardware:{...state.hardware,calculator:1},ui:{...state.ui,activeView:view,selectedTechnologyId:'compute-1'}};shell.mount(state);const workspace=root.querySelector('[data-workspace]'),writes=workspace.innerHTMLWrites;for(let index=0;index<10;index++){state=tickGame(state,100);shell.render(state,{reason:'game-loop'})}assert.equal(workspace.innerHTMLWrites,writes,`${view} replaced its workspace during ticks`);const lifecycle=shell.diagnostics().renderLifecycle;assert.equal(lifecycle.domReplacements,1,view);assert.equal(lifecycle.liveUpdates,11,view)}}finally{if(previousDocument===undefined)delete globalThis.document;else globalThis.document=previousDocument}});

test('Model skill controls are patched without replacing their container during live ticks',()=>{const root=new MockRoot(),shell=new AppShell(root,new EventBus());let state=createDefaultState();state={...state,hardware:{...state.hardware,calculator:1},ui:{...state.ui,activeView:'model'}};shell.mount(state);const skills=root.querySelector('[data-basic-skills]'),writes=skills.innerHTMLWrites;for(let index=0;index<10;index++){state=tickGame(state,100);shell.render(state,{reason:'game-loop'})}assert.equal(skills.innerHTMLWrites,writes);assert.equal(root.querySelector('[data-action="upgrade-model-skill"][data-model-id="tinyChat"][data-skill-id="quality"]').disabled,true);state={...state,model:{...state.model,progress:{...state.model.progress,tinyChat:{...state.model.progress.tinyChat,availablePoints:1,upgradePoints:1,totalPointsEarned:1}}}};shell.render(state,{reason:'game-loop'});assert.equal(skills.innerHTMLWrites,writes);assert.equal(root.querySelector('[data-action="upgrade-model-skill"][data-model-id="tinyChat"][data-skill-id="quality"]').disabled,false)});

test('locked Technology nodes remain inspectable and selection survives ticks',()=>{const root=new MockRoot(),bus=new EventBus(),shell=new AppShell(root,bus);let state=createDefaultState();state={...state,meta:{...state.meta,cycles:1},ui:{...state.ui,activeView:'strategy',selectedTechnologyId:'compute-1'}};bus.on('tech:select',({nodeId})=>{state={...state,ui:{...state.ui,selectedTechnologyId:nodeId}};shell.render(state,{reason:'tech-selection'})});shell.mount(state);const node=id=>({tagName:'path',dataset:{action:'select-technology-node',nodeId:id},closest(selector){return selector==='[data-action="select-technology-node"][data-node-id]'||selector==='[data-node-id]'||selector==='button'?this:null}});root.dispatch('click',{target:node('research-1')});assert.equal(state.ui.selectedTechnologyId,'research-1');assert.match(root.querySelector('[data-workspace]').innerHTML,/data-selected-technology="research-1"[\s\S]*Research Division/);for(let index=0;index<10;index++){state=tickGame(state,100);shell.render(state,{reason:'game-loop'})}assert.equal(state.ui.selectedTechnologyId,'research-1');root.dispatch('click',{target:node('agi-5')});assert.equal(state.ui.selectedTechnologyId,'agi-5');assert.match(root.querySelector('[data-workspace]').innerHTML,/data-selected-technology="agi-5"[\s\S]*General Intelligence/);assert.equal(root.querySelector('[data-tech-purchase="agi-5"]').disabled,true)});

test('Technology pointer movement threshold distinguishes tap from pan',()=>{const root=new MockRoot(),bus=new EventBus(),shell=new AppShell(root,bus);let state={...createDefaultState(),meta:{...createDefaultState().meta,cycles:1},ui:{...createDefaultState().ui,activeView:'strategy',selectedTechnologyId:'compute-1'}},selections=[];bus.on('tech:select',payload=>{selections.push(payload.nodeId);state={...state,ui:{...state.ui,selectedTechnologyId:payload.nodeId}};shell.render(state,{reason:'tech-selection'})});shell.mount(state);const viewport=new MockNode(),target={tagName:'svg',dataset:{nodeId:'research-1'},disabled:false,closest(selector){if(selector==='[data-tech-viewport]')return viewport;return selector.includes('select-technology-node')||selector==='[data-node-id]'||selector==='button'?this:null}};root.dispatch('pointerdown',{target,pointerId:1,clientX:10,clientY:10});root.dispatch('pointermove',{target,pointerId:1,clientX:13,clientY:12});root.dispatch('pointerup',{target,pointerId:1,clientX:13,clientY:12});assert.deepEqual(selections,['research-1']);root.dispatch('click',{target});assert.deepEqual(selections,['research-1']);root.dispatch('pointerdown',{target,pointerId:2,clientX:10,clientY:10});root.dispatch('pointermove',{target,pointerId:2,clientX:30,clientY:30});root.dispatch('pointerup',{target,pointerId:2,clientX:30,clientY:30});root.dispatch('click',{target});assert.deepEqual(selections,['research-1'])});




test('Technology gesture resolves SVG children, locked nodes, and empty-surface pans',()=>{const root=new MockRoot(),bus=new EventBus(),shell=new AppShell(root,bus);let state={...createDefaultState(),meta:{...createDefaultState().meta,cycles:1},ui:{...createDefaultState().ui,activeView:'strategy',selectedTechnologyId:'compute-1'}},selections=[];bus.on('tech:select',payload=>{selections.push(payload.nodeId);state={...state,ui:{...state.ui,selectedTechnologyId:payload.nodeId}};shell.render(state,{reason:'tech-selection'})});shell.mount(state);const viewport=new MockNode();viewport.scrollLeft=100;viewport.scrollTop=200;viewport.setPointerCapture=()=>{};const node={tagName:'BUTTON',dataset:{nodeId:'agi-5'},closest(selector){if(selector==='[data-tech-viewport]')return viewport;if(selector.includes('select-technology-node'))return this;return null}};const svgChild={tagName:'path',className:{baseVal:'game-icon-path'},closest(selector){if(selector==='[data-tech-viewport]')return viewport;if(selector.includes('select-technology-node'))return node;return null}};root.dispatch('pointerdown',{target:svgChild,pointerId:11,clientX:40,clientY:40});root.dispatch('pointerup',{target:svgChild,pointerId:11,clientX:40,clientY:40});assert.deepEqual(selections,['agi-5']);assert.equal(state.ui.selectedTechnologyId,'agi-5');assert.match(root.querySelector('[data-workspace]').innerHTML,/data-selected-technology="agi-5"[\s\S]*General Intelligence/);root.dispatch('pointerdown',{target:svgChild,pointerId:12,clientX:40,clientY:40});root.dispatch('pointermove',{target:svgChild,pointerId:12,clientX:70,clientY:40});root.dispatch('pointerup',{target:svgChild,pointerId:12,clientX:70,clientY:40});assert.deepEqual(selections,['agi-5']);assert.equal(viewport.scrollLeft,70);const empty={tagName:'DIV',closest(selector){return selector==='[data-tech-viewport]'?viewport:null}};root.dispatch('pointerdown',{target:empty,pointerId:13,clientX:50,clientY:50});root.dispatch('pointermove',{target:empty,pointerId:13,clientX:80,clientY:90});root.dispatch('pointerup',{target:empty,pointerId:13,clientX:80,clientY:90});assert.equal(viewport.scrollLeft,40);assert.equal(viewport.scrollTop,160)});

test('Technology hit-test diagnostics report physical-equivalent node resolution',()=>{const previousDocument=globalThis.document;const root=new MockRoot(),bus=new EventBus(),shell=new AppShell(root,bus,{devMode:false});let state={...createDefaultState(),meta:{...createDefaultState().meta,cycles:1},ui:{...createDefaultState().ui,activeView:'strategy'}};bus.on('tech:select',({nodeId})=>{state={...state,ui:{...state.ui,selectedTechnologyId:nodeId}};shell.render(state)});const viewport=new MockNode(),node={tagName:'BUTTON',className:'tech-icon-node locked',dataset:{nodeId:'research-1'},closest(selector){if(selector==='[data-tech-viewport]')return viewport;if(selector.includes('select-technology-node'))return this;return null}};try{globalThis.document={elementFromPoint:()=>node,elementsFromPoint:()=>[node,viewport]};shell.mount(state);root.dispatch('pointerdown',{target:node,pointerId:20,clientX:10,clientY:20});root.dispatch('pointerup',{target:node,pointerId:20,clientX:12,clientY:21});const hit=shell.diagnostics().techHitTest;assert.equal(hit.resolvedNodeId,'research-1');assert.equal(hit.selectionSucceeded,true);assert.equal(hit.elementFromPoint,'button.tech-icon-node.locked');assert.equal(hit.pointerTravelPx,Math.hypot(2,1))}finally{if(previousDocument===undefined)delete globalThis.document;else globalThis.document=previousDocument}});

test('Technology graph CSS keeps decorative layers inert and node targets mobile-sized',()=>{const css=readFileSync(new URL('../src/styles/main.css',import.meta.url),'utf8');assert.match(css,/\.tech-connections\{[^}]*z-index:0[^}]*pointer-events:none/);assert.match(css,/\.tech-connections line\{pointer-events:none/);assert.match(css,/\.tech-icon-node\{[^}]*z-index:2[^}]*width:58px[^}]*min-width:58px[^}]*pointer-events:auto/);assert.match(css,/\.tech-map-viewport\{[^}]*touch-action:none/)});
test('Technology selectors are valid, escaped, and resolve every representative node ID',()=>{const ids=['compute-1','research-1','agi-5','singularity-7','training-7','future node\"unsafe'];for(const id of ids){const selector=technologyNodeSelector(id);assert.match(selector,/^\[data-action="select-technology-node"\]\[data-node-id=".*"\]$/);assert.doesNotMatch(selector,/select-technology-node" data-node-id/);let received;const sentinel={},root={querySelector(value){received=value;return sentinel}};assert.equal(findTechnologyNode(root,id),sentinel);assert.equal(received,selector)}assert.match(technologyNodeSelector('future node"unsafe'),/\\20 |\\22 /)});

test('Technology view opens and live-updates representative selections without malformed selectors',()=>{class StrictRoot extends MockRoot{querySelector(selector){if(/\[data-action=[^\]]+ data-node-id=/u.test(selector))throw new SyntaxError(`Invalid selector: ${selector}`);return super.querySelector(selector)}}const ids=['compute-1','research-1','agi-5','singularity-7','training-7'];for(const id of ids){const root=new StrictRoot(),shell=new AppShell(root,new EventBus());let game=createDefaultState();game={...game,meta:{...game.meta,cycles:1},ui:{...game.ui,activeView:'strategy',selectedTechnologyId:id}};assert.doesNotThrow(()=>shell.mount(game),id);assert.doesNotThrow(()=>shell.render(tickGame(game,100),{reason:'game-loop'}),id);assert.match(root.querySelector('[data-workspace]').innerHTML,new RegExp(`data-selected-technology="${id}"`))}});

test('purchased Compute Theory reopens as purchased without spending Lifetime INT',()=>{const root=new MockRoot(),shell=new AppShell(root,new EventBus());let game=createDefaultState();game={...game,meta:{...game.meta,cycles:1,intelligence:0,totalIntelligence:2,techNodes:['compute-1']},ui:{...game.ui,activeView:'strategy',selectedTechnologyId:'compute-1'}};shell.mount(game);const button=root.querySelector('[data-tech-purchase="compute-1"]');assert.equal(button.disabled,true);assert.equal(button.textContent,'PURCHASED');assert.equal(game.meta.intelligence,0);assert.equal(game.meta.totalIntelligence,2);assert.match(root.querySelector('[data-workspace]').innerHTML,/data-node-id="compute-2"/) });

test('Research Technology mounts the real Research interface and Model view has no advanced specialization UI',()=>{const researchRoot=new MockRoot(),researchShell=new AppShell(researchRoot,new EventBus());let state=createDefaultState();state={...state,meta:{...state.meta,cycles:1,techNodes:['research-1']},ui:{...state.ui,activeView:'research'}};researchShell.mount(state);assert.match(researchRoot.querySelector('[data-workspace]').innerHTML,/RESEARCH DIVISION/);assert.match(researchRoot.querySelector('[data-workspace]').innerHTML,/data-research-stored/);const modelRoot=new MockRoot(),modelShell=new AppShell(modelRoot,new EventBus());modelShell.mount({...state,ui:{...state.ui,activeView:'model'}});const html=modelRoot.querySelector('[data-workspace]').innerHTML;assert.doesNotMatch(html,/ADVANCED SPECIALIZATIONS/);for(const skill of ['quality','efficiency','popularity'])assert.match(html,new RegExp(`data-skill-id="${skill}"`))});

test('Research tutorial, navigation, route, and allocation appear together after live Tech purchase',()=>{const root=new MockRoot(),bus=new EventBus(),shell=new AppShell(root,bus);let state={...createDefaultState(),tutorial:{step:11,completed:false,acknowledged:[]},meta:{...createDefaultState().meta,cycles:1,intelligence:10,totalIntelligence:10},ui:{...createDefaultState().ui,activeView:'allocation'}};bus.on('tutorial:advance',()=>{state=advanceTutorial(state);shell.render(state,{reason:'tutorial'})});shell.mount(state);assert.doesNotMatch(root.querySelector('[data-navigation]').innerHTML,/Research/);assert.equal(root.querySelector('[data-tutorial]').innerHTML,'');assert.doesNotMatch(root.querySelector('[data-workspace]').innerHTML,/data-allocation="research"/);state=purchaseTechnology(state,'research-1');shell.render(state,{reason:'tech'});assert.match(root.querySelector('[data-navigation]').innerHTML,/Research/);assert.match(root.querySelector('[data-tutorial]').innerHTML,/OPEN RESEARCH/);assert.match(root.querySelector('[data-workspace]').innerHTML,/data-allocation="research"/);root.dispatch('click',{target:{dataset:{action:'tutorial'},closest(selector){return selector==='[data-action]'?this:null}}});assert.equal(state.ui.activeView,'research');assert.match(root.querySelector('[data-workspace]').innerHTML,/RESEARCH DIVISION/);for(let index=0;index<10;index++){state=tickGame(state,100);shell.render(state,{reason:'game-loop'})}assert.match(root.querySelector('[data-navigation]').innerHTML,/Research/);assert.match(root.querySelector('[data-workspace]').innerHTML,/RESEARCH DIVISION/)});
