import assert from 'node:assert/strict';
import test from 'node:test';
import { BALANCE, isResearchUnlocked } from '../src/config/balance.js';
import { createDefaultState, HARDWARE_CATALOG, OBJECTIVES } from '../src/data/defaultState.js';
import { TelemetryService } from '../src/dev/telemetry-service.js';
import { buyHardware, buyHardwareBulk, effectiveHardwareCost, hardwareBulkCost, startDevelopmentCycle } from '../src/systems/GameSystem.js';
import { earnGems, spendGems } from '../src/systems/GemSystem.js';

function cycleReady(state){return{...state,hardware:{...state.hardware,miniDatacenter:1},model:{...state.model,level:9,progress:{...state.model.progress,tinyChat:{...state.model.progress.tinyChat,level:9}}},objectives:Object.fromEntries(OBJECTIVES.slice(0,6).map(item=>[item.id,true])),run:{...state.run,creditsEarned:BALANCE.intelligence.creditScale,computeProduced:BALANCE.intelligence.computeScale}}}

test('one canonical telemetry Run is created for each actual Development Cycle',()=>{let now=1_000,state=cycleReady(createDefaultState());const telemetry=new TelemetryService({clock:()=>now,storage:null});telemetry.start(state);for(let cycle=0;cycle<2;cycle++){const next=startDevelopmentCycle(state);now+=1_000;telemetry.observe(state,next,'development-cycle');state=cycleReady(next)}const report=telemetry.prepareExport(state),starts=report.events.filter(event=>event.type==='run-started'),ends=report.events.filter(event=>event.type==='run-ended');assert.equal(starts.length,3);assert.equal(ends.length,2);assert.equal(new Set(starts.map(event=>event.runId)).size,3);assert.equal(report.summary.runs.length,3)});

test('bulk Hardware quote equals sequential canonical purchases and MAX is exact',()=>{let state={...createDefaultState(),resources:{...createDefaultState().resources,credits:1_000_000}};const quote=hardwareBulkCost(state,'calculator',25),bulk=buyHardwareBulk(state,'calculator',25,'x25');let sequential=state;for(let i=0;i<25;i++)sequential=buyHardware(sequential,'calculator');assert.equal(bulk.hardware.calculator,25);assert.equal(quote.totalCost,state.resources.credits-bulk.resources.credits);assert.equal(bulk.resources.credits,sequential.resources.credits);const maxQuote=hardwareBulkCost(state,'calculator','max'),max=buyHardwareBulk(state,'calculator','max','MAX');assert.equal(max.hardware.calculator,maxQuote.quantity);assert(max.resources.credits<effectiveHardwareCost(max,HARDWARE_CATALOG[0]))});

test('Research requires a completed Cycle and Research entry Tech while legacy evidence survives',()=>{const base=createDefaultState(),cycle={...base,meta:{...base.meta,cycles:1}};assert.equal(isResearchUnlocked(cycle),false);assert.equal(isResearchUnlocked({...cycle,meta:{...cycle.meta,techNodes:['research-1']}}),true);assert.equal(isResearchUnlocked({...base,resources:{...base.resources,research:5}}),true)});

test('session Gem accounting includes starting balance and highest Hardware reached survives reset',()=>{let now=1_000,state={...createDefaultState(),resources:{...createDefaultState().resources,gems:10},hardware:{...createDefaultState().hardware,hyperscaleDatacenter:1}};const telemetry=new TelemetryService({clock:()=>now,storage:null});telemetry.start(state);let next=earnGems(state,4,'daily-mission');now+=1_000;telemetry.observe(state,next,'mission');state=next;next=spendGems(state,3,'boost');now+=1_000;telemetry.observe(state,next,'gems-spent');state=next;next={...state,hardware:Object.fromEntries(HARDWARE_CATALOG.map(item=>[item.id,0]))};now+=1_000;telemetry.observe(state,next,'development-cycle');const summary=telemetry.prepareExport(next).summary;assert.equal(summary.gems.startingGemBalance,10);assert.equal(summary.gems.sessionGemsEarned,4);assert.equal(summary.gems.sessionGemsSpent,3);assert.equal(summary.gems.endingGemBalance,11);assert(summary.gems.invariantValid);assert.equal(summary.hardware.highestTierReachedSession,7);assert.equal(summary.hardware.currentHighestOwnedTier,0)});
