import test from 'node:test';
import assert from 'node:assert/strict';
import { createDefaultState, MODEL_CATALOG, PATENTS, TECH_NODES } from '../src/data/defaultState.js';
import { TECHNOLOGY_BRANCHES, hasTechnologyMechanic, technologyEffect } from '../src/data/technologyCatalog.js';
import { buyTechNode, computePerSecond, effectiveHardwareOutput, marketMetrics, optimizeGain, patentResearchPerSecond, revenuePerUser, tickGame, trainModel, trainingEtaSeconds } from '../src/systems/GameSystem.js';
import { acquireItem, equipItem } from '../src/systems/InventorySystem.js';
import { modifierValue, inferCompanyBuild } from '../src/systems/ModifierSystem.js';
import { icon } from '../src/ui/icons.js';

const rich=()=>{const state=createDefaultState();state.meta={...state.meta,intelligence:1e60,totalIntelligence:1e60};state.resources={...state.resources,credits:1e30};state.hardware={...state.hardware,calculator:50,gamingPc:20,gpuServer:10};state.model={...state.model,level:10,progress:{...state.model.progress,tinyChat:{...state.model.progress.tinyChat,level:10,upgradePoints:20,totalPointsEarned:20}}};return state};
const buyPath=(state,branch,rank)=>{let next=state;for(let index=1;index<=rank;index++)next=buyTechNode(next,`${branch}-${index}`);return next};

test('Technology catalog contains 119 meaningful nodes across 17 strategic branches',()=>{assert.equal(TECH_NODES.length,119);assert.equal(Object.keys(TECHNOLOGY_BRANCHES).length,17);assert(TECH_NODES.every(node=>node.description&&node.effect&&node.type&&node.icon));assert(TECH_NODES.filter(node=>node.type==='minor').length>=20);assert(TECH_NODES.filter(node=>node.type==='keystone').length>=15);assert(TECH_NODES.filter(node=>node.type==='keystone').length<=25)});
test('Technology graph has unique IDs, valid prerequisites, positions, icons, and no cycles',()=>{assert.equal(new Set(TECH_NODES.map(node=>node.id)).size,TECH_NODES.length);const ids=new Set(TECH_NODES.map(node=>node.id));for(const node of TECH_NODES){assert(!node.requires||ids.has(node.requires));assert(Number.isFinite(node.position.x)&&Number.isFinite(node.position.y));assert.match(icon(node.icon,node.name),/<svg/);const visited=new Set();let cursor=node;while(cursor?.requires){assert(!visited.has(cursor.id));visited.add(cursor.id);cursor=TECH_NODES.find(item=>item.id===cursor.requires)}}});
test('major, Keystone, Model, System, and Era nodes are reachable with finite entitlement-calibrated costs',()=>{for(const type of ['major','keystone','model','system','era'])assert(TECH_NODES.some(node=>node.type===type));assert.equal(Math.min(...TECH_NODES.map(node=>node.cost)),1);assert(Math.max(...TECH_NODES.map(node=>node.cost))<1e18);assert(TECH_NODES.every(node=>Number.isFinite(node.cost)&&(!node.requires||TECH_NODES.find(parent=>parent.id===node.requires).rank<node.rank)));});
test('spending INT applies a Technology exactly once without reducing Lifetime INT',()=>{let state=rich(),before=state.meta.totalIntelligence;state=buyTechNode(state,'compute-1');const after=state.meta.intelligence;assert.equal(after,1e60-1);assert.equal(state.meta.totalIntelligence,before);assert.equal(buyTechNode(state,'compute-1'),state);assert.equal(state.meta.intelligence,after);assert.equal(technologyEffect(state,'hardwareOutput'),.85)});
test('Model and system unlock nodes activate canonical progression',()=>{let state=rich();state=buyPath(state,'model',3);assert(state.model.owned.includes('smartChat'));assert(state.model.owned.includes('gptClass'));assert(state.model.owned.includes('omni'));state=buyPath(state,'research',1);assert(hasTechnologyMechanic(state,'research')||state.meta.techNodes.includes('research-1'));state=buyPath(state,'patent',1);assert(state.meta.techNodes.includes('patent-1'));state=buyPath(state,'automation',3);assert(hasTechnologyMechanic(state,'smart-allocation'));assert(hasTechnologyMechanic(state,'auto-training'));assert(hasTechnologyMechanic(state,'auto-buy'));assert(MODEL_CATALOG.every(model=>!model.unlockTech||typeof model.unlockTech==='string')||state.model.owned.length>1)});
test('Compute, Training, Consumer, Enterprise, and Research paths alter distinct canonical outputs',()=>{const base=rich(),compute=buyPath(rich(),'compute',2),training=buyPath(rich(),'training',1),consumer=buyPath(rich(),'consumer',2),enterprise=buyPath(rich(),'enterprise',2),research=buyPath({...rich(),allocation:{training:20,inference:20,research:60,data:0,agents:0}},'research',3);assert(computePerSecond(compute)>computePerSecond(base));assert(trainingEtaSeconds(trainModel(training))<trainingEtaSeconds(trainModel(base)));assert(marketMetrics(consumer).demand>marketMetrics(base).demand);assert(revenuePerUser(enterprise)>revenuePerUser(base));assert(patentResearchPerSecond(buyPath(research,'patent',1))>0)});
test('Keystone strengths and tradeoffs both change live economy',()=>{const base=rich(),computeEmpire=buyPath(rich(),'compute',6),allIn=buyPath(rich(),'training',6),viral=buyPath(rich(),'consumer',6),enterprise=buyPath(rich(),'enterprise',6);assert(computePerSecond(computeEmpire)>computePerSecond(base)*1.5);const computeWithout=marketMetrics({...computeEmpire,meta:{...computeEmpire.meta,techNodes:computeEmpire.meta.techNodes.filter(id=>id!=='compute-6')}}),computeWith=marketMetrics(computeEmpire);assert(computeWith.demand/computeWith.capacity<computeWithout.demand/computeWithout.capacity);assert(trainingEtaSeconds(trainModel(allIn))<trainingEtaSeconds(trainModel(base)));assert(marketMetrics(allIn).capacity<marketMetrics({...allIn,meta:{...allIn.meta,techNodes:allIn.meta.techNodes.filter(id=>id!=='training-6')}}).capacity);assert(marketMetrics(viral).demand>marketMetrics(base).demand);assert(revenuePerUser(viral)<revenuePerUser({...viral,meta:{...viral.meta,techNodes:viral.meta.techNodes.filter(id=>id!=='consumer-6')}}));assert(revenuePerUser(enterprise)>revenuePerUser(base)*1.5)});
test('Hardware Mastery is hidden in Technology and changes tier output without micro-upgrades',()=>{const base=rich(),mastered=buyPath(rich(),'hardware',4),item={...base.hardware};assert.equal(base.hardwareUpgradeLevels,undefined);assert(effectiveHardwareOutput(mastered,{id:'calculator',computePerSecond:.5,tier:0,milestones:[]})>effectiveHardwareOutput({...base,hardware:item},{id:'calculator',computePerSecond:.5,tier:0,milestones:[]}))});
test('Tech combines with Model skills, Patents, Items, and active play',()=>{let skilled=buyPath(rich(),'training',7);const baseTap=optimizeGain(rich()),activeTap=optimizeGain({...buyPath(rich(),'training',4),model:{...rich().model,trainingActive:true}});assert(activeTap>baseTap);assert(technologyEffect(skilled,'modelSkillPower')>0);let patent=buyPath(rich(),'patent',3);patent={...patent,patents:{...patent.patents,discovered:[PATENTS[0].id],equipped:[PATENTS[0].id]}};assert(computePerSecond(patent)>computePerSecond({...patent,meta:{...patent.meta,techNodes:patent.meta.techNodes.filter(id=>id!=='patent-3')}}));let items=buyPath(rich(),'items',3);items=acquireItem(items,'sparse-transformer');const instance=items.inventory.instances[0];items=equipItem(items,instance.instanceId,'tinyChat');assert(modifierValue(items,'research','tinyChat')>modifierValue({...items,meta:{...items.meta,techNodes:items.meta.techNodes.filter(id=>id!=='items-3')}},'research','tinyChat'))});
test('Automation path performs passive decisions and build identities emerge from investment',()=>{let automated=buyPath(rich(),'automation',3);automated={...automated,model:{...automated.model,trainingActive:false}};automated=tickGame(automated,1000);assert(automated.model.trainingActive||automated.model.trainingProgress>0);const builds=['compute','consumer','enterprise','research','agent'].map(branch=>inferCompanyBuild(buyPath(rich(),branch,6)));assert(new Set(builds).size>=4)});
