import { BALANCE, featureUnlocked } from '../config/balance.js';
import { ITEM_CATALOG } from '../data/itemCatalog.js';
import { CONSUMABLES, GEM_CONVENIENCE, REWARD_CACHES } from '../data/metaCatalog.js';

export function acquireItem(state,catalogId,source='gameplay',now=Date.now(),{bypassUnlock=false}={}){
  const item=ITEM_CATALOG.find(entry=>entry.id===catalogId);if(!item||(!bypassUnlock&&!featureUnlocked(state,'items'))||state.inventory.instances.length>=inventoryCapacity(state))return state;
  const sequence=state.inventory.nextInstanceId;const instance={instanceId:`item-${sequence}`,catalogId,ownerId:state.profile.localOwnerId??'local',equippedModelId:null,locked:false,favorite:false,acquiredAt:now,source,seed:sequence,qualityRoll:1,affixRolls:[],tradeable:item.tradeable,bound:item.bound};
  return{...state,inventory:{...state.inventory,nextInstanceId:sequence+1,instances:[...state.inventory.instances,instance],collection:{...state.inventory.collection,items:[...new Set([...state.inventory.collection.items,catalogId])],rarities:[...new Set([...state.inventory.collection.rarities,item.rarity])],sets:item.setId?[...new Set([...state.inventory.collection.sets,item.setId])]:state.inventory.collection.sets},newItem:instance},statistics:{...state.statistics,totalItemsAcquired:state.statistics.totalItemsAcquired+1}};
}
export function equipItem(state,instanceId,modelId){const instance=state.inventory.instances.find(item=>item.instanceId===instanceId),item=ITEM_CATALOG.find(entry=>entry.id===instance?.catalogId);if(!instance||!item||!state.model.owned.includes(modelId)||!availableSlots(state,modelId).includes(item.slotType))return state;const previous=state.inventory.equipped[modelId]?.[item.slotType]??null;const equipped={...state.inventory.equipped,[modelId]:{...(state.inventory.equipped[modelId]??{}),[item.slotType]:instanceId}};const instances=state.inventory.instances.map(entry=>entry.instanceId===instanceId?{...entry,equippedModelId:modelId}:entry.instanceId===previous?{...entry,equippedModelId:null}:entry);return{...state,inventory:{...state.inventory,equipped,instances,newItem:null}}}
export function unequipItem(state,modelId,slotType){const id=state.inventory.equipped[modelId]?.[slotType];if(!id)return state;const modelEquipment={...(state.inventory.equipped[modelId]??{})};delete modelEquipment[slotType];return{...state,inventory:{...state.inventory,equipped:{...state.inventory.equipped,[modelId]:modelEquipment},instances:state.inventory.instances.map(item=>item.instanceId===id?{...item,equippedModelId:null}:item)}}}
export function toggleItemFavorite(state,instanceId){return{...state,inventory:{...state.inventory,instances:state.inventory.instances.map(item=>item.instanceId===instanceId?{...item,favorite:!item.favorite}:item)}}}
export function availableSlots(state){const count=Math.min(BALANCE.items.maxSlots,BALANCE.items.baseSlots+(state.premium.purchases.includes('item-slot-3')?1:0)+(state.meta.techNodes.includes('model-1')?1:0));return['architecture','compute','memory','dataset','optimization','safety'].slice(0,count)}
export function inventoryCapacity(state){return BALANCE.items.inventoryCapacity+(state.premium.purchases.includes('inventory-25')?25:0)}
export function grantConsumable(state,id,amount=1){if(!CONSUMABLES.some(item=>item.id===id))return state;return{...state,consumables:{...state.consumables,[id]:(state.consumables[id]??0)+amount}}}
export function useConsumable(state,id){const item=CONSUMABLES.find(entry=>entry.id===id);if(!item||(state.consumables[id]??0)<1)return state;let next={...state,consumables:{...state.consumables,[id]:state.consumables[id]-1},gemEconomy:{...state.gemEconomy,consumablesUsed:state.gemEconomy.consumablesUsed+1}};if(item.effect==='instantCompute')next={...next,resources:{...next.resources,compute:next.resources.compute+item.value}};else if(item.effect==='instantCreditsSeconds'){const approximateRate=Math.max(.01,next.resources.users*.24*next.market.priceMultiplier);next={...next,resources:{...next.resources,credits:next.resources.credits+approximateRate*item.value}}}else if(item.effect==='patentProgress')next={...next,patents:{...next.patents,progress:next.patents.progress+Math.max(1,next.patents.progress*.25+60)*item.value}};else if(item.effect==='trainingSkip')next={...next,model:{...next.model,trainingProgress:next.model.trainingProgress+Math.max(1,next.model.trainingProgress*.25+10)*item.value}};else if(item.effect==='reputation')next={...next,market:{...next.market,reputation:next.market.reputation+item.value}};else next={...next,world:{...next.world,modifiers:[...next.world.modifiers,{effect:item.effect,value:item.value,expiresAt:next.statistics.playTimeMs+item.durationMs,source:`consumable:${id}`}]}};return next}
export function grantCache(state,id,amount=1){if(!REWARD_CACHES.some(cache=>cache.id===id))return state;return{...state,rewardCaches:{...state.rewardCaches,[id]:(state.rewardCaches[id]??0)+amount}}}
export function openCache(state,id){const cache=REWARD_CACHES.find(entry=>entry.id===id);if(!cache||(state.rewardCaches[id]??0)<1)return state;let next={...state,rewardCaches:{...state.rewardCaches,[id]:state.rewardCaches[id]-1}};if(cache.rewards.gems)next=earnGems(next,cache.rewards.gems,'cache');if(cache.rewards.compute)next={...next,resources:{...next.resources,compute:next.resources.compute+cache.rewards.compute}};if(cache.rewards.research)next={...next,resources:{...next.resources,research:next.resources.research+cache.rewards.research}};if(cache.rewards.consumable)next=grantConsumable(next,cache.rewards.consumable);if(cache.rewards.item)next=acquireItem(next,cache.rewards.item,'cache');return next}
export function earnGems(state,amount,source){return{...state,resources:{...state.resources,gems:state.resources.gems+amount},gemEconomy:{...state.gemEconomy,earned:state.gemEconomy.earned+amount,history:[...state.gemEconomy.history,{type:'earned',amount,source,at:Date.now()}].slice(-100)}}}
export function buyGemConvenience(state,id){const item=GEM_CONVENIENCE.find(entry=>entry.id===id);if(!item||state.premium.purchases.includes(id)||state.resources.gems<item.cost)return state;let next={...state,resources:{...state.resources,gems:state.resources.gems-item.cost},premium:{...state.premium,purchases:[...state.premium.purchases,id]},gemEconomy:{...state.gemEconomy,spent:state.gemEconomy.spent+item.cost,history:[...state.gemEconomy.history,{type:'spent',amount:item.cost,source:id,at:Date.now()}].slice(-100)}};if(item.durationMs)next={...next,world:{...next.world,modifiers:[...next.world.modifiers,{effect:item.effect,value:item.value,expiresAt:next.statistics.playTimeMs+item.durationMs,source:`gems:${id}`}]}};return next}
