import { BALANCE } from '../config/balance.js';

const finiteNonNegative=value=>Number.isFinite(value)?Math.max(0,value):0;

export function marketingFactor(level){return 1+BALANCE.marketV3.marketingCoefficient*Math.log1p(finiteNonNegative(level))}
export function reputationFactor(value){const p=BALANCE.marketV3.reputation,r=Number.isFinite(value)?value:p.midpoint;return p.min+(p.max-p.min)/(1+Math.exp(-p.steepness*(r-p.midpoint)))}
export function adoptionFactor(value){const p=BALANCE.marketV3.adoption,a=finiteNonNegative(value);return 1+p.maxBonus*a/(p.halfSaturation+a)}
export function wordOfMouthFactor(users){const p=BALANCE.marketV3.wordOfMouth,z=Math.log1p(finiteNonNegative(users)/p.userScale);return 1+p.maxBonus*z/(p.saturation+z)}
export function qualityDemandFactor(quality){return 1+BALANCE.marketV3.qualityDemandCoefficient*Math.log1p(finiteNonNegative(quality))}
export function popularityDemandFactor(popularity){const p=BALANCE.marketV3.popularity,value=finiteNonNegative(popularity);return 1+p.sqrtCoefficient*Math.sqrt(value)+p.logCoefficient*Math.log1p(value)}
export function priceDemandFactor(price,quality,elasticityBonus=0){const p=BALANCE.marketV3.price,value=Math.min(3,Math.max(.5,Number(price)||1));if(value<=1)return 1+p.discountDemandCoefficient*(1-value);const tolerance=Math.max(.1,1+p.qualityToleranceCoefficient*Math.sqrt(finiteNonNegative(quality))+finiteNonNegative(elasticityBonus));return Math.exp(-p.premiumElasticity*(value-1)/tolerance)}
export function acquisitionHalfLife(popularity,marketing){const p=BALANCE.marketV3.acquisition;return Math.max(p.minimumHalfLifeSeconds,p.baseHalfLifeSeconds/(1+p.popularityCoefficient*Math.sqrt(finiteNonNegative(popularity))+p.marketingCoefficient*Math.log1p(finiteNonNegative(marketing))))}
export function instantaneousUserGrowth(users,demand,popularity,marketing){const current=finiteNonNegative(users),target=finiteNonNegative(demand),halfLife=current<target?acquisitionHalfLife(popularity,marketing):BALANCE.marketV3.churnHalfLifeSeconds;return Math.log(2)/halfLife*(target-current)}
// Exact exponential convergence keeps online and offline chunk sizes equivalent.
export function advanceUsers(users,demand,deltaSeconds,popularity,marketing){const current=finiteNonNegative(users),target=finiteNonNegative(demand),seconds=finiteNonNegative(deltaSeconds);if(!seconds||current===target)return current;const halfLife=current<target?acquisitionHalfLife(popularity,marketing):BALANCE.marketV3.churnHalfLifeSeconds;return target+(current-target)*Math.exp(-Math.log(2)/halfLife*seconds)}

// Capacity must never feed Potential Demand. This prevents the V2 feedback loop.
export function potentialDemand(_state,factors){const value=factors.baseMarket*factors.modelTier*factors.modelLevel*qualityDemandFactor(factors.quality)*popularityDemandFactor(factors.popularity)*factors.infrastructure*marketingFactor(factors.marketing)*reputationFactor(factors.reputation)*adoptionFactor(factors.adoption)*wordOfMouthFactor(factors.currentUsers)*priceDemandFactor(factors.price,factors.quality,factors.priceElasticity)*factors.marketSizeModifiers*factors.demandModifiers*factors.appealModifiers;return finiteNonNegative(value)}
export function inferenceCapacity(state,totalComputePerSecond,modelEfficiency,inferenceModifiers=1){const inferenceCompute=finiteNonNegative(totalComputePerSecond)*(finiteNonNegative(state.allocation.inference)/100),capacity=inferenceCompute*finiteNonNegative(modelEfficiency)*finiteNonNegative(inferenceModifiers);return{inferenceComputePerSecond:inferenceCompute,inferenceCapacity:finiteNonNegative(capacity)}}
export function servedUsers(currentUsers,demand,capacity){return Math.min(finiteNonNegative(currentUsers),finiteNonNegative(demand),finiteNonNegative(capacity))}
export function revenueRate(served,revenuePerUser){return finiteNonNegative(served)*finiteNonNegative(revenuePerUser)}
export function marketSnapshot(state,context,users=state.resources.users){const factors={...context.factors,currentUsers:finiteNonNegative(users)},demand=potentialDemand(state,factors),capacityResult=inferenceCapacity(state,context.totalComputePerSecond,context.modelEfficiency,context.inferenceModifiers),served=servedUsers(users,demand,capacityResult.inferenceCapacity),utilization=capacityResult.inferenceCapacity?Math.min(1,served/capacityResult.inferenceCapacity):0,rpu=finiteNonNegative(context.revenuePerUser);return{potentialDemand:demand,demand,currentUsers:finiteNonNegative(users),servedUsers:served,...capacityResult,capacity:capacityResult.inferenceCapacity,utilization,revenuePerUser:rpu,revenuePerSecond:revenueRate(served,rpu),revenue:revenueRate(served,rpu),acquisitionHalfLife:acquisitionHalfLife(factors.popularity,factors.marketing),churnHalfLife:BALANCE.marketV3.churnHalfLifeSeconds,userGrowthPerSecond:instantaneousUserGrowth(users,demand,factors.popularity,factors.marketing),factors,capacityDemand:0,organicDemand:demand,target:demand,bottleneck:demand<capacityResult.inferenceCapacity?'DEMAND LIMITED':'CAPACITY LIMITED'} }
