import { BALANCE, featureUnlocked, isResearchUnlocked } from '../config/balance.js';
import { HARDWARE_CATALOG } from '../data/defaultState.js';
import { economySnapshot, grantCredits } from './GameSystem.js';
import { acquireItem, earnGems, grantCache } from './InventorySystem.js';

const PERIOD_COUNTS={daily:5,weekly:7,monthly:10};
const PERIOD_DIFFICULTY={daily:['EASY','EASY','STANDARD','STANDARD','STANDARD'],weekly:['STANDARD','STANDARD','STANDARD','HARD','HARD','HARD','HARD'],monthly:Array(10).fill('HARD')};
export const WEEKLY_TRACK=[{target:4,reward:{gems:2}},{target:8,reward:{gems:4}},{target:12,reward:{cache:'weekly-cache'}},{target:18,reward:{gems:8}}];
export const MONTHLY_TRACK=[{target:8,reward:{gems:5}},{target:16,reward:{gems:10}},{target:25,reward:{cache:'weekly-cache'}},{target:36,reward:{gems:20}}];
const CORE=()=>({ok:true,reason:'Core system available'}),FEATURE=(id,label=id)=>state=>featureUnlocked(state,id)?{ok:true,reason:`${label} unlocked`}:{ok:false,reason:`${label} locked`};
const RESEARCH=state=>isResearchUnlocked(state)?{ok:true,reason:'Research unlocked'}:{ok:false,reason:'Research locked'};
const LABS=count=>state=>{const unlocked=state.researchLabs?.unlocked??0;return unlocked>=count?{ok:true,reason:`${unlocked} Labs unlocked`}:{ok:false,reason:`requires ${count} Labs, player has ${unlocked}`}};
const CYCLES=state=>(state.meta.cycles??0)>0?{ok:true,reason:'Development Cycles available'}:{ok:false,reason:'Development Cycles unavailable'};

function definition(type,category,metric,titleTemplate,eligiblePeriods,targets,rewards,unlockCondition=CORE,options={}){return{type,category,progressSource:metric,titleTemplate,description:options.description??'',eligiblePeriods,targets,rewards,unlockCondition,unit:options.unit??'count',tiers:options.tiers??null}}
export const MISSION_CATALOG=Object.freeze([
 definition('training-completions','TRAINING','totalTrainings','Complete {target} Trainings',['daily','weekly','monthly'],{daily:[2,3,5,8],weekly:[15,30,40,50],monthly:[50,75,100,150]},'gems'),
 definition('model-levels','MODEL','totalModelLevels','Gain {target} Model Levels',['daily','weekly','monthly'],{daily:[1,2,3,5],weekly:[8,12,20,30],monthly:[25,50,75,100]},'mixed'),
 definition('improvement-points','MODEL','totalModelPointsSpent','Spend {target} Improvement Points',['daily','weekly','monthly'],{daily:[1,2,3,5],weekly:[8,15,25,40],monthly:[30,60,100,150]},'mixed'),
 definition('hardware-units','HARDWARE','totalHardwarePurchased','Buy {target} Hardware units',['daily','weekly','monthly'],{daily:[5,10,20,30],weekly:[75,150,250,400],monthly:[300,750,1500,3000]},'credits'),
 definition('hardware-tiers','HARDWARE','highestHardwareTier','Reach Hardware Tier {target}',['daily','weekly','monthly'],{daily:[1,2,3,4],weekly:[3,5,7,9],monthly:[5,8,11,14]},'mixed'),
 definition('compute-generated','COMPUTE','totalComputeProduced','Generate {target} Compute',['daily','weekly','monthly'],{daily:[1e3,1e5,1e7,1e9],weekly:[1e7,1e10,1e13,1e16],monthly:[1e10,1e14,1e18,1e22]},'credits'),
 definition('manual-compute','ACTIVE PLAY','totalManualComputeProduced','Generate {target} manual Compute',['daily','weekly','monthly'],{daily:[100,1e3,1e4,1e5],weekly:[1e4,1e5,1e6,1e8],monthly:[1e6,1e8,1e10,1e12]},'gems'),
 definition('manual-taps','ACTIVE PLAY','totalClicks','Perform {target} manual taps',['daily','weekly','monthly'],{daily:[50,100,250,500],weekly:[500,1000,2500,5000],monthly:[10000,25000,50000,100000]},'gems'),
 definition('credits-earned','ECONOMY','totalCreditsEarned','Earn {target} Credits',['daily','weekly','monthly'],{daily:[1e3,1e5,1e7,1e9],weekly:[1e7,1e10,1e13,1e16],monthly:[1e10,1e14,1e18,1e22]},'credits'),
 definition('users-served','MARKET','totalUsersServed','Serve {target} cumulative Users',['daily','weekly','monthly'],{daily:[1e3,1e5,1e7,1e9],weekly:[1e7,1e9,1e12,1e15],monthly:[1e10,1e13,1e16,1e20]},'mixed',FEATURE('market','Market')),
 definition('marketing-campaigns','MARKET','totalMarketingPurchased','Launch {target} Marketing campaigns',['daily','weekly','monthly'],{daily:[1,2,3,5],weekly:[10,20,30,40],monthly:[40,75,120,200]},'mixed',FEATURE('marketing','Marketing')),
 definition('screens-visited','EXPLORATION','pageVisits','Visit {target} company screens',['daily','weekly','monthly'],{daily:[3,4,5,6],weekly:[10,15,20,30],monthly:[30,50,75,100]},'credits'),
 definition('progression-claims','PROGRESSION','objectivesClaimed','Claim {target} permanent Progression Goals',['daily','weekly','monthly'],{daily:[1,1,2,3],weekly:[3,5,8,12],monthly:[10,20,30,50]},'gems'),
 definition('login-days','RETURN','distinctLoginDays','Play on {target} different days',['weekly','monthly'],{weekly:[3,5,6,7],monthly:[10,15,20,25]},'gems',CORE,{tiers:[1,2,3]}),
 definition('daily-missions','MISSIONS','dailyMissionsClaimed','Complete {target} Daily Missions',['weekly','monthly'],{weekly:[8,12,18,25],monthly:[25,50,75,100]},'gems'),
 definition('research-projects','RESEARCH','totalResearchProjects','Complete {target} Research projects',['daily','weekly','monthly'],{daily:[1,1,2,3],weekly:[3,5,8,12],monthly:[15,30,40,50]},'research',RESEARCH),
 definition('research-spent','RESEARCH','totalResearchPointsSpent','Spend {target} Research Points',['daily','weekly','monthly'],{daily:[100,500,2000,10000],weekly:[5000,25000,100000,500000],monthly:[1e5,1e6,1e7,1e8]},'research',RESEARCH),
 definition('lab-hours','RESEARCH','researchLabSeconds','Accumulate {target} Lab-Hours of Research',['daily','weekly','monthly'],{daily:[.25,.5,1,2],weekly:[3,6,12,24],monthly:[10,20,40,80]},'gems',RESEARCH,{unit:'lab-hours'}),
 definition('parallel-labs','RESEARCH','peakActiveLabs','Run {target} Labs simultaneously',['weekly','monthly'],{weekly:[2,2,3,3],monthly:[2,3,4,5]},'gems',LABS(2)),
 definition('technology-purchases','TECHNOLOGY','totalTechPurchased','Purchase {target} permanent Technologies',['daily','weekly','monthly'],{daily:[1,1,2,2],weekly:[2,4,6,10],monthly:[8,15,25,40]},'gems',FEATURE('strategy','Tech Tree')),
 definition('development-cycles','DEVELOPMENT','cycles','Complete {target} Development Cycles',['weekly','monthly'],{weekly:[1,1,2,2],monthly:[3,5,6,8]},'gems',CYCLES),
 definition('patent-discoveries','PATENTS','totalPatentsDiscovered','Discover {target} Patents',['weekly','monthly'],{weekly:[1,1,2,3],monthly:[2,4,6,10]},'gems',FEATURE('patents','Patents')),
 definition('items-acquired','ITEMS','totalItemsAcquired','Acquire {target} Model Items',['daily','weekly','monthly'],{daily:[1,2,3,4],weekly:[4,8,12,20],monthly:[15,30,50,75]},'mixed',FEATURE('items','Items')),
]);

export function missionPeriodIds(date=new Date()){const day=date.toISOString().slice(0,10),first=new Date(Date.UTC(date.getUTCFullYear(),0,1)),week=Math.ceil(((date-first)/86400000+first.getUTCDay()+1)/7);return{dailyPeriodId:day,weeklyPeriodId:`${date.getUTCFullYear()}-W${String(week).padStart(2,'0')}`,monthlyPeriodId:`${date.getUTCFullYear()}-${String(date.getUTCMonth()+1).padStart(2,'0')}`}}
export function missionPeriodRemaining(period,date=new Date()){let end;if(period==='daily')end=Date.UTC(date.getUTCFullYear(),date.getUTCMonth(),date.getUTCDate()+1);else if(period==='weekly'){const days=7-((date.getUTCDay()+6)%7);end=Date.UTC(date.getUTCFullYear(),date.getUTCMonth(),date.getUTCDate()+days)}else end=Date.UTC(date.getUTCFullYear(),date.getUTCMonth()+1,1);return Math.max(0,Math.floor((end-date.getTime())/1000))}
export function missionTitle(template,target){return template.replaceAll('{target}',formatTarget(target))}
export function ensureMissions(state,date=new Date()){const ids=missionPeriodIds(date),day=ids.dailyPeriodId,loginDays=[...new Set([...(state.retention.loginDays??[]),day])].slice(-400);let next={...state,retention:{...state.retention,loginDays},missions:{...state.missions,claims:state.missions.claims??{},claimHistory:state.missions.claimHistory??[],tracks:state.missions.tracks??{}}},changed=loginDays.length!==(state.retention.loginDays??[]).length;for(const period of ['daily','weekly','monthly']){const key=`${period}PeriodId`;if(next.missions[key]!==ids[key]){next={...next,missions:{...next.missions,[key]:ids[key],[period]:generatePeriod(next,period,ids[key]),generatedAt:date.getTime(),seeds:{...next.missions.seeds,[period]:seedOf(`${next.profile.localOwnerId}:${ids[key]}`)},tracks:{...next.missions.tracks,[period]:{periodId:ids[key],points:0,claimed:{}}}}};changed=true}}return changed?next:state}
export function missionsWithProgress(state,period=null){const periods=period?[period]:['daily','weekly','monthly'];return periods.flatMap(name=>(state.missions[name]??[]).map(entry=>{const normalized={...entry,progressSource:entry.progressSource??entry.metric,titleTemplate:entry.titleTemplate??entry.text??'Reach {target}'},raw=missionMetric(state,normalized),progress=Math.min(entry.target,Math.max(0,entry.periodMetric?raw:raw-(entry.baseline??0))),title=missionTitle(normalized.titleTemplate,entry.target);return{...normalized,title,text:title,progress,completed:progress>=entry.target,claimed:Boolean(state.missions.claims?.[entry.id])}}))}
export function claimMission(state,id){const mission=missionsWithProgress(state).find(entry=>entry.id===id);if(!mission||mission.claimed||!mission.completed)return state;const at=Date.now(),points=mission.difficulty==='HARD'?2:1;let next={...state,missions:{...state.missions,claims:{...state.missions.claims,[id]:at},claimHistory:[...(state.missions.claimHistory??[]),{id,period:mission.period,type:mission.type,difficulty:mission.difficulty,at,periodId:mission.periodId}].slice(-1000)},statistics:{...state.statistics,totalMissionsClaimed:(state.statistics.totalMissionsClaimed??0)+1}};next=addTrackProgress(next,mission.period,points);next=grantReward(next,mission.reward,mission.period);return updateDailyStreak(next,mission.period)}
export function claimAllMissions(state,period){return missionsWithProgress(state,period).filter(m=>m.completed&&!m.claimed).reduce((next,m)=>claimMission(next,m.id),state)}
export function claimMissionTrack(state,period,target){const milestones=period==='weekly'?WEEKLY_TRACK:period==='monthly'?MONTHLY_TRACK:[],milestone=milestones.find(item=>item.target===Number(target)),track=state.missions.tracks?.[period];if(!milestone||!track||track.points<milestone.target||track.claimed?.[milestone.target])return state;const next={...state,missions:{...state.missions,tracks:{...state.missions.tracks,[period]:{...track,claimed:{...track.claimed,[milestone.target]:Date.now()}}}}};return grantReward(next,milestone.reward,period)}
export function claimableTrackRewards(state,period){const milestones=period==='weekly'?WEEKLY_TRACK:period==='monthly'?MONTHLY_TRACK:[],track=state.missions.tracks?.[period]??{points:0,claimed:{}};return milestones.map(entry=>({...entry,claimed:Boolean(track.claimed?.[entry.target]),claimable:track.points>=entry.target&&!track.claimed?.[entry.target]}))}
export function missionDiagnostics(state){const active=Object.fromEntries(['daily','weekly','monthly'].map(period=>[period,missionsWithProgress(state,period)])),excluded=Object.fromEntries(['daily','weekly','monthly'].map(period=>[period,MISSION_CATALOG.filter(d=>d.eligiblePeriods.includes(period)).map(d=>({type:d.type,...eligibility(d,state,period,progressionBand(state))})).filter(x=>!x.ok)]));return{active,excluded,tracks:state.missions.tracks??{}}}
export function completeMissionsForDeveloper(state,period){return missionsWithProgress(state,period).reduce((next,entry)=>({...next,missions:{...next.missions,claims:{...next.missions.claims,[entry.id]:'developer-complete'}}}),state)}

function generatePeriod(state,period,periodId){const band=progressionBand(state),eligible=MISSION_CATALOG.filter(d=>d.eligiblePeriods.includes(period)&&eligibility(d,state,period,band).ok),random=seeded(seedOf(`${state.profile.localOwnerId}:${periodId}:${period}`)),ranked=eligible.map(item=>({item,score:random()})).sort((a,b)=>a.score-b.score),selected=[];for(const {item} of ranked){if(selected.length>=PERIOD_COUNTS[period])break;if(!selected.some(existing=>existing.category===item.category))selected.push(item)}for(const {item} of ranked)if(selected.length<PERIOD_COUNTS[period]&&!selected.includes(item))selected.push(item);return selected.map((entry,index)=>instantiate(state,entry,period,periodId,band,index))}
function instantiate(state,definition,period,periodId,band,index){const target=definition.targets[period][band],difficulty=PERIOD_DIFFICULTY[period][index]??'HARD',reward=rewardFor(state,definition.rewards,period,difficulty),metricEntry={progressSource:definition.progressSource,period,periodId};return{id:`${periodId}-${definition.type}`,definitionId:definition.type,type:definition.type,period,periodId,category:definition.category,target,unit:definition.unit,titleTemplate:definition.titleTemplate,description:definition.description,difficulty,tier:definition.tiers?.[Math.min(definition.tiers.length-1,band)]??null,progressSource:definition.progressSource,metric:definition.progressSource,baseline:periodMetric(definition.progressSource)?0:missionMetric(state,metricEntry),periodMetric:periodMetric(definition.progressSource),reward,unlockReason:eligibility(definition,state,period,band).reason}}
function progressionBand(state){const cycles=state.meta.cycles??0,tier=highestTier(state);return Math.min(3,cycles>=8||tier>=12?3:cycles>=3||tier>=8?2:cycles>=1||tier>=4?1:0)}
function eligibility(definition,state,period='weekly',band=progressionBand(state)){const result=definition.unlockCondition(state);if(!result.ok)return result;if(definition.type==='parallel-labs'){const target=definition.targets[period]?.[band]??2;return LABS(target)(state)}return result}
function periodMetric(metric){return ['distinctLoginDays','dailyMissionsClaimed'].includes(metric)}
function missionMetric(state,entry){const stats=state.statistics??{},progress=Object.values(state.model.progress??{}),history=state.missions.claimHistory??[];switch(entry.progressSource){case'trainings':case'totalTrainings':return stats.totalTrainings??progress.reduce((sum,p)=>sum+(p.trainingCount??p.trainings??0),0);case'modelLevels':case'totalModelLevels':return stats.totalModelLevels??Math.max(0,(state.model.level??1)-1);case'modelPointsSpent':case'totalModelPointsSpent':return stats.totalModelPointsSpent??progress.reduce((sum,p)=>sum+(p.totalPointsSpent??0),0);case'hardwareOwned':case'totalHardwarePurchased':return stats.totalHardwarePurchased??totalHardware(state);case'hardwareTier':case'highestHardwareTier':return highestTier(state)+1;case'computeProduced':case'totalComputeProduced':return stats.totalComputeProduced??0;case'totalManualComputeProduced':return stats.totalManualComputeProduced??0;case'totalClicks':return stats.totalClicks??0;case'creditsEarned':case'totalCreditsEarned':return stats.totalCreditsEarned??0;case'usersGained':case'totalUsersServed':return stats.totalUsersServed??state.resources.users;case'totalMarketingPurchased':return stats.totalMarketingPurchased??state.market.marketing;case'pageVisits':return stats.pageVisits??0;case'objectivesClaimed':return stats.objectivesClaimed??Object.values(state.objectives).filter(Boolean).length;case'distinctLoginDays':return distinctDaysInPeriod(state.retention.loginDays??[],entry.period,entry.periodId);case'dailyMissionsClaimed':return history.filter(item=>item.period==='daily'&&belongsToPeriod(item.at,entry.period,entry.periodId)).length;case'researchGained':return state.resources.research;case'totalResearchProjects':return stats.totalResearchProjects??state.researchLabs?.projectHistory?.length??0;case'totalResearchPointsSpent':return stats.totalResearchPointsSpent??state.researchLabs?.pointsSpent??0;case'researchLabSeconds':return (stats.researchLabSeconds??0)/3600;case'peakActiveLabs':return stats.peakActiveLabs??0;case'totalTechPurchased':return stats.totalTechPurchased??state.meta.techNodes.length;case'cycles':return state.meta.cycles??0;case'patents':case'totalPatentsDiscovered':return stats.totalPatentsDiscovered??state.patents.discovered.length;case'itemsAcquired':case'totalItemsAcquired':return stats.totalItemsAcquired??0;default:return 0}}
function distinctDaysInPeriod(days,period,id){return days.filter(day=>belongsToPeriod(new Date(`${day}T12:00:00Z`).getTime(),period,id)).length}
function belongsToPeriod(timestamp,period,id){const ids=missionPeriodIds(new Date(timestamp));return ids[`${period}PeriodId`]===id}
export function missionCreditReward(state,period){const clean={...state,world:{...state.world,modifiers:[]}},rate=economySnapshot(clean).creditsPerSecond,available=HARDWARE_CATALOG.filter(item=>state.hardware[item.id]>0||item.tier===0),highest=available.at(-1),importantCost=highest?highest.baseCost:Infinity,balanceCap=Math.max(BALANCE.missions.creditRewardFloor[period],state.resources.credits*BALANCE.missions.balanceCaps[period]),purchaseCap=importantCost*BALANCE.missions.nextPurchaseCaps[period],rateReward=rate*BALANCE.missions.creditRewardSeconds[period];return Math.ceil(Math.max(BALANCE.missions.creditRewardFloor[period],Math.min(rateReward,balanceCap,purchaseCap)))}
function rewardFor(state,kind,period,difficulty){const multiplier=difficulty==='HARD'?2:difficulty==='STANDARD'?1.4:1,gems=Math.max(BALANCE.missions.gems[period],Math.ceil(({daily:1,weekly:3,monthly:6}[period])*multiplier)),credits=missionCreditReward(state,period),reward={gems,credits};if(kind==='research'&&isResearchUnlocked(state))reward.research=Math.ceil(100*multiplier);return reward}
function addTrackProgress(state,claimedPeriod,points){let tracks={...state.missions.tracks};for(const period of ['weekly','monthly']){if(claimedPeriod==='monthly'&&period==='weekly')continue;const track=tracks[period];if(track)tracks={...tracks,[period]:{...track,points:(track.points??0)+points}}}return{...state,missions:{...state.missions,tracks}}}
function grantReward(state,reward,period){let next=state;if(reward.credits)next=grantCredits(next,reward.credits,`${period}-mission`);if(reward.gems)next=earnGems(next,reward.gems,`${period}-mission`);if(reward.research)next={...next,resources:{...next.resources,research:next.resources.research+reward.research}};if(reward.item)next=acquireItem(next,reward.item,'mission');if(reward.cache)next=grantCache(next,reward.cache);return next}
function updateDailyStreak(state,period){if(period!=='daily')return state;const primary=state.missions.daily??[];if(!primary.length||!primary.every(entry=>state.missions.claims[entry.id])||state.retention.lastDailyCompletionPeriod===state.missions.dailyPeriodId)return state;const previous=previousDay(state.missions.dailyPeriodId),continued=state.retention.lastDailyCompletionPeriod===previous||!state.retention.lastDailyCompletionPeriod,streak=continued?(state.retention.dailyCompletionStreak??0)+1:1;return{...state,retention:{...state.retention,dailyCompletionStreak:streak,lastDailyCompletionPeriod:state.missions.dailyPeriodId,completedDailyPeriods:(state.retention.completedDailyPeriods??0)+1}}}
function previousDay(id){const date=new Date(`${id}T00:00:00Z`);date.setUTCDate(date.getUTCDate()-1);return date.toISOString().slice(0,10)}
function highestTier(state){return HARDWARE_CATALOG.reduce((max,item)=>state.hardware[item.id]>0?Math.max(max,item.tier):max,-1)}
function totalHardware(state){return Object.values(state.hardware).reduce((a,b)=>a+b,0)}
function formatTarget(value){if(value<1)return String(value);return new Intl.NumberFormat('en-US',{maximumFractionDigits:2}).format(value)}
function seedOf(text){let value=2166136261;for(const char of text)value=Math.imul(value^char.charCodeAt(0),16777619);return value>>>0}
function seeded(seed){let value=seed||1;return()=>{value=Math.imul(1664525,value)+1013904223>>>0;return value/4294967296}}
