import { BALANCE, featureUnlocked } from '../config/balance.js';
import { tickGame } from './GameSystem.js';
import { enqueueReward } from './RewardQueue.js';
import { spendGems } from './GemSystem.js';
import { technologyEffect } from '../data/technologyCatalog.js';

export function offlineCapacityMs(state){return Math.min(BALANCE.offline.maxCapMs,(state.offline.capMs??BALANCE.offline.capMs)+technologyEffect(state,'offlineCapacity')*60*60*1000)}
export function offlineEfficiency(state){return Math.min(1,Math.max(0,state.offline.efficiency??BALANCE.offline.efficiency)+technologyEffect(state,'offlineEfficiency'))}

export function reconcileOffline(state,now=Date.now()){
  const last=Number(state.offline.lastActiveTimestamp)||now;const durationMs=Math.max(0,now-last);if(state.offline.lastReconciledTimestamp===last||durationMs<BALANCE.offline.minimumRewardMs)return stampActive(state,now);
  const capMs=offlineCapacityMs(state),effectiveDurationMs=Math.min(durationMs,capMs),efficiency=offlineEfficiency(state),rewardedDurationMs=effectiveDurationMs*efficiency;const before=offlineSnapshot(state);let next=simulateDuration(state,rewardedDurationMs);const offlineCredits=Math.max(0,(next.statistics.creditSources?.['user-revenue']??0)-(state.statistics.creditSources?.['user-revenue']??0));if(offlineCredits)next={...next,statistics:{...next.statistics,creditSources:{...next.statistics.creditSources,'user-revenue':next.statistics.creditSources['user-revenue']-offlineCredits,offline:(next.statistics.creditSources.offline??0)+offlineCredits}}};if(next.model.lastTrainingResult?.completedAt&&next.model.lastTrainingResult.completedAt!==state.model.lastTrainingResult?.completedAt)next={...next,model:{...next.model,lastTrainingResult:{...next.model.lastTrainingResult,offline:true}}};const after=offlineSnapshot(next);const results=offlineResults(before,after,state,next,durationMs,effectiveDurationMs);results.rewardedDurationMs=rewardedDurationMs;results.capMs=capMs;results.efficiency=efficiency;next={...next,offline:{...next.offline,lastActiveTimestamp:now,lastReconciledTimestamp:last,durationMs,effectiveDurationMs,rewardedDurationMs,capMs,efficiency,results,doubled:false,periods:state.offline.periods+1,totalOfflineMs:state.offline.totalOfflineMs+rewardedDurationMs}};
  const lines=Object.entries(results.gains).filter(([,value])=>value>0).map(([key,value])=>({key,value}));if(lines.length||results.milestones.length){next={...next,offline:{...next.offline,rewardPending:true}};next=enqueueReward(next,{priority:results.milestones.length?'high':'normal',category:'offline',title:'WELCOME BACK',lines,metadata:{durationMs,effectiveDurationMs,rewardedDurationMs,capMs,efficiency,milestones:results.milestones}})}return next;
}
export function doubleOfflineRewardWithGems(state){if(!state.offline.rewardPending||state.offline.doubled||!state.offline.results)return state;const paid=spendGems(state,BALANCE.offline.doubleGemCost,'offline-double');if(paid===state)return state;const gains=state.offline.results.gains??{};return{...paid,resources:{...paid.resources,credits:paid.resources.credits+(gains.credits??0),compute:paid.resources.compute+(gains.compute??0),users:paid.resources.users+(gains.users??0),research:paid.resources.research+(gains.research??0)},offline:{...paid.offline,doubled:true,doubleSource:'gems'}}}
export function simulateDuration(state,durationMs){let next=state,remaining=Math.max(0,durationMs);const chunk=durationMs<=BALANCE.offline.longThresholdMs?BALANCE.offline.shortChunkMs:BALANCE.offline.longChunkMs;while(remaining>0){const step=Math.min(chunk,remaining);next=tickGame(next,step);remaining-=step}return next}
export function stampActive(state,now=Date.now()){return{...state,offline:{...state.offline,lastActiveTimestamp:now,results:null}}}
function offlineSnapshot(state){const progress=state.model.progress?.[state.model.activeId]??{};return{credits:state.resources.credits,compute:state.resources.compute,users:state.resources.users,research:state.resources.research,modelXp:state.model.xp,modelLevel:progress.level??state.model.level,modelPoints:progress.availablePoints??0,patentProgress:state.patents.progress,patents:state.patents.discovered.length,missions:Object.keys(state.missions.claims).length}}
function offlineResults(before,after,original,next,durationMs,effectiveDurationMs){const gains={credits:Math.max(0,after.credits-before.credits),compute:Math.max(0,after.compute-before.compute),users:Math.max(0,after.users-before.users),modelXp:Math.max(0,after.modelXp-before.modelXp)};if(featureUnlocked(original,'research'))gains.research=Math.max(0,after.research-before.research);if(featureUnlocked(original,'patents'))gains.patentProgress=Math.max(0,after.patentProgress-before.patentProgress);const milestones=[];if(after.modelLevel>before.modelLevel)milestones.push(`TRAINING COMPLETED · ${next.model.lastTrainingResult?.modelId??next.model.activeId} reached Level ${after.modelLevel} · +${next.model.lastTrainingResult?.upgradePointsGained??after.modelPoints-before.modelPoints} Model Point${(next.model.lastTrainingResult?.upgradePointsGained??1)===1?'':'s'}`);if(after.patents>before.patents)milestones.push(`${after.patents-before.patents} Patent${after.patents-before.patents===1?'':'s'} discovered`);if(Object.keys(next.meta.achievements).length>Object.keys(original.meta.achievements).length)milestones.push('Achievement unlocked');return{durationMs,effectiveDurationMs,gains,milestones,startedAt:original.offline.lastActiveTimestamp,endedAt:(original.offline.lastActiveTimestamp??0)+durationMs}}
