import { BALANCE, featureUnlocked } from '../config/balance.js';
import { tickGame } from './GameSystem.js';
import { enqueueReward } from './RewardQueue.js';

export function reconcileOffline(state,now=Date.now()){
  const last=Number(state.offline.lastActiveTimestamp)||now;const durationMs=Math.max(0,now-last);if(state.offline.lastReconciledTimestamp===last||durationMs<BALANCE.offline.minimumRewardMs)return stampActive(state,now);
  const effectiveDurationMs=Math.min(durationMs,state.offline.capMs??BALANCE.offline.capMs);const before=offlineSnapshot(state);let next=simulateDuration(state,effectiveDurationMs);const after=offlineSnapshot(next);const results=offlineResults(before,after,state,next,durationMs,effectiveDurationMs);next={...next,offline:{...next.offline,lastActiveTimestamp:now,lastReconciledTimestamp:last,durationMs,effectiveDurationMs,capMs:state.offline.capMs??BALANCE.offline.capMs,results,periods:state.offline.periods+1,totalOfflineMs:state.offline.totalOfflineMs+effectiveDurationMs}};
  const lines=Object.entries(results.gains).filter(([,value])=>value>0).map(([key,value])=>({key,value}));if(lines.length||results.milestones.length){next={...next,offline:{...next.offline,rewardPending:true}};next=enqueueReward(next,{priority:results.milestones.length?'high':'normal',category:'offline',title:'WELCOME BACK',lines,metadata:{durationMs,effectiveDurationMs,milestones:results.milestones}})}return next;
}
export function simulateDuration(state,durationMs){let next=state,remaining=Math.max(0,durationMs);const chunk=durationMs<=BALANCE.offline.longThresholdMs?BALANCE.offline.shortChunkMs:BALANCE.offline.longChunkMs;while(remaining>0){const step=Math.min(chunk,remaining);next=tickGame(next,step);remaining-=step}return next}
export function stampActive(state,now=Date.now()){return{...state,offline:{...state.offline,lastActiveTimestamp:now,results:null}}}
function offlineSnapshot(state){return{credits:state.resources.credits,compute:state.resources.compute,users:state.resources.users,research:state.resources.research,modelXp:state.model.xp,modelLevel:state.model.level,patentProgress:state.patents.progress,patents:state.patents.discovered.length,missions:Object.keys(state.missions.claims).length}}
function offlineResults(before,after,original,next,durationMs,effectiveDurationMs){const gains={credits:Math.max(0,after.credits-before.credits),compute:Math.max(0,after.compute-before.compute),users:Math.max(0,after.users-before.users),modelXp:Math.max(0,after.modelXp-before.modelXp)};if(featureUnlocked(original,'research'))gains.research=Math.max(0,after.research-before.research);if(featureUnlocked(original,'patents'))gains.patentProgress=Math.max(0,after.patentProgress-before.patentProgress);const milestones=[];if(after.modelLevel>before.modelLevel)milestones.push(`Model reached Level ${after.modelLevel}`);if(after.patents>before.patents)milestones.push(`${after.patents-before.patents} Patent${after.patents-before.patents===1?'':'s'} discovered`);if(Object.keys(next.meta.achievements).length>Object.keys(original.meta.achievements).length)milestones.push('Achievement unlocked');return{durationMs,effectiveDurationMs,gains,milestones,startedAt:original.offline.lastActiveTimestamp,endedAt:(original.offline.lastActiveTimestamp??0)+durationMs}}
