import { BALANCE } from '../config/balance.js';
import { UPGRADES } from '../data/defaultState.js';
import { hasTechnologyMechanic, technologyEffect } from '../data/technologyCatalog.js';
import { earnGems, spendGems } from './GemSystem.js';
import { boundedResearchSpeed, researchLevelCost } from './ResearchEconomySystem.js';

const CATEGORIES=['COMPUTE SCIENCE','MACHINE LEARNING','MARKET SCIENCE','SYSTEMS ENGINEERING','FUNDAMENTAL RESEARCH'];
export const RESEARCH_PROJECTS=Object.freeze(UPGRADES.filter(upgrade=>upgrade.category==='research').map((upgrade,index)=>Object.freeze({
  id:upgrade.id,name:upgrade.name,description:upgrade.description,category:CATEGORIES[index%CATEGORIES.length],researchCost:upgrade.cost,
  baseDurationSeconds:[120,300,600,900,1_800,3_600][index]??3_600,effect:{type:upgrade.effect,value:upgrade.value},prerequisites:index?[]:[],repeatable:true,maxLevel:10,visualImportance:index>=4?'major':'standard',
})));

export function researchSpeed(state){
  const datacenters=(state.hardware?.hyperscaleDatacenter??0)+(state.hardware?.tpuCluster??0);
  const modelLevel=Math.max(1,state.model?.level??1);
  const patentBonus=(state.patents?.equipped??[]).includes('lab-notebook')?Math.min(.5,datacenters*.01):0;
  const permanent=technologyEffect(state,'researchSpeed')+Math.min(.5,datacenters*.01)+Math.floor(modelLevel/5)*.01+patentBonus;
  return BALANCE.research.baseSpeed*boundedResearchSpeed(permanent);
}
export function effectiveResearchDuration(state,project){return project.baseDurationSeconds/researchSpeed(state)}
export function researchProjectCost(state,project){const level=state.researchUpgradeLevels?.[project.id]??0;return Math.ceil(researchLevelCost(project.researchCost,level))}
export function unlockedResearchLabs(state){if(!state.meta.techNodes.includes('research-1'))return 0;return Math.min(BALANCE.research.maxLabs,1+(state.meta.techNodes.includes('research-4')?1:0)+(state.premium.purchases.includes('researchLab3')?1:0)+(state.premium.purchases.includes('researchLab4')?1:0)+(state.premium.purchases.includes('researchLab5')?1:0))}
export function canQueueResearch(state){return hasTechnologyMechanic(state,'research-queue-1')}
export function startResearchProject(state,projectId,labId){const project=RESEARCH_PROJECTS.find(item=>item.id===projectId),labs=state.researchLabs?.labs??[],index=labs.findIndex(lab=>lab.id===Number(labId)),lab=labs[index],level=state.researchUpgradeLevels?.[projectId]??0;if(!project||!lab||lab.id>unlockedResearchLabs(state)||level>=project.maxLevel)return state;const cost=researchProjectCost(state,project);if(state.resources.research<cost||lab.projectId)return state;const totalSeconds=effectiveResearchDuration(state,project);const nextLab={...lab,projectId,level:level+1,remainingSeconds:totalSeconds,totalSeconds,startedAt:Date.now()};return{...state,resources:{...state.resources,research:state.resources.research-cost},statistics:{...state.statistics,totalResearchPointsSpent:(state.statistics.totalResearchPointsSpent??0)+cost},researchLabs:{...state.researchLabs,unlocked:unlockedResearchLabs(state),labs:labs.map((entry,i)=>i===index?nextLab:entry),pointsSpent:(state.researchLabs.pointsSpent??0)+cost,lastStarted:{projectId,labId:lab.id,cost,researchSpeed:researchSpeed(state),at:Date.now()}}};}
export function tickResearchLabs(state,deltaMs){if(!state.researchLabs||deltaMs<=0)return state;const activeLabs=state.researchLabs.labs.filter(lab=>lab.projectId).length,completed=[];const labs=state.researchLabs.labs.map(lab=>{if(!lab.projectId)return lab;const remaining=lab.remainingSeconds-deltaMs/1000;if(remaining>0)return{...lab,remainingSeconds:remaining};completed.push({projectId:lab.projectId,level:lab.level,labId:lab.id,completedAt:Date.now()});return{...lab,projectId:null,level:null,remainingSeconds:0,totalSeconds:0,startedAt:null}}),statistics={...state.statistics,researchLabSeconds:(state.statistics.researchLabSeconds??0)+activeLabs*deltaMs/1000,peakActiveLabs:Math.max(state.statistics.peakActiveLabs??0,activeLabs),totalResearchProjects:(state.statistics.totalResearchProjects??0)+completed.length};if(!completed.length)return{...state,statistics,researchLabs:{...state.researchLabs,labs}};const levels={...state.researchUpgradeLevels};for(const entry of completed)levels[entry.projectId]=Math.max(levels[entry.projectId]??0,entry.level);const latest=completed.at(-1),project=RESEARCH_PROJECTS.find(item=>item.id===latest.projectId);return{...state,statistics,researchUpgradeLevels:levels,upgrades:[...new Set([...state.upgrades,...completed.map(entry=>entry.projectId)])],researchLabs:{...state.researchLabs,labs,completedProjects:[...(state.researchLabs.completedProjects??[]),...completed.map(entry=>`${entry.projectId}:${entry.level}`)],projectHistory:[...(state.researchLabs.projectHistory??[]),...completed].slice(-100),lastCompleted:latest},ui:{...state.ui,toast:{message:`Research complete · ${project?.name??latest.projectId} Level ${latest.level}`,id:Date.now()}}}}
export function purchaseResearchLab(state,labNumber){const lab=Number(labNumber),cost=BALANCE.research.labGemCosts[lab],id=`researchLab${lab}`;if(!cost||lab<3||lab>5||state.premium.purchases.includes(id))return state;const paid=spendGems(state,cost,'research-lab',{lab});if(paid===state)return state;return{...paid,premium:{...paid.premium,purchases:[...paid.premium.purchases,id]},researchLabs:{...paid.researchLabs,unlocked:unlockedResearchLabs({...paid,premium:{...paid.premium,purchases:[...paid.premium.purchases,id]}})}}}
export function claimDailyFreeGems(state,now=Date.now()){const last=state.premium.freeGemClaimedAt??0;if(last>0&&now-last<BALANCE.freeGems.cooldownMs)return state;const rewarded=earnGems(state,BALANCE.freeGems.amount,'daily-shop',{claimedAt:now});return rewarded===state?state:{...rewarded,premium:{...rewarded.premium,freeGemClaimedAt:now}}}
