#!/usr/bin/env node
// ANALYSIS ONLY — NOT LIVE ECONOMY. Candidate Phase-1 mathematics.
import fs from 'node:fs';
import { PATENTS } from '../src/data/defaultState.js';
import { TECHNOLOGY_NODES } from '../src/data/technologyCatalog.js';
const P=JSON.parse(fs.readFileSync(new URL('../MATHEMATICAL_ECONOMY_PARAMETERS_V1.json',import.meta.url)));
const log10=x=>x>0?Math.log10(x):null;
const bulk=(h,n,k)=>h.baseCost*h.costGrowth**n*(h.costGrowth**k-1)/(h.costGrowth-1);
const modelLevel=L=>1+.16*L**.62;
const trainingDuration=(L,tier=0)=>45+34*Math.sqrt(L)+P.training.durationSeconds.tierTransitionSeconds[tier];
const skill={qualityDemand:q=>1+.18*Math.log1p(q),qualityRevenue:q=>1+.12*Math.sqrt(q),efficiency:e=>1+.2*Math.sqrt(e),popularity:p=>1+.3*Math.sqrt(p)+.08*Math.log1p(p)};
const rep=r=>{const p=P.market.reputation;return p.minimum+(p.maximum-p.minimum)/(1+Math.exp(-p.slope*(r-p.midpoint)))};
const adoption=x=>1+.5*x/(50+x);
const wom=u=>{const p=P.market.wordOfMouth,z=Math.log1p(u/p.userScale);return 1+p.maximumBonus*z/(p.K+z)};
const marketing=m=>1+.32*Math.log1p(m);
const price=(p,tolerance=1)=>p<=1?1+.8*(1-p):Math.exp(-1.15*(p-1)/tolerance);
const demand=s=>P.market.baseMarketByModelTier[s.modelTier]*P.models.tierScale[s.modelTier]*modelLevel(s.level)*skill.qualityDemand(s.q)*skill.popularity(s.pop)*P.market.infrastructureReachByHighestHardwareTier[s.hwTier]*marketing(s.marketing)*rep(s.reputation)*adoption(s.adoption)*wom(s.users)*price(s.price,1+.1*Math.sqrt(s.q));
const entitlement=c=>Math.floor((c/P.prestige.entitlement.C0)**P.prestige.entitlement.alpha);
const references=[
 ['R0 Fresh',0,0,1,0,0,0,0],['R1 Early first run',2,0,3,1,1,1,0],['R2 Server Rack',5,0,11,3,4,10,2.2e5],['R3 GPU Cluster',6,1,15,5,7,16,1.2e6],['R4 First Cycle',6,1,18,6,8,20,3e6],['R5 5 Cycles',7,2,25,10,13,30,2e7],['R6 20 Cycles',8,3,35,16,22,45,2e8],['R7 Advanced Datacenter',9,4,50,24,35,65,2e9],['R8 AGI',11,7,75,40,55,90,4e10],['R9 ASI Seed',12,8,100,60,80,120,8e11],['R10 Dyson',13,8,180,90,120,180,2e13],['R11 Matrioshka',14,8,300,140,180,260,8e14],['R12 Singularity Core',15,8,500,220,280,400,5e16]
].map(([name,hwTier,modelTier,level,q,pop,m,users])=>{const h=Object.values(P.hardware)[hwTier],owned=hwTier<3?20:hwTier<8?12:6,compute=h.baseProduction*owned*(1+Math.sqrt(level)/8),s={hwTier,modelTier,level,q,pop,marketing:m,users,reputation:1,adoption:100,price:1},potential=demand(s),capacity=compute*.35*skill.efficiency(Math.max(1,q)),served=Math.min(users,potential,capacity),rpu=.24*skill.qualityRevenue(q),revenue=served*rpu,research=4*(Math.max(0,compute*.1)/1000)**.72;return{name,hardware:h.displayName,modelTier,level,compute,potentialDemand:potential,users,capacity,utilization:capacity?served/capacity:0,revenuePerUser:rpu,revenuePerSecond:revenue,researchPerSecond:research,researchSpeed:1+1.5*(hwTier+level/5)/(20+hwTier+level/5),intEntitlement:entitlement(compute*3600),logs:{compute:log10(compute),demand:log10(potential),revenue:log10(revenue)}}});
const hardware=Object.entries(P.hardware).map(([id,h])=>({id,name:h.displayName,era:h.era,baseCost:h.baseCost,baseProduction:h.baseProduction,growth:h.costGrowth,costAt10:h.baseCost*h.costGrowth**10,bulk1to10:bulk(h,0,10),roiProductionPerCost:h.baseProduction/h.baseCost,marginalROI:{n1:h.baseProduction/(h.baseCost*h.costGrowth),n10:h.baseProduction/(h.baseCost*h.costGrowth**10),n25:h.baseProduction/(h.baseCost*h.costGrowth**25),n50:h.baseProduction/(h.baseCost*h.costGrowth**50),n100:h.baseProduction/(h.baseCost*h.costGrowth**100)}}));
const levels=[1,5,10,20,50,100,250,500].map(level=>({level,modelLevelFactor:modelLevel(level),targetDurationSeconds:trainingDuration(level),log10RequirementAtOneComputePerSecond:log10(trainingDuration(level))}));
const priceSensitivity=[.5,.75,1,1.25,1.5,2,2.5,3].map(p=>({price:p,demandFactor:price(p,1.25),revenueIndex:p*price(p,1.25)}));
const halfLives=[0,5,20,50,100].map(x=>({investment:x,acquisitionSeconds:Math.max(30,180/(1+.08*Math.sqrt(x)+.06*Math.log1p(x))),churnSeconds:90}));
const firstRun=[5,10,15,20,30,45,60,75,90].map(minutes=>{const stage=Math.min(6,Math.floor(minutes/13)),h=Object.values(P.hardware)[stage],level=Math.max(1,Math.floor(1+minutes/6)),compute=h.baseProduction*(4+minutes/4),users=Math.max(0,80*(Math.exp(minutes/15)-1)),d=Math.max(users*1.3,80*modelLevel(level)*(1+.32*Math.log1p(minutes/5))),capacity=compute*.35*(1+.2*Math.sqrt(level/2));return{minutes,highestHardware:h.displayName,totalHardware:Math.round(4+minutes/3),computePerSecond:compute,model:'TinyChat',modelLevel:level,trainingEtaSeconds:trainingDuration(level),users,demand:d,capacity,utilization:Math.min(1,users/Math.max(1,capacity)),revenuePerSecond:Math.min(users,d,capacity)*.24,marketingLevel:Math.floor(minutes/5),allocation:minutes<20?'60/40':'70/30',nextGoal:stage<6?Object.values(P.hardware)[stage+1].displayName:'Development Cycle',nextGoalEtaSeconds:Math.max(30,600-minutes*4),meaningfulActions:['Hardware','Training','Marketing'],estimatedINT:entitlement(compute*minutes*60)} });
const strategies=[['BALANCED',78],['TRAINING-HEAVY',84],['MARKET-HEAVY',82],['HARDWARE-HEAVY',73],['LOW-INTERACTION',105],['HIGHLY-OPTIMIZED',64]].map(([strategy,minutes])=>({strategy,minutes,withinTarget:minutes>=60&&minutes<=90,note:'calibration anchor, not human prediction'}));
const intCurve=[4e8,4e10,4e12,4e16,4e24,4e40,4e80,4e160,4e300].map(compute=>({compute,log10Compute:log10(compute),entitlement:entitlement(compute),log10Entitlement:log10(Math.max(1,entitlement(compute)))}));
const technology=TECHNOLOGY_NODES.map(node=>{const depth=node.depth??node.rank??1,expectedIntGain=2**Math.floor(Math.max(0,depth-1)/2),typeMultiplier=P.technology.typeMultipliers[node.type]??1,proposedCost=Math.max(1,Math.round(expectedIntGain*(1+.45*depth)**1.55*typeMultiplier/4));const equivalentPower=1+Math.abs(node.value??0);return{id:node.id,name:node.name,branch:node.branch,depth,type:node.type,currentCost:node.cost,proposedCost,expectedIntGain,runCostEquivalent:proposedCost/expectedIntGain,equivalentPower,powerCostRatio:(equivalentPower-1)/proposedCost,outlier:node.cost>proposedCost*5?'CURRENT_COST_HIGH':node.cost*5<proposedCost?'CURRENT_COST_LOW':null}});
const patents=PATENTS.map(p=>({id:p.id,name:p.name,effect:p.effect,value:p.value,mode:p.synergy?'BOUNDED_OR_TRANSFORM':'ADD',equivalentPowerEarly:1+p.value,equivalentPowerMid:1+p.value*1.5,equivalentPowerLate:1+p.value*2,dominantRisk:p.synergy&&!/cap|maximum|bounded/i.test(`${p.description} ${p.synergy}`)?'REQUIRES_EXPLICIT_CAP_AUDIT':null}));
const output={status:P.status,generatedAt:'deterministic',hardware,levels,technology,patents,priceSensitivity,acquisitionHalfLives:halfLives,references,firstRun,strategies,intCurve,invariants:{bulkFormulaFinite:hardware.every(x=>Number.isFinite(x.bulk1to10)),bulkClosedFormEqualsSum:Object.values(P.hardware).every(h=>Math.abs(bulk(h,7,25)-Array.from({length:25},(_,j)=>h.baseCost*h.costGrowth**(7+j)).reduce((a,b)=>a+b,0))<=Math.max(1,bulk(h,7,25))*1e-12),hardwareCostsMonotonic:hardware.every(x=>x.growth>1),trainingMonotonic:levels.every((x,i)=>!i||x.targetDurationSeconds>levels[i-1].targetDurationSeconds),demandIndependentOfInference:(()=>{const s={hwTier:5,modelTier:2,level:20,q:8,pop:10,marketing:20,users:1e6,reputation:1,adoption:100,price:1,inferenceAllocation:.1};return demand(s)===demand({...s,inferenceAllocation:.9})})(),servedUsersBounded:references.every(x=>x.utilization<=1),researchFinite:references.every(x=>Number.isFinite(x.researchPerSecond)&&Number.isFinite(x.researchSpeed)),numberSafety:references.every(x=>Object.values(x.logs).filter(v=>v!==null).every(v=>v<100))}};
const json=JSON.stringify(output,null,2);if(process.argv.includes('--json'))console.log(json);else {fs.writeFileSync(new URL('../MATHEMATICAL_ECONOMY_ANALYSIS_V1.json',import.meta.url),json+'\n');console.log('Wrote MATHEMATICAL_ECONOMY_ANALYSIS_V1.json');}
